
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  vendors: 'vendors',
  category: 'category',
  lokasi_gudang: 'lokasi_gudang',
  produk: 'produk',
  barang_masuk: 'barang_masuk',
  barang_keluar: 'barang_keluar'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const VendorsScalarFieldEnum = {
  id: 'id',
  nama_vendor: 'nama_vendor',
  warna_vendor: 'warna_vendor',
  alamat_vendor: 'alamat_vendor'
} as const

export type VendorsScalarFieldEnum = (typeof VendorsScalarFieldEnum)[keyof typeof VendorsScalarFieldEnum]


export const CategoryScalarFieldEnum = {
  id: 'id',
  nama_kategori: 'nama_kategori',
  warna_category: 'warna_category'
} as const

export type CategoryScalarFieldEnum = (typeof CategoryScalarFieldEnum)[keyof typeof CategoryScalarFieldEnum]


export const Lokasi_gudangScalarFieldEnum = {
  id: 'id',
  nama_gudang: 'nama_gudang',
  alamat_gudang: 'alamat_gudang',
  warna_gudang: 'warna_gudang'
} as const

export type Lokasi_gudangScalarFieldEnum = (typeof Lokasi_gudangScalarFieldEnum)[keyof typeof Lokasi_gudangScalarFieldEnum]


export const ProdukScalarFieldEnum = {
  id: 'id',
  nama_produk: 'nama_produk',
  kategoriId: 'kategoriId',
  vendorsId: 'vendorsId',
  jumlah: 'jumlah',
  lokasiId: 'lokasiId'
} as const

export type ProdukScalarFieldEnum = (typeof ProdukScalarFieldEnum)[keyof typeof ProdukScalarFieldEnum]


export const Barang_masukScalarFieldEnum = {
  id: 'id',
  produkId: 'produkId',
  tanggal_masuk: 'tanggal_masuk',
  nominal_modal: 'nominal_modal',
  jumlah_barang_masuk: 'jumlah_barang_masuk'
} as const

export type Barang_masukScalarFieldEnum = (typeof Barang_masukScalarFieldEnum)[keyof typeof Barang_masukScalarFieldEnum]


export const Barang_keluarScalarFieldEnum = {
  id: 'id',
  produkId: 'produkId',
  tanggal_keluar: 'tanggal_keluar',
  nominal_modal: 'nominal_modal',
  jumlah_barang_keluar: 'jumlah_barang_keluar'
} as const

export type Barang_keluarScalarFieldEnum = (typeof Barang_keluarScalarFieldEnum)[keyof typeof Barang_keluarScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]

