
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/client"
import type * as Prisma from "../models"
import { type PrismaClient } from "./class"

export type * from '../models'

export type DMMF = typeof runtime.DMMF

export type PrismaPromise<T> = runtime.Types.Public.PrismaPromise<T>

/**
 * Prisma Errors
 */

export const PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError
export type PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError

export const PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError
export type PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError

export const PrismaClientRustPanicError = runtime.PrismaClientRustPanicError
export type PrismaClientRustPanicError = runtime.PrismaClientRustPanicError

export const PrismaClientInitializationError = runtime.PrismaClientInitializationError
export type PrismaClientInitializationError = runtime.PrismaClientInitializationError

export const PrismaClientValidationError = runtime.PrismaClientValidationError
export type PrismaClientValidationError = runtime.PrismaClientValidationError

/**
 * Re-export of sql-template-tag
 */
export const sql = runtime.sqltag
export const empty = runtime.empty
export const join = runtime.join
export const raw = runtime.raw
export const Sql = runtime.Sql
export type Sql = runtime.Sql



/**
 * Decimal.js
 */
export const Decimal = runtime.Decimal
export type Decimal = runtime.Decimal

export type DecimalJsLike = runtime.DecimalJsLike

/**
* Extensions
*/
export type Extension = runtime.Types.Extensions.UserArgs
export const getExtensionContext = runtime.Extensions.getExtensionContext
export type Args<T, F extends runtime.Operation> = runtime.Types.Public.Args<T, F>
export type Payload<T, F extends runtime.Operation = never> = runtime.Types.Public.Payload<T, F>
export type Result<T, A, F extends runtime.Operation> = runtime.Types.Public.Result<T, A, F>
export type Exact<A, W> = runtime.Types.Public.Exact<A, W>

export type PrismaVersion = {
  client: string
  engine: string
}

/**
 * Prisma Client JS version: 7.4.2
 * Query Engine version: 94a226be1cf2967af2541cca5529f0f7ba866919
 */
export const prismaVersion: PrismaVersion = {
  client: "7.4.2",
  engine: "94a226be1cf2967af2541cca5529f0f7ba866919"
}

/**
 * Utility Types
 */

export type Bytes = runtime.Bytes
export type JsonObject = runtime.JsonObject
export type JsonArray = runtime.JsonArray
export type JsonValue = runtime.JsonValue
export type InputJsonObject = runtime.InputJsonObject
export type InputJsonArray = runtime.InputJsonArray
export type InputJsonValue = runtime.InputJsonValue


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


type SelectAndInclude = {
  select: any
  include: any
}

type SelectAndOmit = {
  select: any
  omit: any
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
type Prisma__Pick<T, K extends keyof T> = {
    [P in K]: T[P];
};

export type Enumerable<T> = T | Array<T>;

/**
 * Subset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection
 */
export type Subset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never;
};

/**
 * SelectSubset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection.
 * Additionally, it validates, if both select and include are present. If the case, it errors.
 */
export type SelectSubset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  (T extends SelectAndInclude
    ? 'Please either choose `select` or `include`.'
    : T extends SelectAndOmit
      ? 'Please either choose `select` or `omit`.'
      : {})

/**
 * Subset + Intersection
 * @desc From `T` pick properties that exist in `U` and intersect `K`
 */
export type SubsetIntersection<T, U, K> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  K

type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };

/**
 * XOR is needed to have a real mutually exclusive union type
 * https://stackoverflow.com/questions/42123407/does-typescript-support-mutually-exclusive-types
 */
export type XOR<T, U> =
  T extends object ?
  U extends object ?
    (Without<T, U> & U) | (Without<U, T> & T)
  : U : T


/**
 * Is T a Record?
 */
type IsObject<T extends any> = T extends Array<any>
? False
: T extends Date
? False
: T extends Uint8Array
? False
: T extends BigInt
? False
: T extends object
? True
: False


/**
 * If it's T[], return T
 */
export type UnEnumerate<T extends unknown> = T extends Array<infer U> ? U : T

/**
 * From ts-toolbelt
 */

type __Either<O extends object, K extends Key> = Omit<O, K> &
  {
    // Merge all but K
    [P in K]: Prisma__Pick<O, P & keyof O> // With K possibilities
  }[K]

type EitherStrict<O extends object, K extends Key> = Strict<__Either<O, K>>

type EitherLoose<O extends object, K extends Key> = ComputeRaw<__Either<O, K>>

type _Either<
  O extends object,
  K extends Key,
  strict extends Boolean
> = {
  1: EitherStrict<O, K>
  0: EitherLoose<O, K>
}[strict]

export type Either<
  O extends object,
  K extends Key,
  strict extends Boolean = 1
> = O extends unknown ? _Either<O, K, strict> : never

export type Union = any

export type PatchUndefined<O extends object, O1 extends object> = {
  [K in keyof O]: O[K] extends undefined ? At<O1, K> : O[K]
} & {}

/** Helper Types for "Merge" **/
export type IntersectOf<U extends Union> = (
  U extends unknown ? (k: U) => void : never
) extends (k: infer I) => void
  ? I
  : never

export type Overwrite<O extends object, O1 extends object> = {
    [K in keyof O]: K extends keyof O1 ? O1[K] : O[K];
} & {};

type _Merge<U extends object> = IntersectOf<Overwrite<U, {
    [K in keyof U]-?: At<U, K>;
}>>;

type Key = string | number | symbol;
type AtStrict<O extends object, K extends Key> = O[K & keyof O];
type AtLoose<O extends object, K extends Key> = O extends unknown ? AtStrict<O, K> : never;
export type At<O extends object, K extends Key, strict extends Boolean = 1> = {
    1: AtStrict<O, K>;
    0: AtLoose<O, K>;
}[strict];

export type ComputeRaw<A extends any> = A extends Function ? A : {
  [K in keyof A]: A[K];
} & {};

export type OptionalFlat<O> = {
  [K in keyof O]?: O[K];
} & {};

type _Record<K extends keyof any, T> = {
  [P in K]: T;
};

// cause typescript not to expand types and preserve names
type NoExpand<T> = T extends unknown ? T : never;

// this type assumes the passed object is entirely optional
export type AtLeast<O extends object, K extends string> = NoExpand<
  O extends unknown
  ? | (K extends keyof O ? { [P in K]: O[P] } & O : O)
    | {[P in keyof O as P extends K ? P : never]-?: O[P]} & O
  : never>;

type _Strict<U, _U = U> = U extends unknown ? U & OptionalFlat<_Record<Exclude<Keys<_U>, keyof U>, never>> : never;

export type Strict<U extends object> = ComputeRaw<_Strict<U>>;
/** End Helper Types for "Merge" **/

export type Merge<U extends object> = ComputeRaw<_Merge<Strict<U>>>;

export type Boolean = True | False

export type True = 1

export type False = 0

export type Not<B extends Boolean> = {
  0: 1
  1: 0
}[B]

export type Extends<A1 extends any, A2 extends any> = [A1] extends [never]
  ? 0 // anything `never` is false
  : A1 extends A2
  ? 1
  : 0

export type Has<U extends Union, U1 extends Union> = Not<
  Extends<Exclude<U1, U>, U1>
>

export type Or<B1 extends Boolean, B2 extends Boolean> = {
  0: {
    0: 0
    1: 1
  }
  1: {
    0: 1
    1: 1
  }
}[B1][B2]

export type Keys<U extends Union> = U extends unknown ? keyof U : never

export type GetScalarType<T, O> = O extends object ? {
  [P in keyof T]: P extends keyof O
    ? O[P]
    : never
} : never

type FieldPaths<
  T,
  U = Omit<T, '_avg' | '_sum' | '_count' | '_min' | '_max'>
> = IsObject<T> extends True ? U : T

export type GetHavingFields<T> = {
  [K in keyof T]: Or<
    Or<Extends<'OR', K>, Extends<'AND', K>>,
    Extends<'NOT', K>
  > extends True
    ? // infer is only needed to not hit TS limit
      // based on the brilliant idea of Pierre-Antoine Mills
      // https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
      T[K] extends infer TK
      ? GetHavingFields<UnEnumerate<TK> extends object ? Merge<UnEnumerate<TK>> : never>
      : never
    : {} extends FieldPaths<T[K]>
    ? never
    : K
}[keyof T]

/**
 * Convert tuple to union
 */
type _TupleToUnion<T> = T extends (infer E)[] ? E : never
type TupleToUnion<K extends readonly any[]> = _TupleToUnion<K>
export type MaybeTupleToUnion<T> = T extends any[] ? TupleToUnion<T> : T

/**
 * Like `Pick`, but additionally can also accept an array of keys
 */
export type PickEnumerable<T, K extends Enumerable<keyof T> | keyof T> = Prisma__Pick<T, MaybeTupleToUnion<K>>

/**
 * Exclude all keys with underscores
 */
export type ExcludeUnderscoreKeys<T extends string> = T extends `_${string}` ? never : T


export type FieldRef<Model, FieldType> = runtime.FieldRef<Model, FieldType>

type FieldRefInputType<Model, FieldType> = Model extends never ? never : FieldRef<Model, FieldType>


export const ModelName = {
  vendors: 'vendors',
  category: 'category',
  lokasi_gudang: 'lokasi_gudang',
  produk: 'produk',
  barang_masuk: 'barang_masuk',
  barang_keluar: 'barang_keluar'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]



export interface TypeMapCb<GlobalOmitOptions = {}> extends runtime.Types.Utils.Fn<{extArgs: runtime.Types.Extensions.InternalArgs }, runtime.Types.Utils.Record<string, any>> {
  returns: TypeMap<this['params']['extArgs'], GlobalOmitOptions>
}

export type TypeMap<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> = {
  globalOmitOptions: {
    omit: GlobalOmitOptions
  }
  meta: {
    modelProps: "vendors" | "category" | "lokasi_gudang" | "produk" | "barang_masuk" | "barang_keluar"
    txIsolationLevel: TransactionIsolationLevel
  }
  model: {
    vendors: {
      payload: Prisma.$vendorsPayload<ExtArgs>
      fields: Prisma.vendorsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.vendorsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$vendorsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.vendorsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$vendorsPayload>
        }
        findFirst: {
          args: Prisma.vendorsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$vendorsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.vendorsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$vendorsPayload>
        }
        findMany: {
          args: Prisma.vendorsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$vendorsPayload>[]
        }
        create: {
          args: Prisma.vendorsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$vendorsPayload>
        }
        createMany: {
          args: Prisma.vendorsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.vendorsCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$vendorsPayload>[]
        }
        delete: {
          args: Prisma.vendorsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$vendorsPayload>
        }
        update: {
          args: Prisma.vendorsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$vendorsPayload>
        }
        deleteMany: {
          args: Prisma.vendorsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.vendorsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.vendorsUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$vendorsPayload>[]
        }
        upsert: {
          args: Prisma.vendorsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$vendorsPayload>
        }
        aggregate: {
          args: Prisma.VendorsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateVendors>
        }
        groupBy: {
          args: Prisma.vendorsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.VendorsGroupByOutputType>[]
        }
        count: {
          args: Prisma.vendorsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.VendorsCountAggregateOutputType> | number
        }
      }
    }
    category: {
      payload: Prisma.$categoryPayload<ExtArgs>
      fields: Prisma.categoryFieldRefs
      operations: {
        findUnique: {
          args: Prisma.categoryFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$categoryPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.categoryFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$categoryPayload>
        }
        findFirst: {
          args: Prisma.categoryFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$categoryPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.categoryFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$categoryPayload>
        }
        findMany: {
          args: Prisma.categoryFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$categoryPayload>[]
        }
        create: {
          args: Prisma.categoryCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$categoryPayload>
        }
        createMany: {
          args: Prisma.categoryCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.categoryCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$categoryPayload>[]
        }
        delete: {
          args: Prisma.categoryDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$categoryPayload>
        }
        update: {
          args: Prisma.categoryUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$categoryPayload>
        }
        deleteMany: {
          args: Prisma.categoryDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.categoryUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.categoryUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$categoryPayload>[]
        }
        upsert: {
          args: Prisma.categoryUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$categoryPayload>
        }
        aggregate: {
          args: Prisma.CategoryAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateCategory>
        }
        groupBy: {
          args: Prisma.categoryGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CategoryGroupByOutputType>[]
        }
        count: {
          args: Prisma.categoryCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CategoryCountAggregateOutputType> | number
        }
      }
    }
    lokasi_gudang: {
      payload: Prisma.$lokasi_gudangPayload<ExtArgs>
      fields: Prisma.lokasi_gudangFieldRefs
      operations: {
        findUnique: {
          args: Prisma.lokasi_gudangFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$lokasi_gudangPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.lokasi_gudangFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$lokasi_gudangPayload>
        }
        findFirst: {
          args: Prisma.lokasi_gudangFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$lokasi_gudangPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.lokasi_gudangFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$lokasi_gudangPayload>
        }
        findMany: {
          args: Prisma.lokasi_gudangFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$lokasi_gudangPayload>[]
        }
        create: {
          args: Prisma.lokasi_gudangCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$lokasi_gudangPayload>
        }
        createMany: {
          args: Prisma.lokasi_gudangCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.lokasi_gudangCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$lokasi_gudangPayload>[]
        }
        delete: {
          args: Prisma.lokasi_gudangDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$lokasi_gudangPayload>
        }
        update: {
          args: Prisma.lokasi_gudangUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$lokasi_gudangPayload>
        }
        deleteMany: {
          args: Prisma.lokasi_gudangDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.lokasi_gudangUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.lokasi_gudangUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$lokasi_gudangPayload>[]
        }
        upsert: {
          args: Prisma.lokasi_gudangUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$lokasi_gudangPayload>
        }
        aggregate: {
          args: Prisma.Lokasi_gudangAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateLokasi_gudang>
        }
        groupBy: {
          args: Prisma.lokasi_gudangGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Lokasi_gudangGroupByOutputType>[]
        }
        count: {
          args: Prisma.lokasi_gudangCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Lokasi_gudangCountAggregateOutputType> | number
        }
      }
    }
    produk: {
      payload: Prisma.$produkPayload<ExtArgs>
      fields: Prisma.produkFieldRefs
      operations: {
        findUnique: {
          args: Prisma.produkFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$produkPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.produkFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$produkPayload>
        }
        findFirst: {
          args: Prisma.produkFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$produkPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.produkFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$produkPayload>
        }
        findMany: {
          args: Prisma.produkFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$produkPayload>[]
        }
        create: {
          args: Prisma.produkCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$produkPayload>
        }
        createMany: {
          args: Prisma.produkCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.produkCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$produkPayload>[]
        }
        delete: {
          args: Prisma.produkDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$produkPayload>
        }
        update: {
          args: Prisma.produkUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$produkPayload>
        }
        deleteMany: {
          args: Prisma.produkDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.produkUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.produkUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$produkPayload>[]
        }
        upsert: {
          args: Prisma.produkUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$produkPayload>
        }
        aggregate: {
          args: Prisma.ProdukAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateProduk>
        }
        groupBy: {
          args: Prisma.produkGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ProdukGroupByOutputType>[]
        }
        count: {
          args: Prisma.produkCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ProdukCountAggregateOutputType> | number
        }
      }
    }
    barang_masuk: {
      payload: Prisma.$barang_masukPayload<ExtArgs>
      fields: Prisma.barang_masukFieldRefs
      operations: {
        findUnique: {
          args: Prisma.barang_masukFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$barang_masukPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.barang_masukFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$barang_masukPayload>
        }
        findFirst: {
          args: Prisma.barang_masukFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$barang_masukPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.barang_masukFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$barang_masukPayload>
        }
        findMany: {
          args: Prisma.barang_masukFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$barang_masukPayload>[]
        }
        create: {
          args: Prisma.barang_masukCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$barang_masukPayload>
        }
        createMany: {
          args: Prisma.barang_masukCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.barang_masukCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$barang_masukPayload>[]
        }
        delete: {
          args: Prisma.barang_masukDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$barang_masukPayload>
        }
        update: {
          args: Prisma.barang_masukUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$barang_masukPayload>
        }
        deleteMany: {
          args: Prisma.barang_masukDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.barang_masukUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.barang_masukUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$barang_masukPayload>[]
        }
        upsert: {
          args: Prisma.barang_masukUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$barang_masukPayload>
        }
        aggregate: {
          args: Prisma.Barang_masukAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateBarang_masuk>
        }
        groupBy: {
          args: Prisma.barang_masukGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Barang_masukGroupByOutputType>[]
        }
        count: {
          args: Prisma.barang_masukCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Barang_masukCountAggregateOutputType> | number
        }
      }
    }
    barang_keluar: {
      payload: Prisma.$barang_keluarPayload<ExtArgs>
      fields: Prisma.barang_keluarFieldRefs
      operations: {
        findUnique: {
          args: Prisma.barang_keluarFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$barang_keluarPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.barang_keluarFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$barang_keluarPayload>
        }
        findFirst: {
          args: Prisma.barang_keluarFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$barang_keluarPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.barang_keluarFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$barang_keluarPayload>
        }
        findMany: {
          args: Prisma.barang_keluarFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$barang_keluarPayload>[]
        }
        create: {
          args: Prisma.barang_keluarCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$barang_keluarPayload>
        }
        createMany: {
          args: Prisma.barang_keluarCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.barang_keluarCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$barang_keluarPayload>[]
        }
        delete: {
          args: Prisma.barang_keluarDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$barang_keluarPayload>
        }
        update: {
          args: Prisma.barang_keluarUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$barang_keluarPayload>
        }
        deleteMany: {
          args: Prisma.barang_keluarDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.barang_keluarUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.barang_keluarUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$barang_keluarPayload>[]
        }
        upsert: {
          args: Prisma.barang_keluarUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$barang_keluarPayload>
        }
        aggregate: {
          args: Prisma.Barang_keluarAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateBarang_keluar>
        }
        groupBy: {
          args: Prisma.barang_keluarGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Barang_keluarGroupByOutputType>[]
        }
        count: {
          args: Prisma.barang_keluarCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Barang_keluarCountAggregateOutputType> | number
        }
      }
    }
  }
} & {
  other: {
    payload: any
    operations: {
      $executeRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $executeRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
      $queryRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $queryRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
    }
  }
}

/**
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const VendorsScalarFieldEnum = {
  id: 'id',
  nama_vendor: 'nama_vendor',
  warna_vendor: 'warna_vendor',
  alamat_vendor: 'alamat_vendor'
} as const

export type VendorsScalarFieldEnum = (typeof VendorsScalarFieldEnum)[keyof typeof VendorsScalarFieldEnum]


export const CategoryScalarFieldEnum = {
  id: 'id',
  nama_kategori: 'nama_kategori',
  warna_category: 'warna_category'
} as const

export type CategoryScalarFieldEnum = (typeof CategoryScalarFieldEnum)[keyof typeof CategoryScalarFieldEnum]


export const Lokasi_gudangScalarFieldEnum = {
  id: 'id',
  nama_gudang: 'nama_gudang',
  alamat_gudang: 'alamat_gudang',
  warna_gudang: 'warna_gudang'
} as const

export type Lokasi_gudangScalarFieldEnum = (typeof Lokasi_gudangScalarFieldEnum)[keyof typeof Lokasi_gudangScalarFieldEnum]


export const ProdukScalarFieldEnum = {
  id: 'id',
  nama_produk: 'nama_produk',
  kategoriId: 'kategoriId',
  vendorsId: 'vendorsId',
  jumlah: 'jumlah',
  lokasiId: 'lokasiId'
} as const

export type ProdukScalarFieldEnum = (typeof ProdukScalarFieldEnum)[keyof typeof ProdukScalarFieldEnum]


export const Barang_masukScalarFieldEnum = {
  id: 'id',
  produkId: 'produkId',
  tanggal_masuk: 'tanggal_masuk',
  nominal_modal: 'nominal_modal',
  jumlah_barang_masuk: 'jumlah_barang_masuk'
} as const

export type Barang_masukScalarFieldEnum = (typeof Barang_masukScalarFieldEnum)[keyof typeof Barang_masukScalarFieldEnum]


export const Barang_keluarScalarFieldEnum = {
  id: 'id',
  produkId: 'produkId',
  tanggal_keluar: 'tanggal_keluar',
  nominal_modal: 'nominal_modal',
  jumlah_barang_keluar: 'jumlah_barang_keluar'
} as const

export type Barang_keluarScalarFieldEnum = (typeof Barang_keluarScalarFieldEnum)[keyof typeof Barang_keluarScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]



/**
 * Field references
 */


/**
 * Reference to a field of type 'Int'
 */
export type IntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int'>
    


/**
 * Reference to a field of type 'Int[]'
 */
export type ListIntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int[]'>
    


/**
 * Reference to a field of type 'String'
 */
export type StringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String'>
    


/**
 * Reference to a field of type 'String[]'
 */
export type ListStringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String[]'>
    


/**
 * Reference to a field of type 'DateTime'
 */
export type DateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime'>
    


/**
 * Reference to a field of type 'DateTime[]'
 */
export type ListDateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime[]'>
    


/**
 * Reference to a field of type 'Float'
 */
export type FloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float'>
    


/**
 * Reference to a field of type 'Float[]'
 */
export type ListFloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float[]'>
    

/**
 * Batch Payload for updateMany & deleteMany & createMany
 */
export type BatchPayload = {
  count: number
}

export const defineExtension = runtime.Extensions.defineExtension as unknown as runtime.Types.Extensions.ExtendsHook<"define", TypeMapCb, runtime.Types.Extensions.DefaultArgs>
export type DefaultPrismaClient = PrismaClient
export type ErrorFormat = 'pretty' | 'colorless' | 'minimal'
export type PrismaClientOptions = ({
  /**
   * Instance of a Driver Adapter, e.g., like one provided by `@prisma/adapter-pg`.
   */
  adapter: runtime.SqlDriverAdapterFactory
  accelerateUrl?: never
} | {
  /**
   * Prisma Accelerate URL allowing the client to connect through Accelerate instead of a direct database.
   */
  accelerateUrl: string
  adapter?: never
}) & {
  /**
   * @default "colorless"
   */
  errorFormat?: ErrorFormat
  /**
   * @example
   * ```
   * // Shorthand for `emit: 'stdout'`
   * log: ['query', 'info', 'warn', 'error']
   * 
   * // Emit as events only
   * log: [
   *   { emit: 'event', level: 'query' },
   *   { emit: 'event', level: 'info' },
   *   { emit: 'event', level: 'warn' }
   *   { emit: 'event', level: 'error' }
   * ]
   * 
   * / Emit as events and log to stdout
   * og: [
   *  { emit: 'stdout', level: 'query' },
   *  { emit: 'stdout', level: 'info' },
   *  { emit: 'stdout', level: 'warn' }
   *  { emit: 'stdout', level: 'error' }
   * 
   * ```
   * Read more in our [docs](https://pris.ly/d/logging).
   */
  log?: (LogLevel | LogDefinition)[]
  /**
   * The default values for transactionOptions
   * maxWait ?= 2000
   * timeout ?= 5000
   */
  transactionOptions?: {
    maxWait?: number
    timeout?: number
    isolationLevel?: TransactionIsolationLevel
  }
  /**
   * Global configuration for omitting model fields by default.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   omit: {
   *     user: {
   *       password: true
   *     }
   *   }
   * })
   * ```
   */
  omit?: GlobalOmitConfig
  /**
   * SQL commenter plugins that add metadata to SQL queries as comments.
   * Comments follow the sqlcommenter format: https://google.github.io/sqlcommenter/
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   comments: [
   *     traceContext(),
   *     queryInsights(),
   *   ],
   * })
   * ```
   */
  comments?: runtime.SqlCommenterPlugin[]
}
export type GlobalOmitConfig = {
  vendors?: Prisma.vendorsOmit
  category?: Prisma.categoryOmit
  lokasi_gudang?: Prisma.lokasi_gudangOmit
  produk?: Prisma.produkOmit
  barang_masuk?: Prisma.barang_masukOmit
  barang_keluar?: Prisma.barang_keluarOmit
}

/* Types for Logging */
export type LogLevel = 'info' | 'query' | 'warn' | 'error'
export type LogDefinition = {
  level: LogLevel
  emit: 'stdout' | 'event'
}

export type CheckIsLogLevel<T> = T extends LogLevel ? T : never;

export type GetLogType<T> = CheckIsLogLevel<
  T extends LogDefinition ? T['level'] : T
>;

export type GetEvents<T extends any[]> = T extends Array<LogLevel | LogDefinition>
  ? GetLogType<T[number]>
  : never;

export type QueryEvent = {
  timestamp: Date
  query: string
  params: string
  duration: number
  target: string
}

export type LogEvent = {
  timestamp: Date
  message: string
  target: string
}
/* End Types for Logging */


export type PrismaAction =
  | 'findUnique'
  | 'findUniqueOrThrow'
  | 'findMany'
  | 'findFirst'
  | 'findFirstOrThrow'
  | 'create'
  | 'createMany'
  | 'createManyAndReturn'
  | 'update'
  | 'updateMany'
  | 'updateManyAndReturn'
  | 'upsert'
  | 'delete'
  | 'deleteMany'
  | 'executeRaw'
  | 'queryRaw'
  | 'aggregate'
  | 'count'
  | 'runCommandRaw'
  | 'findRaw'
  | 'groupBy'

/**
 * `PrismaClient` proxy available in interactive transactions.
 */
export type TransactionClient = Omit<DefaultPrismaClient, runtime.ITXClientDenyList>

