
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `barang_keluar` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model barang_keluar
 * 
 */
export type barang_keluarModel = runtime.Types.Result.DefaultSelection<Prisma.$barang_keluarPayload>

export type AggregateBarang_keluar = {
  _count: Barang_keluarCountAggregateOutputType | null
  _avg: Barang_keluarAvgAggregateOutputType | null
  _sum: Barang_keluarSumAggregateOutputType | null
  _min: Barang_keluarMinAggregateOutputType | null
  _max: Barang_keluarMaxAggregateOutputType | null
}

export type Barang_keluarAvgAggregateOutputType = {
  id: number | null
  produkId: number | null
  nominal_modal: number | null
  jumlah_barang_keluar: number | null
}

export type Barang_keluarSumAggregateOutputType = {
  id: number | null
  produkId: number | null
  nominal_modal: number | null
  jumlah_barang_keluar: number | null
}

export type Barang_keluarMinAggregateOutputType = {
  id: number | null
  produkId: number | null
  tanggal_keluar: Date | null
  nominal_modal: number | null
  jumlah_barang_keluar: number | null
}

export type Barang_keluarMaxAggregateOutputType = {
  id: number | null
  produkId: number | null
  tanggal_keluar: Date | null
  nominal_modal: number | null
  jumlah_barang_keluar: number | null
}

export type Barang_keluarCountAggregateOutputType = {
  id: number
  produkId: number
  tanggal_keluar: number
  nominal_modal: number
  jumlah_barang_keluar: number
  _all: number
}


export type Barang_keluarAvgAggregateInputType = {
  id?: true
  produkId?: true
  nominal_modal?: true
  jumlah_barang_keluar?: true
}

export type Barang_keluarSumAggregateInputType = {
  id?: true
  produkId?: true
  nominal_modal?: true
  jumlah_barang_keluar?: true
}

export type Barang_keluarMinAggregateInputType = {
  id?: true
  produkId?: true
  tanggal_keluar?: true
  nominal_modal?: true
  jumlah_barang_keluar?: true
}

export type Barang_keluarMaxAggregateInputType = {
  id?: true
  produkId?: true
  tanggal_keluar?: true
  nominal_modal?: true
  jumlah_barang_keluar?: true
}

export type Barang_keluarCountAggregateInputType = {
  id?: true
  produkId?: true
  tanggal_keluar?: true
  nominal_modal?: true
  jumlah_barang_keluar?: true
  _all?: true
}

export type Barang_keluarAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which barang_keluar to aggregate.
   */
  where?: Prisma.barang_keluarWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of barang_keluars to fetch.
   */
  orderBy?: Prisma.barang_keluarOrderByWithRelationInput | Prisma.barang_keluarOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.barang_keluarWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` barang_keluars from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` barang_keluars.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned barang_keluars
  **/
  _count?: true | Barang_keluarCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Barang_keluarAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Barang_keluarSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Barang_keluarMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Barang_keluarMaxAggregateInputType
}

export type GetBarang_keluarAggregateType<T extends Barang_keluarAggregateArgs> = {
      [P in keyof T & keyof AggregateBarang_keluar]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBarang_keluar[P]>
    : Prisma.GetScalarType<T[P], AggregateBarang_keluar[P]>
}




export type barang_keluarGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.barang_keluarWhereInput
  orderBy?: Prisma.barang_keluarOrderByWithAggregationInput | Prisma.barang_keluarOrderByWithAggregationInput[]
  by: Prisma.Barang_keluarScalarFieldEnum[] | Prisma.Barang_keluarScalarFieldEnum
  having?: Prisma.barang_keluarScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Barang_keluarCountAggregateInputType | true
  _avg?: Barang_keluarAvgAggregateInputType
  _sum?: Barang_keluarSumAggregateInputType
  _min?: Barang_keluarMinAggregateInputType
  _max?: Barang_keluarMaxAggregateInputType
}

export type Barang_keluarGroupByOutputType = {
  id: number
  produkId: number
  tanggal_keluar: Date
  nominal_modal: number
  jumlah_barang_keluar: number
  _count: Barang_keluarCountAggregateOutputType | null
  _avg: Barang_keluarAvgAggregateOutputType | null
  _sum: Barang_keluarSumAggregateOutputType | null
  _min: Barang_keluarMinAggregateOutputType | null
  _max: Barang_keluarMaxAggregateOutputType | null
}

type GetBarang_keluarGroupByPayload<T extends barang_keluarGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Barang_keluarGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Barang_keluarGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Barang_keluarGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Barang_keluarGroupByOutputType[P]>
      }
    >
  >



export type barang_keluarWhereInput = {
  AND?: Prisma.barang_keluarWhereInput | Prisma.barang_keluarWhereInput[]
  OR?: Prisma.barang_keluarWhereInput[]
  NOT?: Prisma.barang_keluarWhereInput | Prisma.barang_keluarWhereInput[]
  id?: Prisma.IntFilter<"barang_keluar"> | number
  produkId?: Prisma.IntFilter<"barang_keluar"> | number
  tanggal_keluar?: Prisma.DateTimeFilter<"barang_keluar"> | Date | string
  nominal_modal?: Prisma.IntFilter<"barang_keluar"> | number
  jumlah_barang_keluar?: Prisma.IntFilter<"barang_keluar"> | number
  produk?: Prisma.XOR<Prisma.ProdukScalarRelationFilter, Prisma.produkWhereInput>
}

export type barang_keluarOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  produkId?: Prisma.SortOrder
  tanggal_keluar?: Prisma.SortOrder
  nominal_modal?: Prisma.SortOrder
  jumlah_barang_keluar?: Prisma.SortOrder
  produk?: Prisma.produkOrderByWithRelationInput
}

export type barang_keluarWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.barang_keluarWhereInput | Prisma.barang_keluarWhereInput[]
  OR?: Prisma.barang_keluarWhereInput[]
  NOT?: Prisma.barang_keluarWhereInput | Prisma.barang_keluarWhereInput[]
  produkId?: Prisma.IntFilter<"barang_keluar"> | number
  tanggal_keluar?: Prisma.DateTimeFilter<"barang_keluar"> | Date | string
  nominal_modal?: Prisma.IntFilter<"barang_keluar"> | number
  jumlah_barang_keluar?: Prisma.IntFilter<"barang_keluar"> | number
  produk?: Prisma.XOR<Prisma.ProdukScalarRelationFilter, Prisma.produkWhereInput>
}, "id">

export type barang_keluarOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  produkId?: Prisma.SortOrder
  tanggal_keluar?: Prisma.SortOrder
  nominal_modal?: Prisma.SortOrder
  jumlah_barang_keluar?: Prisma.SortOrder
  _count?: Prisma.barang_keluarCountOrderByAggregateInput
  _avg?: Prisma.barang_keluarAvgOrderByAggregateInput
  _max?: Prisma.barang_keluarMaxOrderByAggregateInput
  _min?: Prisma.barang_keluarMinOrderByAggregateInput
  _sum?: Prisma.barang_keluarSumOrderByAggregateInput
}

export type barang_keluarScalarWhereWithAggregatesInput = {
  AND?: Prisma.barang_keluarScalarWhereWithAggregatesInput | Prisma.barang_keluarScalarWhereWithAggregatesInput[]
  OR?: Prisma.barang_keluarScalarWhereWithAggregatesInput[]
  NOT?: Prisma.barang_keluarScalarWhereWithAggregatesInput | Prisma.barang_keluarScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"barang_keluar"> | number
  produkId?: Prisma.IntWithAggregatesFilter<"barang_keluar"> | number
  tanggal_keluar?: Prisma.DateTimeWithAggregatesFilter<"barang_keluar"> | Date | string
  nominal_modal?: Prisma.IntWithAggregatesFilter<"barang_keluar"> | number
  jumlah_barang_keluar?: Prisma.IntWithAggregatesFilter<"barang_keluar"> | number
}

export type barang_keluarCreateInput = {
  tanggal_keluar?: Date | string
  nominal_modal: number
  jumlah_barang_keluar: number
  produk: Prisma.produkCreateNestedOneWithoutOutboundInput
}

export type barang_keluarUncheckedCreateInput = {
  id?: number
  produkId: number
  tanggal_keluar?: Date | string
  nominal_modal: number
  jumlah_barang_keluar: number
}

export type barang_keluarUpdateInput = {
  tanggal_keluar?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  nominal_modal?: Prisma.IntFieldUpdateOperationsInput | number
  jumlah_barang_keluar?: Prisma.IntFieldUpdateOperationsInput | number
  produk?: Prisma.produkUpdateOneRequiredWithoutOutboundNestedInput
}

export type barang_keluarUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  produkId?: Prisma.IntFieldUpdateOperationsInput | number
  tanggal_keluar?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  nominal_modal?: Prisma.IntFieldUpdateOperationsInput | number
  jumlah_barang_keluar?: Prisma.IntFieldUpdateOperationsInput | number
}

export type barang_keluarCreateManyInput = {
  id?: number
  produkId: number
  tanggal_keluar?: Date | string
  nominal_modal: number
  jumlah_barang_keluar: number
}

export type barang_keluarUpdateManyMutationInput = {
  tanggal_keluar?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  nominal_modal?: Prisma.IntFieldUpdateOperationsInput | number
  jumlah_barang_keluar?: Prisma.IntFieldUpdateOperationsInput | number
}

export type barang_keluarUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  produkId?: Prisma.IntFieldUpdateOperationsInput | number
  tanggal_keluar?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  nominal_modal?: Prisma.IntFieldUpdateOperationsInput | number
  jumlah_barang_keluar?: Prisma.IntFieldUpdateOperationsInput | number
}

export type Barang_keluarListRelationFilter = {
  every?: Prisma.barang_keluarWhereInput
  some?: Prisma.barang_keluarWhereInput
  none?: Prisma.barang_keluarWhereInput
}

export type barang_keluarOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type barang_keluarCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  produkId?: Prisma.SortOrder
  tanggal_keluar?: Prisma.SortOrder
  nominal_modal?: Prisma.SortOrder
  jumlah_barang_keluar?: Prisma.SortOrder
}

export type barang_keluarAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  produkId?: Prisma.SortOrder
  nominal_modal?: Prisma.SortOrder
  jumlah_barang_keluar?: Prisma.SortOrder
}

export type barang_keluarMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  produkId?: Prisma.SortOrder
  tanggal_keluar?: Prisma.SortOrder
  nominal_modal?: Prisma.SortOrder
  jumlah_barang_keluar?: Prisma.SortOrder
}

export type barang_keluarMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  produkId?: Prisma.SortOrder
  tanggal_keluar?: Prisma.SortOrder
  nominal_modal?: Prisma.SortOrder
  jumlah_barang_keluar?: Prisma.SortOrder
}

export type barang_keluarSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  produkId?: Prisma.SortOrder
  nominal_modal?: Prisma.SortOrder
  jumlah_barang_keluar?: Prisma.SortOrder
}

export type barang_keluarCreateNestedManyWithoutProdukInput = {
  create?: Prisma.XOR<Prisma.barang_keluarCreateWithoutProdukInput, Prisma.barang_keluarUncheckedCreateWithoutProdukInput> | Prisma.barang_keluarCreateWithoutProdukInput[] | Prisma.barang_keluarUncheckedCreateWithoutProdukInput[]
  connectOrCreate?: Prisma.barang_keluarCreateOrConnectWithoutProdukInput | Prisma.barang_keluarCreateOrConnectWithoutProdukInput[]
  createMany?: Prisma.barang_keluarCreateManyProdukInputEnvelope
  connect?: Prisma.barang_keluarWhereUniqueInput | Prisma.barang_keluarWhereUniqueInput[]
}

export type barang_keluarUncheckedCreateNestedManyWithoutProdukInput = {
  create?: Prisma.XOR<Prisma.barang_keluarCreateWithoutProdukInput, Prisma.barang_keluarUncheckedCreateWithoutProdukInput> | Prisma.barang_keluarCreateWithoutProdukInput[] | Prisma.barang_keluarUncheckedCreateWithoutProdukInput[]
  connectOrCreate?: Prisma.barang_keluarCreateOrConnectWithoutProdukInput | Prisma.barang_keluarCreateOrConnectWithoutProdukInput[]
  createMany?: Prisma.barang_keluarCreateManyProdukInputEnvelope
  connect?: Prisma.barang_keluarWhereUniqueInput | Prisma.barang_keluarWhereUniqueInput[]
}

export type barang_keluarUpdateManyWithoutProdukNestedInput = {
  create?: Prisma.XOR<Prisma.barang_keluarCreateWithoutProdukInput, Prisma.barang_keluarUncheckedCreateWithoutProdukInput> | Prisma.barang_keluarCreateWithoutProdukInput[] | Prisma.barang_keluarUncheckedCreateWithoutProdukInput[]
  connectOrCreate?: Prisma.barang_keluarCreateOrConnectWithoutProdukInput | Prisma.barang_keluarCreateOrConnectWithoutProdukInput[]
  upsert?: Prisma.barang_keluarUpsertWithWhereUniqueWithoutProdukInput | Prisma.barang_keluarUpsertWithWhereUniqueWithoutProdukInput[]
  createMany?: Prisma.barang_keluarCreateManyProdukInputEnvelope
  set?: Prisma.barang_keluarWhereUniqueInput | Prisma.barang_keluarWhereUniqueInput[]
  disconnect?: Prisma.barang_keluarWhereUniqueInput | Prisma.barang_keluarWhereUniqueInput[]
  delete?: Prisma.barang_keluarWhereUniqueInput | Prisma.barang_keluarWhereUniqueInput[]
  connect?: Prisma.barang_keluarWhereUniqueInput | Prisma.barang_keluarWhereUniqueInput[]
  update?: Prisma.barang_keluarUpdateWithWhereUniqueWithoutProdukInput | Prisma.barang_keluarUpdateWithWhereUniqueWithoutProdukInput[]
  updateMany?: Prisma.barang_keluarUpdateManyWithWhereWithoutProdukInput | Prisma.barang_keluarUpdateManyWithWhereWithoutProdukInput[]
  deleteMany?: Prisma.barang_keluarScalarWhereInput | Prisma.barang_keluarScalarWhereInput[]
}

export type barang_keluarUncheckedUpdateManyWithoutProdukNestedInput = {
  create?: Prisma.XOR<Prisma.barang_keluarCreateWithoutProdukInput, Prisma.barang_keluarUncheckedCreateWithoutProdukInput> | Prisma.barang_keluarCreateWithoutProdukInput[] | Prisma.barang_keluarUncheckedCreateWithoutProdukInput[]
  connectOrCreate?: Prisma.barang_keluarCreateOrConnectWithoutProdukInput | Prisma.barang_keluarCreateOrConnectWithoutProdukInput[]
  upsert?: Prisma.barang_keluarUpsertWithWhereUniqueWithoutProdukInput | Prisma.barang_keluarUpsertWithWhereUniqueWithoutProdukInput[]
  createMany?: Prisma.barang_keluarCreateManyProdukInputEnvelope
  set?: Prisma.barang_keluarWhereUniqueInput | Prisma.barang_keluarWhereUniqueInput[]
  disconnect?: Prisma.barang_keluarWhereUniqueInput | Prisma.barang_keluarWhereUniqueInput[]
  delete?: Prisma.barang_keluarWhereUniqueInput | Prisma.barang_keluarWhereUniqueInput[]
  connect?: Prisma.barang_keluarWhereUniqueInput | Prisma.barang_keluarWhereUniqueInput[]
  update?: Prisma.barang_keluarUpdateWithWhereUniqueWithoutProdukInput | Prisma.barang_keluarUpdateWithWhereUniqueWithoutProdukInput[]
  updateMany?: Prisma.barang_keluarUpdateManyWithWhereWithoutProdukInput | Prisma.barang_keluarUpdateManyWithWhereWithoutProdukInput[]
  deleteMany?: Prisma.barang_keluarScalarWhereInput | Prisma.barang_keluarScalarWhereInput[]
}

export type barang_keluarCreateWithoutProdukInput = {
  tanggal_keluar?: Date | string
  nominal_modal: number
  jumlah_barang_keluar: number
}

export type barang_keluarUncheckedCreateWithoutProdukInput = {
  id?: number
  tanggal_keluar?: Date | string
  nominal_modal: number
  jumlah_barang_keluar: number
}

export type barang_keluarCreateOrConnectWithoutProdukInput = {
  where: Prisma.barang_keluarWhereUniqueInput
  create: Prisma.XOR<Prisma.barang_keluarCreateWithoutProdukInput, Prisma.barang_keluarUncheckedCreateWithoutProdukInput>
}

export type barang_keluarCreateManyProdukInputEnvelope = {
  data: Prisma.barang_keluarCreateManyProdukInput | Prisma.barang_keluarCreateManyProdukInput[]
  skipDuplicates?: boolean
}

export type barang_keluarUpsertWithWhereUniqueWithoutProdukInput = {
  where: Prisma.barang_keluarWhereUniqueInput
  update: Prisma.XOR<Prisma.barang_keluarUpdateWithoutProdukInput, Prisma.barang_keluarUncheckedUpdateWithoutProdukInput>
  create: Prisma.XOR<Prisma.barang_keluarCreateWithoutProdukInput, Prisma.barang_keluarUncheckedCreateWithoutProdukInput>
}

export type barang_keluarUpdateWithWhereUniqueWithoutProdukInput = {
  where: Prisma.barang_keluarWhereUniqueInput
  data: Prisma.XOR<Prisma.barang_keluarUpdateWithoutProdukInput, Prisma.barang_keluarUncheckedUpdateWithoutProdukInput>
}

export type barang_keluarUpdateManyWithWhereWithoutProdukInput = {
  where: Prisma.barang_keluarScalarWhereInput
  data: Prisma.XOR<Prisma.barang_keluarUpdateManyMutationInput, Prisma.barang_keluarUncheckedUpdateManyWithoutProdukInput>
}

export type barang_keluarScalarWhereInput = {
  AND?: Prisma.barang_keluarScalarWhereInput | Prisma.barang_keluarScalarWhereInput[]
  OR?: Prisma.barang_keluarScalarWhereInput[]
  NOT?: Prisma.barang_keluarScalarWhereInput | Prisma.barang_keluarScalarWhereInput[]
  id?: Prisma.IntFilter<"barang_keluar"> | number
  produkId?: Prisma.IntFilter<"barang_keluar"> | number
  tanggal_keluar?: Prisma.DateTimeFilter<"barang_keluar"> | Date | string
  nominal_modal?: Prisma.IntFilter<"barang_keluar"> | number
  jumlah_barang_keluar?: Prisma.IntFilter<"barang_keluar"> | number
}

export type barang_keluarCreateManyProdukInput = {
  id?: number
  tanggal_keluar?: Date | string
  nominal_modal: number
  jumlah_barang_keluar: number
}

export type barang_keluarUpdateWithoutProdukInput = {
  tanggal_keluar?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  nominal_modal?: Prisma.IntFieldUpdateOperationsInput | number
  jumlah_barang_keluar?: Prisma.IntFieldUpdateOperationsInput | number
}

export type barang_keluarUncheckedUpdateWithoutProdukInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  tanggal_keluar?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  nominal_modal?: Prisma.IntFieldUpdateOperationsInput | number
  jumlah_barang_keluar?: Prisma.IntFieldUpdateOperationsInput | number
}

export type barang_keluarUncheckedUpdateManyWithoutProdukInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  tanggal_keluar?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  nominal_modal?: Prisma.IntFieldUpdateOperationsInput | number
  jumlah_barang_keluar?: Prisma.IntFieldUpdateOperationsInput | number
}



export type barang_keluarSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  produkId?: boolean
  tanggal_keluar?: boolean
  nominal_modal?: boolean
  jumlah_barang_keluar?: boolean
  produk?: boolean | Prisma.produkDefaultArgs<ExtArgs>
}, ExtArgs["result"]["barang_keluar"]>

export type barang_keluarSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  produkId?: boolean
  tanggal_keluar?: boolean
  nominal_modal?: boolean
  jumlah_barang_keluar?: boolean
  produk?: boolean | Prisma.produkDefaultArgs<ExtArgs>
}, ExtArgs["result"]["barang_keluar"]>

export type barang_keluarSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  produkId?: boolean
  tanggal_keluar?: boolean
  nominal_modal?: boolean
  jumlah_barang_keluar?: boolean
  produk?: boolean | Prisma.produkDefaultArgs<ExtArgs>
}, ExtArgs["result"]["barang_keluar"]>

export type barang_keluarSelectScalar = {
  id?: boolean
  produkId?: boolean
  tanggal_keluar?: boolean
  nominal_modal?: boolean
  jumlah_barang_keluar?: boolean
}

export type barang_keluarOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "produkId" | "tanggal_keluar" | "nominal_modal" | "jumlah_barang_keluar", ExtArgs["result"]["barang_keluar"]>
export type barang_keluarInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  produk?: boolean | Prisma.produkDefaultArgs<ExtArgs>
}
export type barang_keluarIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  produk?: boolean | Prisma.produkDefaultArgs<ExtArgs>
}
export type barang_keluarIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  produk?: boolean | Prisma.produkDefaultArgs<ExtArgs>
}

export type $barang_keluarPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "barang_keluar"
  objects: {
    produk: Prisma.$produkPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    produkId: number
    tanggal_keluar: Date
    nominal_modal: number
    jumlah_barang_keluar: number
  }, ExtArgs["result"]["barang_keluar"]>
  composites: {}
}

export type barang_keluarGetPayload<S extends boolean | null | undefined | barang_keluarDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$barang_keluarPayload, S>

export type barang_keluarCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<barang_keluarFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Barang_keluarCountAggregateInputType | true
  }

export interface barang_keluarDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['barang_keluar'], meta: { name: 'barang_keluar' } }
  /**
   * Find zero or one Barang_keluar that matches the filter.
   * @param {barang_keluarFindUniqueArgs} args - Arguments to find a Barang_keluar
   * @example
   * // Get one Barang_keluar
   * const barang_keluar = await prisma.barang_keluar.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends barang_keluarFindUniqueArgs>(args: Prisma.SelectSubset<T, barang_keluarFindUniqueArgs<ExtArgs>>): Prisma.Prisma__barang_keluarClient<runtime.Types.Result.GetResult<Prisma.$barang_keluarPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Barang_keluar that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {barang_keluarFindUniqueOrThrowArgs} args - Arguments to find a Barang_keluar
   * @example
   * // Get one Barang_keluar
   * const barang_keluar = await prisma.barang_keluar.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends barang_keluarFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, barang_keluarFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__barang_keluarClient<runtime.Types.Result.GetResult<Prisma.$barang_keluarPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Barang_keluar that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {barang_keluarFindFirstArgs} args - Arguments to find a Barang_keluar
   * @example
   * // Get one Barang_keluar
   * const barang_keluar = await prisma.barang_keluar.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends barang_keluarFindFirstArgs>(args?: Prisma.SelectSubset<T, barang_keluarFindFirstArgs<ExtArgs>>): Prisma.Prisma__barang_keluarClient<runtime.Types.Result.GetResult<Prisma.$barang_keluarPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Barang_keluar that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {barang_keluarFindFirstOrThrowArgs} args - Arguments to find a Barang_keluar
   * @example
   * // Get one Barang_keluar
   * const barang_keluar = await prisma.barang_keluar.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends barang_keluarFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, barang_keluarFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__barang_keluarClient<runtime.Types.Result.GetResult<Prisma.$barang_keluarPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Barang_keluars that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {barang_keluarFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Barang_keluars
   * const barang_keluars = await prisma.barang_keluar.findMany()
   * 
   * // Get first 10 Barang_keluars
   * const barang_keluars = await prisma.barang_keluar.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const barang_keluarWithIdOnly = await prisma.barang_keluar.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends barang_keluarFindManyArgs>(args?: Prisma.SelectSubset<T, barang_keluarFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$barang_keluarPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Barang_keluar.
   * @param {barang_keluarCreateArgs} args - Arguments to create a Barang_keluar.
   * @example
   * // Create one Barang_keluar
   * const Barang_keluar = await prisma.barang_keluar.create({
   *   data: {
   *     // ... data to create a Barang_keluar
   *   }
   * })
   * 
   */
  create<T extends barang_keluarCreateArgs>(args: Prisma.SelectSubset<T, barang_keluarCreateArgs<ExtArgs>>): Prisma.Prisma__barang_keluarClient<runtime.Types.Result.GetResult<Prisma.$barang_keluarPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Barang_keluars.
   * @param {barang_keluarCreateManyArgs} args - Arguments to create many Barang_keluars.
   * @example
   * // Create many Barang_keluars
   * const barang_keluar = await prisma.barang_keluar.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends barang_keluarCreateManyArgs>(args?: Prisma.SelectSubset<T, barang_keluarCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Barang_keluars and returns the data saved in the database.
   * @param {barang_keluarCreateManyAndReturnArgs} args - Arguments to create many Barang_keluars.
   * @example
   * // Create many Barang_keluars
   * const barang_keluar = await prisma.barang_keluar.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Barang_keluars and only return the `id`
   * const barang_keluarWithIdOnly = await prisma.barang_keluar.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends barang_keluarCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, barang_keluarCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$barang_keluarPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Barang_keluar.
   * @param {barang_keluarDeleteArgs} args - Arguments to delete one Barang_keluar.
   * @example
   * // Delete one Barang_keluar
   * const Barang_keluar = await prisma.barang_keluar.delete({
   *   where: {
   *     // ... filter to delete one Barang_keluar
   *   }
   * })
   * 
   */
  delete<T extends barang_keluarDeleteArgs>(args: Prisma.SelectSubset<T, barang_keluarDeleteArgs<ExtArgs>>): Prisma.Prisma__barang_keluarClient<runtime.Types.Result.GetResult<Prisma.$barang_keluarPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Barang_keluar.
   * @param {barang_keluarUpdateArgs} args - Arguments to update one Barang_keluar.
   * @example
   * // Update one Barang_keluar
   * const barang_keluar = await prisma.barang_keluar.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends barang_keluarUpdateArgs>(args: Prisma.SelectSubset<T, barang_keluarUpdateArgs<ExtArgs>>): Prisma.Prisma__barang_keluarClient<runtime.Types.Result.GetResult<Prisma.$barang_keluarPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Barang_keluars.
   * @param {barang_keluarDeleteManyArgs} args - Arguments to filter Barang_keluars to delete.
   * @example
   * // Delete a few Barang_keluars
   * const { count } = await prisma.barang_keluar.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends barang_keluarDeleteManyArgs>(args?: Prisma.SelectSubset<T, barang_keluarDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Barang_keluars.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {barang_keluarUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Barang_keluars
   * const barang_keluar = await prisma.barang_keluar.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends barang_keluarUpdateManyArgs>(args: Prisma.SelectSubset<T, barang_keluarUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Barang_keluars and returns the data updated in the database.
   * @param {barang_keluarUpdateManyAndReturnArgs} args - Arguments to update many Barang_keluars.
   * @example
   * // Update many Barang_keluars
   * const barang_keluar = await prisma.barang_keluar.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Barang_keluars and only return the `id`
   * const barang_keluarWithIdOnly = await prisma.barang_keluar.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends barang_keluarUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, barang_keluarUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$barang_keluarPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Barang_keluar.
   * @param {barang_keluarUpsertArgs} args - Arguments to update or create a Barang_keluar.
   * @example
   * // Update or create a Barang_keluar
   * const barang_keluar = await prisma.barang_keluar.upsert({
   *   create: {
   *     // ... data to create a Barang_keluar
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Barang_keluar we want to update
   *   }
   * })
   */
  upsert<T extends barang_keluarUpsertArgs>(args: Prisma.SelectSubset<T, barang_keluarUpsertArgs<ExtArgs>>): Prisma.Prisma__barang_keluarClient<runtime.Types.Result.GetResult<Prisma.$barang_keluarPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Barang_keluars.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {barang_keluarCountArgs} args - Arguments to filter Barang_keluars to count.
   * @example
   * // Count the number of Barang_keluars
   * const count = await prisma.barang_keluar.count({
   *   where: {
   *     // ... the filter for the Barang_keluars we want to count
   *   }
   * })
  **/
  count<T extends barang_keluarCountArgs>(
    args?: Prisma.Subset<T, barang_keluarCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Barang_keluarCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Barang_keluar.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Barang_keluarAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Barang_keluarAggregateArgs>(args: Prisma.Subset<T, Barang_keluarAggregateArgs>): Prisma.PrismaPromise<GetBarang_keluarAggregateType<T>>

  /**
   * Group by Barang_keluar.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {barang_keluarGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends barang_keluarGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: barang_keluarGroupByArgs['orderBy'] }
      : { orderBy?: barang_keluarGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, barang_keluarGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetBarang_keluarGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the barang_keluar model
 */
readonly fields: barang_keluarFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for barang_keluar.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__barang_keluarClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  produk<T extends Prisma.produkDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.produkDefaultArgs<ExtArgs>>): Prisma.Prisma__produkClient<runtime.Types.Result.GetResult<Prisma.$produkPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the barang_keluar model
 */
export interface barang_keluarFieldRefs {
  readonly id: Prisma.FieldRef<"barang_keluar", 'Int'>
  readonly produkId: Prisma.FieldRef<"barang_keluar", 'Int'>
  readonly tanggal_keluar: Prisma.FieldRef<"barang_keluar", 'DateTime'>
  readonly nominal_modal: Prisma.FieldRef<"barang_keluar", 'Int'>
  readonly jumlah_barang_keluar: Prisma.FieldRef<"barang_keluar", 'Int'>
}
    

// Custom InputTypes
/**
 * barang_keluar findUnique
 */
export type barang_keluarFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the barang_keluar
   */
  select?: Prisma.barang_keluarSelect<ExtArgs> | null
  /**
   * Omit specific fields from the barang_keluar
   */
  omit?: Prisma.barang_keluarOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.barang_keluarInclude<ExtArgs> | null
  /**
   * Filter, which barang_keluar to fetch.
   */
  where: Prisma.barang_keluarWhereUniqueInput
}

/**
 * barang_keluar findUniqueOrThrow
 */
export type barang_keluarFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the barang_keluar
   */
  select?: Prisma.barang_keluarSelect<ExtArgs> | null
  /**
   * Omit specific fields from the barang_keluar
   */
  omit?: Prisma.barang_keluarOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.barang_keluarInclude<ExtArgs> | null
  /**
   * Filter, which barang_keluar to fetch.
   */
  where: Prisma.barang_keluarWhereUniqueInput
}

/**
 * barang_keluar findFirst
 */
export type barang_keluarFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the barang_keluar
   */
  select?: Prisma.barang_keluarSelect<ExtArgs> | null
  /**
   * Omit specific fields from the barang_keluar
   */
  omit?: Prisma.barang_keluarOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.barang_keluarInclude<ExtArgs> | null
  /**
   * Filter, which barang_keluar to fetch.
   */
  where?: Prisma.barang_keluarWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of barang_keluars to fetch.
   */
  orderBy?: Prisma.barang_keluarOrderByWithRelationInput | Prisma.barang_keluarOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for barang_keluars.
   */
  cursor?: Prisma.barang_keluarWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` barang_keluars from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` barang_keluars.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of barang_keluars.
   */
  distinct?: Prisma.Barang_keluarScalarFieldEnum | Prisma.Barang_keluarScalarFieldEnum[]
}

/**
 * barang_keluar findFirstOrThrow
 */
export type barang_keluarFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the barang_keluar
   */
  select?: Prisma.barang_keluarSelect<ExtArgs> | null
  /**
   * Omit specific fields from the barang_keluar
   */
  omit?: Prisma.barang_keluarOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.barang_keluarInclude<ExtArgs> | null
  /**
   * Filter, which barang_keluar to fetch.
   */
  where?: Prisma.barang_keluarWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of barang_keluars to fetch.
   */
  orderBy?: Prisma.barang_keluarOrderByWithRelationInput | Prisma.barang_keluarOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for barang_keluars.
   */
  cursor?: Prisma.barang_keluarWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` barang_keluars from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` barang_keluars.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of barang_keluars.
   */
  distinct?: Prisma.Barang_keluarScalarFieldEnum | Prisma.Barang_keluarScalarFieldEnum[]
}

/**
 * barang_keluar findMany
 */
export type barang_keluarFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the barang_keluar
   */
  select?: Prisma.barang_keluarSelect<ExtArgs> | null
  /**
   * Omit specific fields from the barang_keluar
   */
  omit?: Prisma.barang_keluarOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.barang_keluarInclude<ExtArgs> | null
  /**
   * Filter, which barang_keluars to fetch.
   */
  where?: Prisma.barang_keluarWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of barang_keluars to fetch.
   */
  orderBy?: Prisma.barang_keluarOrderByWithRelationInput | Prisma.barang_keluarOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing barang_keluars.
   */
  cursor?: Prisma.barang_keluarWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` barang_keluars from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` barang_keluars.
   */
  skip?: number
  distinct?: Prisma.Barang_keluarScalarFieldEnum | Prisma.Barang_keluarScalarFieldEnum[]
}

/**
 * barang_keluar create
 */
export type barang_keluarCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the barang_keluar
   */
  select?: Prisma.barang_keluarSelect<ExtArgs> | null
  /**
   * Omit specific fields from the barang_keluar
   */
  omit?: Prisma.barang_keluarOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.barang_keluarInclude<ExtArgs> | null
  /**
   * The data needed to create a barang_keluar.
   */
  data: Prisma.XOR<Prisma.barang_keluarCreateInput, Prisma.barang_keluarUncheckedCreateInput>
}

/**
 * barang_keluar createMany
 */
export type barang_keluarCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many barang_keluars.
   */
  data: Prisma.barang_keluarCreateManyInput | Prisma.barang_keluarCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * barang_keluar createManyAndReturn
 */
export type barang_keluarCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the barang_keluar
   */
  select?: Prisma.barang_keluarSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the barang_keluar
   */
  omit?: Prisma.barang_keluarOmit<ExtArgs> | null
  /**
   * The data used to create many barang_keluars.
   */
  data: Prisma.barang_keluarCreateManyInput | Prisma.barang_keluarCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.barang_keluarIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * barang_keluar update
 */
export type barang_keluarUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the barang_keluar
   */
  select?: Prisma.barang_keluarSelect<ExtArgs> | null
  /**
   * Omit specific fields from the barang_keluar
   */
  omit?: Prisma.barang_keluarOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.barang_keluarInclude<ExtArgs> | null
  /**
   * The data needed to update a barang_keluar.
   */
  data: Prisma.XOR<Prisma.barang_keluarUpdateInput, Prisma.barang_keluarUncheckedUpdateInput>
  /**
   * Choose, which barang_keluar to update.
   */
  where: Prisma.barang_keluarWhereUniqueInput
}

/**
 * barang_keluar updateMany
 */
export type barang_keluarUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update barang_keluars.
   */
  data: Prisma.XOR<Prisma.barang_keluarUpdateManyMutationInput, Prisma.barang_keluarUncheckedUpdateManyInput>
  /**
   * Filter which barang_keluars to update
   */
  where?: Prisma.barang_keluarWhereInput
  /**
   * Limit how many barang_keluars to update.
   */
  limit?: number
}

/**
 * barang_keluar updateManyAndReturn
 */
export type barang_keluarUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the barang_keluar
   */
  select?: Prisma.barang_keluarSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the barang_keluar
   */
  omit?: Prisma.barang_keluarOmit<ExtArgs> | null
  /**
   * The data used to update barang_keluars.
   */
  data: Prisma.XOR<Prisma.barang_keluarUpdateManyMutationInput, Prisma.barang_keluarUncheckedUpdateManyInput>
  /**
   * Filter which barang_keluars to update
   */
  where?: Prisma.barang_keluarWhereInput
  /**
   * Limit how many barang_keluars to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.barang_keluarIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * barang_keluar upsert
 */
export type barang_keluarUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the barang_keluar
   */
  select?: Prisma.barang_keluarSelect<ExtArgs> | null
  /**
   * Omit specific fields from the barang_keluar
   */
  omit?: Prisma.barang_keluarOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.barang_keluarInclude<ExtArgs> | null
  /**
   * The filter to search for the barang_keluar to update in case it exists.
   */
  where: Prisma.barang_keluarWhereUniqueInput
  /**
   * In case the barang_keluar found by the `where` argument doesn't exist, create a new barang_keluar with this data.
   */
  create: Prisma.XOR<Prisma.barang_keluarCreateInput, Prisma.barang_keluarUncheckedCreateInput>
  /**
   * In case the barang_keluar was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.barang_keluarUpdateInput, Prisma.barang_keluarUncheckedUpdateInput>
}

/**
 * barang_keluar delete
 */
export type barang_keluarDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the barang_keluar
   */
  select?: Prisma.barang_keluarSelect<ExtArgs> | null
  /**
   * Omit specific fields from the barang_keluar
   */
  omit?: Prisma.barang_keluarOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.barang_keluarInclude<ExtArgs> | null
  /**
   * Filter which barang_keluar to delete.
   */
  where: Prisma.barang_keluarWhereUniqueInput
}

/**
 * barang_keluar deleteMany
 */
export type barang_keluarDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which barang_keluars to delete
   */
  where?: Prisma.barang_keluarWhereInput
  /**
   * Limit how many barang_keluars to delete.
   */
  limit?: number
}

/**
 * barang_keluar without action
 */
export type barang_keluarDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the barang_keluar
   */
  select?: Prisma.barang_keluarSelect<ExtArgs> | null
  /**
   * Omit specific fields from the barang_keluar
   */
  omit?: Prisma.barang_keluarOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.barang_keluarInclude<ExtArgs> | null
}
