
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `barang_masuk` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model barang_masuk
 * 
 */
export type barang_masukModel = runtime.Types.Result.DefaultSelection<Prisma.$barang_masukPayload>

export type AggregateBarang_masuk = {
  _count: Barang_masukCountAggregateOutputType | null
  _avg: Barang_masukAvgAggregateOutputType | null
  _sum: Barang_masukSumAggregateOutputType | null
  _min: Barang_masukMinAggregateOutputType | null
  _max: Barang_masukMaxAggregateOutputType | null
}

export type Barang_masukAvgAggregateOutputType = {
  id: number | null
  produkId: number | null
  nominal_modal: number | null
  jumlah_barang_masuk: number | null
}

export type Barang_masukSumAggregateOutputType = {
  id: number | null
  produkId: number | null
  nominal_modal: number | null
  jumlah_barang_masuk: number | null
}

export type Barang_masukMinAggregateOutputType = {
  id: number | null
  produkId: number | null
  tanggal_masuk: Date | null
  nominal_modal: number | null
  jumlah_barang_masuk: number | null
}

export type Barang_masukMaxAggregateOutputType = {
  id: number | null
  produkId: number | null
  tanggal_masuk: Date | null
  nominal_modal: number | null
  jumlah_barang_masuk: number | null
}

export type Barang_masukCountAggregateOutputType = {
  id: number
  produkId: number
  tanggal_masuk: number
  nominal_modal: number
  jumlah_barang_masuk: number
  _all: number
}


export type Barang_masukAvgAggregateInputType = {
  id?: true
  produkId?: true
  nominal_modal?: true
  jumlah_barang_masuk?: true
}

export type Barang_masukSumAggregateInputType = {
  id?: true
  produkId?: true
  nominal_modal?: true
  jumlah_barang_masuk?: true
}

export type Barang_masukMinAggregateInputType = {
  id?: true
  produkId?: true
  tanggal_masuk?: true
  nominal_modal?: true
  jumlah_barang_masuk?: true
}

export type Barang_masukMaxAggregateInputType = {
  id?: true
  produkId?: true
  tanggal_masuk?: true
  nominal_modal?: true
  jumlah_barang_masuk?: true
}

export type Barang_masukCountAggregateInputType = {
  id?: true
  produkId?: true
  tanggal_masuk?: true
  nominal_modal?: true
  jumlah_barang_masuk?: true
  _all?: true
}

export type Barang_masukAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which barang_masuk to aggregate.
   */
  where?: Prisma.barang_masukWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of barang_masuks to fetch.
   */
  orderBy?: Prisma.barang_masukOrderByWithRelationInput | Prisma.barang_masukOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.barang_masukWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` barang_masuks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` barang_masuks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned barang_masuks
  **/
  _count?: true | Barang_masukCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Barang_masukAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Barang_masukSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Barang_masukMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Barang_masukMaxAggregateInputType
}

export type GetBarang_masukAggregateType<T extends Barang_masukAggregateArgs> = {
      [P in keyof T & keyof AggregateBarang_masuk]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBarang_masuk[P]>
    : Prisma.GetScalarType<T[P], AggregateBarang_masuk[P]>
}




export type barang_masukGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.barang_masukWhereInput
  orderBy?: Prisma.barang_masukOrderByWithAggregationInput | Prisma.barang_masukOrderByWithAggregationInput[]
  by: Prisma.Barang_masukScalarFieldEnum[] | Prisma.Barang_masukScalarFieldEnum
  having?: Prisma.barang_masukScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Barang_masukCountAggregateInputType | true
  _avg?: Barang_masukAvgAggregateInputType
  _sum?: Barang_masukSumAggregateInputType
  _min?: Barang_masukMinAggregateInputType
  _max?: Barang_masukMaxAggregateInputType
}

export type Barang_masukGroupByOutputType = {
  id: number
  produkId: number
  tanggal_masuk: Date
  nominal_modal: number
  jumlah_barang_masuk: number
  _count: Barang_masukCountAggregateOutputType | null
  _avg: Barang_masukAvgAggregateOutputType | null
  _sum: Barang_masukSumAggregateOutputType | null
  _min: Barang_masukMinAggregateOutputType | null
  _max: Barang_masukMaxAggregateOutputType | null
}

type GetBarang_masukGroupByPayload<T extends barang_masukGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Barang_masukGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Barang_masukGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Barang_masukGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Barang_masukGroupByOutputType[P]>
      }
    >
  >



export type barang_masukWhereInput = {
  AND?: Prisma.barang_masukWhereInput | Prisma.barang_masukWhereInput[]
  OR?: Prisma.barang_masukWhereInput[]
  NOT?: Prisma.barang_masukWhereInput | Prisma.barang_masukWhereInput[]
  id?: Prisma.IntFilter<"barang_masuk"> | number
  produkId?: Prisma.IntFilter<"barang_masuk"> | number
  tanggal_masuk?: Prisma.DateTimeFilter<"barang_masuk"> | Date | string
  nominal_modal?: Prisma.IntFilter<"barang_masuk"> | number
  jumlah_barang_masuk?: Prisma.IntFilter<"barang_masuk"> | number
  produk?: Prisma.XOR<Prisma.ProdukScalarRelationFilter, Prisma.produkWhereInput>
}

export type barang_masukOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  produkId?: Prisma.SortOrder
  tanggal_masuk?: Prisma.SortOrder
  nominal_modal?: Prisma.SortOrder
  jumlah_barang_masuk?: Prisma.SortOrder
  produk?: Prisma.produkOrderByWithRelationInput
}

export type barang_masukWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.barang_masukWhereInput | Prisma.barang_masukWhereInput[]
  OR?: Prisma.barang_masukWhereInput[]
  NOT?: Prisma.barang_masukWhereInput | Prisma.barang_masukWhereInput[]
  produkId?: Prisma.IntFilter<"barang_masuk"> | number
  tanggal_masuk?: Prisma.DateTimeFilter<"barang_masuk"> | Date | string
  nominal_modal?: Prisma.IntFilter<"barang_masuk"> | number
  jumlah_barang_masuk?: Prisma.IntFilter<"barang_masuk"> | number
  produk?: Prisma.XOR<Prisma.ProdukScalarRelationFilter, Prisma.produkWhereInput>
}, "id">

export type barang_masukOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  produkId?: Prisma.SortOrder
  tanggal_masuk?: Prisma.SortOrder
  nominal_modal?: Prisma.SortOrder
  jumlah_barang_masuk?: Prisma.SortOrder
  _count?: Prisma.barang_masukCountOrderByAggregateInput
  _avg?: Prisma.barang_masukAvgOrderByAggregateInput
  _max?: Prisma.barang_masukMaxOrderByAggregateInput
  _min?: Prisma.barang_masukMinOrderByAggregateInput
  _sum?: Prisma.barang_masukSumOrderByAggregateInput
}

export type barang_masukScalarWhereWithAggregatesInput = {
  AND?: Prisma.barang_masukScalarWhereWithAggregatesInput | Prisma.barang_masukScalarWhereWithAggregatesInput[]
  OR?: Prisma.barang_masukScalarWhereWithAggregatesInput[]
  NOT?: Prisma.barang_masukScalarWhereWithAggregatesInput | Prisma.barang_masukScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"barang_masuk"> | number
  produkId?: Prisma.IntWithAggregatesFilter<"barang_masuk"> | number
  tanggal_masuk?: Prisma.DateTimeWithAggregatesFilter<"barang_masuk"> | Date | string
  nominal_modal?: Prisma.IntWithAggregatesFilter<"barang_masuk"> | number
  jumlah_barang_masuk?: Prisma.IntWithAggregatesFilter<"barang_masuk"> | number
}

export type barang_masukCreateInput = {
  tanggal_masuk?: Date | string
  nominal_modal: number
  jumlah_barang_masuk: number
  produk: Prisma.produkCreateNestedOneWithoutInboundInput
}

export type barang_masukUncheckedCreateInput = {
  id?: number
  produkId: number
  tanggal_masuk?: Date | string
  nominal_modal: number
  jumlah_barang_masuk: number
}

export type barang_masukUpdateInput = {
  tanggal_masuk?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  nominal_modal?: Prisma.IntFieldUpdateOperationsInput | number
  jumlah_barang_masuk?: Prisma.IntFieldUpdateOperationsInput | number
  produk?: Prisma.produkUpdateOneRequiredWithoutInboundNestedInput
}

export type barang_masukUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  produkId?: Prisma.IntFieldUpdateOperationsInput | number
  tanggal_masuk?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  nominal_modal?: Prisma.IntFieldUpdateOperationsInput | number
  jumlah_barang_masuk?: Prisma.IntFieldUpdateOperationsInput | number
}

export type barang_masukCreateManyInput = {
  id?: number
  produkId: number
  tanggal_masuk?: Date | string
  nominal_modal: number
  jumlah_barang_masuk: number
}

export type barang_masukUpdateManyMutationInput = {
  tanggal_masuk?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  nominal_modal?: Prisma.IntFieldUpdateOperationsInput | number
  jumlah_barang_masuk?: Prisma.IntFieldUpdateOperationsInput | number
}

export type barang_masukUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  produkId?: Prisma.IntFieldUpdateOperationsInput | number
  tanggal_masuk?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  nominal_modal?: Prisma.IntFieldUpdateOperationsInput | number
  jumlah_barang_masuk?: Prisma.IntFieldUpdateOperationsInput | number
}

export type Barang_masukListRelationFilter = {
  every?: Prisma.barang_masukWhereInput
  some?: Prisma.barang_masukWhereInput
  none?: Prisma.barang_masukWhereInput
}

export type barang_masukOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type barang_masukCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  produkId?: Prisma.SortOrder
  tanggal_masuk?: Prisma.SortOrder
  nominal_modal?: Prisma.SortOrder
  jumlah_barang_masuk?: Prisma.SortOrder
}

export type barang_masukAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  produkId?: Prisma.SortOrder
  nominal_modal?: Prisma.SortOrder
  jumlah_barang_masuk?: Prisma.SortOrder
}

export type barang_masukMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  produkId?: Prisma.SortOrder
  tanggal_masuk?: Prisma.SortOrder
  nominal_modal?: Prisma.SortOrder
  jumlah_barang_masuk?: Prisma.SortOrder
}

export type barang_masukMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  produkId?: Prisma.SortOrder
  tanggal_masuk?: Prisma.SortOrder
  nominal_modal?: Prisma.SortOrder
  jumlah_barang_masuk?: Prisma.SortOrder
}

export type barang_masukSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  produkId?: Prisma.SortOrder
  nominal_modal?: Prisma.SortOrder
  jumlah_barang_masuk?: Prisma.SortOrder
}

export type barang_masukCreateNestedManyWithoutProdukInput = {
  create?: Prisma.XOR<Prisma.barang_masukCreateWithoutProdukInput, Prisma.barang_masukUncheckedCreateWithoutProdukInput> | Prisma.barang_masukCreateWithoutProdukInput[] | Prisma.barang_masukUncheckedCreateWithoutProdukInput[]
  connectOrCreate?: Prisma.barang_masukCreateOrConnectWithoutProdukInput | Prisma.barang_masukCreateOrConnectWithoutProdukInput[]
  createMany?: Prisma.barang_masukCreateManyProdukInputEnvelope
  connect?: Prisma.barang_masukWhereUniqueInput | Prisma.barang_masukWhereUniqueInput[]
}

export type barang_masukUncheckedCreateNestedManyWithoutProdukInput = {
  create?: Prisma.XOR<Prisma.barang_masukCreateWithoutProdukInput, Prisma.barang_masukUncheckedCreateWithoutProdukInput> | Prisma.barang_masukCreateWithoutProdukInput[] | Prisma.barang_masukUncheckedCreateWithoutProdukInput[]
  connectOrCreate?: Prisma.barang_masukCreateOrConnectWithoutProdukInput | Prisma.barang_masukCreateOrConnectWithoutProdukInput[]
  createMany?: Prisma.barang_masukCreateManyProdukInputEnvelope
  connect?: Prisma.barang_masukWhereUniqueInput | Prisma.barang_masukWhereUniqueInput[]
}

export type barang_masukUpdateManyWithoutProdukNestedInput = {
  create?: Prisma.XOR<Prisma.barang_masukCreateWithoutProdukInput, Prisma.barang_masukUncheckedCreateWithoutProdukInput> | Prisma.barang_masukCreateWithoutProdukInput[] | Prisma.barang_masukUncheckedCreateWithoutProdukInput[]
  connectOrCreate?: Prisma.barang_masukCreateOrConnectWithoutProdukInput | Prisma.barang_masukCreateOrConnectWithoutProdukInput[]
  upsert?: Prisma.barang_masukUpsertWithWhereUniqueWithoutProdukInput | Prisma.barang_masukUpsertWithWhereUniqueWithoutProdukInput[]
  createMany?: Prisma.barang_masukCreateManyProdukInputEnvelope
  set?: Prisma.barang_masukWhereUniqueInput | Prisma.barang_masukWhereUniqueInput[]
  disconnect?: Prisma.barang_masukWhereUniqueInput | Prisma.barang_masukWhereUniqueInput[]
  delete?: Prisma.barang_masukWhereUniqueInput | Prisma.barang_masukWhereUniqueInput[]
  connect?: Prisma.barang_masukWhereUniqueInput | Prisma.barang_masukWhereUniqueInput[]
  update?: Prisma.barang_masukUpdateWithWhereUniqueWithoutProdukInput | Prisma.barang_masukUpdateWithWhereUniqueWithoutProdukInput[]
  updateMany?: Prisma.barang_masukUpdateManyWithWhereWithoutProdukInput | Prisma.barang_masukUpdateManyWithWhereWithoutProdukInput[]
  deleteMany?: Prisma.barang_masukScalarWhereInput | Prisma.barang_masukScalarWhereInput[]
}

export type barang_masukUncheckedUpdateManyWithoutProdukNestedInput = {
  create?: Prisma.XOR<Prisma.barang_masukCreateWithoutProdukInput, Prisma.barang_masukUncheckedCreateWithoutProdukInput> | Prisma.barang_masukCreateWithoutProdukInput[] | Prisma.barang_masukUncheckedCreateWithoutProdukInput[]
  connectOrCreate?: Prisma.barang_masukCreateOrConnectWithoutProdukInput | Prisma.barang_masukCreateOrConnectWithoutProdukInput[]
  upsert?: Prisma.barang_masukUpsertWithWhereUniqueWithoutProdukInput | Prisma.barang_masukUpsertWithWhereUniqueWithoutProdukInput[]
  createMany?: Prisma.barang_masukCreateManyProdukInputEnvelope
  set?: Prisma.barang_masukWhereUniqueInput | Prisma.barang_masukWhereUniqueInput[]
  disconnect?: Prisma.barang_masukWhereUniqueInput | Prisma.barang_masukWhereUniqueInput[]
  delete?: Prisma.barang_masukWhereUniqueInput | Prisma.barang_masukWhereUniqueInput[]
  connect?: Prisma.barang_masukWhereUniqueInput | Prisma.barang_masukWhereUniqueInput[]
  update?: Prisma.barang_masukUpdateWithWhereUniqueWithoutProdukInput | Prisma.barang_masukUpdateWithWhereUniqueWithoutProdukInput[]
  updateMany?: Prisma.barang_masukUpdateManyWithWhereWithoutProdukInput | Prisma.barang_masukUpdateManyWithWhereWithoutProdukInput[]
  deleteMany?: Prisma.barang_masukScalarWhereInput | Prisma.barang_masukScalarWhereInput[]
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type barang_masukCreateWithoutProdukInput = {
  tanggal_masuk?: Date | string
  nominal_modal: number
  jumlah_barang_masuk: number
}

export type barang_masukUncheckedCreateWithoutProdukInput = {
  id?: number
  tanggal_masuk?: Date | string
  nominal_modal: number
  jumlah_barang_masuk: number
}

export type barang_masukCreateOrConnectWithoutProdukInput = {
  where: Prisma.barang_masukWhereUniqueInput
  create: Prisma.XOR<Prisma.barang_masukCreateWithoutProdukInput, Prisma.barang_masukUncheckedCreateWithoutProdukInput>
}

export type barang_masukCreateManyProdukInputEnvelope = {
  data: Prisma.barang_masukCreateManyProdukInput | Prisma.barang_masukCreateManyProdukInput[]
  skipDuplicates?: boolean
}

export type barang_masukUpsertWithWhereUniqueWithoutProdukInput = {
  where: Prisma.barang_masukWhereUniqueInput
  update: Prisma.XOR<Prisma.barang_masukUpdateWithoutProdukInput, Prisma.barang_masukUncheckedUpdateWithoutProdukInput>
  create: Prisma.XOR<Prisma.barang_masukCreateWithoutProdukInput, Prisma.barang_masukUncheckedCreateWithoutProdukInput>
}

export type barang_masukUpdateWithWhereUniqueWithoutProdukInput = {
  where: Prisma.barang_masukWhereUniqueInput
  data: Prisma.XOR<Prisma.barang_masukUpdateWithoutProdukInput, Prisma.barang_masukUncheckedUpdateWithoutProdukInput>
}

export type barang_masukUpdateManyWithWhereWithoutProdukInput = {
  where: Prisma.barang_masukScalarWhereInput
  data: Prisma.XOR<Prisma.barang_masukUpdateManyMutationInput, Prisma.barang_masukUncheckedUpdateManyWithoutProdukInput>
}

export type barang_masukScalarWhereInput = {
  AND?: Prisma.barang_masukScalarWhereInput | Prisma.barang_masukScalarWhereInput[]
  OR?: Prisma.barang_masukScalarWhereInput[]
  NOT?: Prisma.barang_masukScalarWhereInput | Prisma.barang_masukScalarWhereInput[]
  id?: Prisma.IntFilter<"barang_masuk"> | number
  produkId?: Prisma.IntFilter<"barang_masuk"> | number
  tanggal_masuk?: Prisma.DateTimeFilter<"barang_masuk"> | Date | string
  nominal_modal?: Prisma.IntFilter<"barang_masuk"> | number
  jumlah_barang_masuk?: Prisma.IntFilter<"barang_masuk"> | number
}

export type barang_masukCreateManyProdukInput = {
  id?: number
  tanggal_masuk?: Date | string
  nominal_modal: number
  jumlah_barang_masuk: number
}

export type barang_masukUpdateWithoutProdukInput = {
  tanggal_masuk?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  nominal_modal?: Prisma.IntFieldUpdateOperationsInput | number
  jumlah_barang_masuk?: Prisma.IntFieldUpdateOperationsInput | number
}

export type barang_masukUncheckedUpdateWithoutProdukInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  tanggal_masuk?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  nominal_modal?: Prisma.IntFieldUpdateOperationsInput | number
  jumlah_barang_masuk?: Prisma.IntFieldUpdateOperationsInput | number
}

export type barang_masukUncheckedUpdateManyWithoutProdukInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  tanggal_masuk?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  nominal_modal?: Prisma.IntFieldUpdateOperationsInput | number
  jumlah_barang_masuk?: Prisma.IntFieldUpdateOperationsInput | number
}



export type barang_masukSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  produkId?: boolean
  tanggal_masuk?: boolean
  nominal_modal?: boolean
  jumlah_barang_masuk?: boolean
  produk?: boolean | Prisma.produkDefaultArgs<ExtArgs>
}, ExtArgs["result"]["barang_masuk"]>

export type barang_masukSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  produkId?: boolean
  tanggal_masuk?: boolean
  nominal_modal?: boolean
  jumlah_barang_masuk?: boolean
  produk?: boolean | Prisma.produkDefaultArgs<ExtArgs>
}, ExtArgs["result"]["barang_masuk"]>

export type barang_masukSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  produkId?: boolean
  tanggal_masuk?: boolean
  nominal_modal?: boolean
  jumlah_barang_masuk?: boolean
  produk?: boolean | Prisma.produkDefaultArgs<ExtArgs>
}, ExtArgs["result"]["barang_masuk"]>

export type barang_masukSelectScalar = {
  id?: boolean
  produkId?: boolean
  tanggal_masuk?: boolean
  nominal_modal?: boolean
  jumlah_barang_masuk?: boolean
}

export type barang_masukOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "produkId" | "tanggal_masuk" | "nominal_modal" | "jumlah_barang_masuk", ExtArgs["result"]["barang_masuk"]>
export type barang_masukInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  produk?: boolean | Prisma.produkDefaultArgs<ExtArgs>
}
export type barang_masukIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  produk?: boolean | Prisma.produkDefaultArgs<ExtArgs>
}
export type barang_masukIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  produk?: boolean | Prisma.produkDefaultArgs<ExtArgs>
}

export type $barang_masukPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "barang_masuk"
  objects: {
    produk: Prisma.$produkPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    produkId: number
    tanggal_masuk: Date
    nominal_modal: number
    jumlah_barang_masuk: number
  }, ExtArgs["result"]["barang_masuk"]>
  composites: {}
}

export type barang_masukGetPayload<S extends boolean | null | undefined | barang_masukDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$barang_masukPayload, S>

export type barang_masukCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<barang_masukFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Barang_masukCountAggregateInputType | true
  }

export interface barang_masukDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['barang_masuk'], meta: { name: 'barang_masuk' } }
  /**
   * Find zero or one Barang_masuk that matches the filter.
   * @param {barang_masukFindUniqueArgs} args - Arguments to find a Barang_masuk
   * @example
   * // Get one Barang_masuk
   * const barang_masuk = await prisma.barang_masuk.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends barang_masukFindUniqueArgs>(args: Prisma.SelectSubset<T, barang_masukFindUniqueArgs<ExtArgs>>): Prisma.Prisma__barang_masukClient<runtime.Types.Result.GetResult<Prisma.$barang_masukPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Barang_masuk that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {barang_masukFindUniqueOrThrowArgs} args - Arguments to find a Barang_masuk
   * @example
   * // Get one Barang_masuk
   * const barang_masuk = await prisma.barang_masuk.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends barang_masukFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, barang_masukFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__barang_masukClient<runtime.Types.Result.GetResult<Prisma.$barang_masukPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Barang_masuk that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {barang_masukFindFirstArgs} args - Arguments to find a Barang_masuk
   * @example
   * // Get one Barang_masuk
   * const barang_masuk = await prisma.barang_masuk.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends barang_masukFindFirstArgs>(args?: Prisma.SelectSubset<T, barang_masukFindFirstArgs<ExtArgs>>): Prisma.Prisma__barang_masukClient<runtime.Types.Result.GetResult<Prisma.$barang_masukPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Barang_masuk that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {barang_masukFindFirstOrThrowArgs} args - Arguments to find a Barang_masuk
   * @example
   * // Get one Barang_masuk
   * const barang_masuk = await prisma.barang_masuk.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends barang_masukFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, barang_masukFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__barang_masukClient<runtime.Types.Result.GetResult<Prisma.$barang_masukPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Barang_masuks that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {barang_masukFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Barang_masuks
   * const barang_masuks = await prisma.barang_masuk.findMany()
   * 
   * // Get first 10 Barang_masuks
   * const barang_masuks = await prisma.barang_masuk.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const barang_masukWithIdOnly = await prisma.barang_masuk.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends barang_masukFindManyArgs>(args?: Prisma.SelectSubset<T, barang_masukFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$barang_masukPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Barang_masuk.
   * @param {barang_masukCreateArgs} args - Arguments to create a Barang_masuk.
   * @example
   * // Create one Barang_masuk
   * const Barang_masuk = await prisma.barang_masuk.create({
   *   data: {
   *     // ... data to create a Barang_masuk
   *   }
   * })
   * 
   */
  create<T extends barang_masukCreateArgs>(args: Prisma.SelectSubset<T, barang_masukCreateArgs<ExtArgs>>): Prisma.Prisma__barang_masukClient<runtime.Types.Result.GetResult<Prisma.$barang_masukPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Barang_masuks.
   * @param {barang_masukCreateManyArgs} args - Arguments to create many Barang_masuks.
   * @example
   * // Create many Barang_masuks
   * const barang_masuk = await prisma.barang_masuk.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends barang_masukCreateManyArgs>(args?: Prisma.SelectSubset<T, barang_masukCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Barang_masuks and returns the data saved in the database.
   * @param {barang_masukCreateManyAndReturnArgs} args - Arguments to create many Barang_masuks.
   * @example
   * // Create many Barang_masuks
   * const barang_masuk = await prisma.barang_masuk.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Barang_masuks and only return the `id`
   * const barang_masukWithIdOnly = await prisma.barang_masuk.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends barang_masukCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, barang_masukCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$barang_masukPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Barang_masuk.
   * @param {barang_masukDeleteArgs} args - Arguments to delete one Barang_masuk.
   * @example
   * // Delete one Barang_masuk
   * const Barang_masuk = await prisma.barang_masuk.delete({
   *   where: {
   *     // ... filter to delete one Barang_masuk
   *   }
   * })
   * 
   */
  delete<T extends barang_masukDeleteArgs>(args: Prisma.SelectSubset<T, barang_masukDeleteArgs<ExtArgs>>): Prisma.Prisma__barang_masukClient<runtime.Types.Result.GetResult<Prisma.$barang_masukPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Barang_masuk.
   * @param {barang_masukUpdateArgs} args - Arguments to update one Barang_masuk.
   * @example
   * // Update one Barang_masuk
   * const barang_masuk = await prisma.barang_masuk.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends barang_masukUpdateArgs>(args: Prisma.SelectSubset<T, barang_masukUpdateArgs<ExtArgs>>): Prisma.Prisma__barang_masukClient<runtime.Types.Result.GetResult<Prisma.$barang_masukPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Barang_masuks.
   * @param {barang_masukDeleteManyArgs} args - Arguments to filter Barang_masuks to delete.
   * @example
   * // Delete a few Barang_masuks
   * const { count } = await prisma.barang_masuk.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends barang_masukDeleteManyArgs>(args?: Prisma.SelectSubset<T, barang_masukDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Barang_masuks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {barang_masukUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Barang_masuks
   * const barang_masuk = await prisma.barang_masuk.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends barang_masukUpdateManyArgs>(args: Prisma.SelectSubset<T, barang_masukUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Barang_masuks and returns the data updated in the database.
   * @param {barang_masukUpdateManyAndReturnArgs} args - Arguments to update many Barang_masuks.
   * @example
   * // Update many Barang_masuks
   * const barang_masuk = await prisma.barang_masuk.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Barang_masuks and only return the `id`
   * const barang_masukWithIdOnly = await prisma.barang_masuk.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends barang_masukUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, barang_masukUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$barang_masukPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Barang_masuk.
   * @param {barang_masukUpsertArgs} args - Arguments to update or create a Barang_masuk.
   * @example
   * // Update or create a Barang_masuk
   * const barang_masuk = await prisma.barang_masuk.upsert({
   *   create: {
   *     // ... data to create a Barang_masuk
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Barang_masuk we want to update
   *   }
   * })
   */
  upsert<T extends barang_masukUpsertArgs>(args: Prisma.SelectSubset<T, barang_masukUpsertArgs<ExtArgs>>): Prisma.Prisma__barang_masukClient<runtime.Types.Result.GetResult<Prisma.$barang_masukPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Barang_masuks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {barang_masukCountArgs} args - Arguments to filter Barang_masuks to count.
   * @example
   * // Count the number of Barang_masuks
   * const count = await prisma.barang_masuk.count({
   *   where: {
   *     // ... the filter for the Barang_masuks we want to count
   *   }
   * })
  **/
  count<T extends barang_masukCountArgs>(
    args?: Prisma.Subset<T, barang_masukCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Barang_masukCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Barang_masuk.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Barang_masukAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Barang_masukAggregateArgs>(args: Prisma.Subset<T, Barang_masukAggregateArgs>): Prisma.PrismaPromise<GetBarang_masukAggregateType<T>>

  /**
   * Group by Barang_masuk.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {barang_masukGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends barang_masukGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: barang_masukGroupByArgs['orderBy'] }
      : { orderBy?: barang_masukGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, barang_masukGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetBarang_masukGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the barang_masuk model
 */
readonly fields: barang_masukFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for barang_masuk.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__barang_masukClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  produk<T extends Prisma.produkDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.produkDefaultArgs<ExtArgs>>): Prisma.Prisma__produkClient<runtime.Types.Result.GetResult<Prisma.$produkPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the barang_masuk model
 */
export interface barang_masukFieldRefs {
  readonly id: Prisma.FieldRef<"barang_masuk", 'Int'>
  readonly produkId: Prisma.FieldRef<"barang_masuk", 'Int'>
  readonly tanggal_masuk: Prisma.FieldRef<"barang_masuk", 'DateTime'>
  readonly nominal_modal: Prisma.FieldRef<"barang_masuk", 'Int'>
  readonly jumlah_barang_masuk: Prisma.FieldRef<"barang_masuk", 'Int'>
}
    

// Custom InputTypes
/**
 * barang_masuk findUnique
 */
export type barang_masukFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the barang_masuk
   */
  select?: Prisma.barang_masukSelect<ExtArgs> | null
  /**
   * Omit specific fields from the barang_masuk
   */
  omit?: Prisma.barang_masukOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.barang_masukInclude<ExtArgs> | null
  /**
   * Filter, which barang_masuk to fetch.
   */
  where: Prisma.barang_masukWhereUniqueInput
}

/**
 * barang_masuk findUniqueOrThrow
 */
export type barang_masukFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the barang_masuk
   */
  select?: Prisma.barang_masukSelect<ExtArgs> | null
  /**
   * Omit specific fields from the barang_masuk
   */
  omit?: Prisma.barang_masukOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.barang_masukInclude<ExtArgs> | null
  /**
   * Filter, which barang_masuk to fetch.
   */
  where: Prisma.barang_masukWhereUniqueInput
}

/**
 * barang_masuk findFirst
 */
export type barang_masukFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the barang_masuk
   */
  select?: Prisma.barang_masukSelect<ExtArgs> | null
  /**
   * Omit specific fields from the barang_masuk
   */
  omit?: Prisma.barang_masukOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.barang_masukInclude<ExtArgs> | null
  /**
   * Filter, which barang_masuk to fetch.
   */
  where?: Prisma.barang_masukWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of barang_masuks to fetch.
   */
  orderBy?: Prisma.barang_masukOrderByWithRelationInput | Prisma.barang_masukOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for barang_masuks.
   */
  cursor?: Prisma.barang_masukWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` barang_masuks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` barang_masuks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of barang_masuks.
   */
  distinct?: Prisma.Barang_masukScalarFieldEnum | Prisma.Barang_masukScalarFieldEnum[]
}

/**
 * barang_masuk findFirstOrThrow
 */
export type barang_masukFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the barang_masuk
   */
  select?: Prisma.barang_masukSelect<ExtArgs> | null
  /**
   * Omit specific fields from the barang_masuk
   */
  omit?: Prisma.barang_masukOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.barang_masukInclude<ExtArgs> | null
  /**
   * Filter, which barang_masuk to fetch.
   */
  where?: Prisma.barang_masukWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of barang_masuks to fetch.
   */
  orderBy?: Prisma.barang_masukOrderByWithRelationInput | Prisma.barang_masukOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for barang_masuks.
   */
  cursor?: Prisma.barang_masukWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` barang_masuks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` barang_masuks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of barang_masuks.
   */
  distinct?: Prisma.Barang_masukScalarFieldEnum | Prisma.Barang_masukScalarFieldEnum[]
}

/**
 * barang_masuk findMany
 */
export type barang_masukFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the barang_masuk
   */
  select?: Prisma.barang_masukSelect<ExtArgs> | null
  /**
   * Omit specific fields from the barang_masuk
   */
  omit?: Prisma.barang_masukOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.barang_masukInclude<ExtArgs> | null
  /**
   * Filter, which barang_masuks to fetch.
   */
  where?: Prisma.barang_masukWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of barang_masuks to fetch.
   */
  orderBy?: Prisma.barang_masukOrderByWithRelationInput | Prisma.barang_masukOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing barang_masuks.
   */
  cursor?: Prisma.barang_masukWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` barang_masuks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` barang_masuks.
   */
  skip?: number
  distinct?: Prisma.Barang_masukScalarFieldEnum | Prisma.Barang_masukScalarFieldEnum[]
}

/**
 * barang_masuk create
 */
export type barang_masukCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the barang_masuk
   */
  select?: Prisma.barang_masukSelect<ExtArgs> | null
  /**
   * Omit specific fields from the barang_masuk
   */
  omit?: Prisma.barang_masukOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.barang_masukInclude<ExtArgs> | null
  /**
   * The data needed to create a barang_masuk.
   */
  data: Prisma.XOR<Prisma.barang_masukCreateInput, Prisma.barang_masukUncheckedCreateInput>
}

/**
 * barang_masuk createMany
 */
export type barang_masukCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many barang_masuks.
   */
  data: Prisma.barang_masukCreateManyInput | Prisma.barang_masukCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * barang_masuk createManyAndReturn
 */
export type barang_masukCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the barang_masuk
   */
  select?: Prisma.barang_masukSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the barang_masuk
   */
  omit?: Prisma.barang_masukOmit<ExtArgs> | null
  /**
   * The data used to create many barang_masuks.
   */
  data: Prisma.barang_masukCreateManyInput | Prisma.barang_masukCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.barang_masukIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * barang_masuk update
 */
export type barang_masukUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the barang_masuk
   */
  select?: Prisma.barang_masukSelect<ExtArgs> | null
  /**
   * Omit specific fields from the barang_masuk
   */
  omit?: Prisma.barang_masukOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.barang_masukInclude<ExtArgs> | null
  /**
   * The data needed to update a barang_masuk.
   */
  data: Prisma.XOR<Prisma.barang_masukUpdateInput, Prisma.barang_masukUncheckedUpdateInput>
  /**
   * Choose, which barang_masuk to update.
   */
  where: Prisma.barang_masukWhereUniqueInput
}

/**
 * barang_masuk updateMany
 */
export type barang_masukUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update barang_masuks.
   */
  data: Prisma.XOR<Prisma.barang_masukUpdateManyMutationInput, Prisma.barang_masukUncheckedUpdateManyInput>
  /**
   * Filter which barang_masuks to update
   */
  where?: Prisma.barang_masukWhereInput
  /**
   * Limit how many barang_masuks to update.
   */
  limit?: number
}

/**
 * barang_masuk updateManyAndReturn
 */
export type barang_masukUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the barang_masuk
   */
  select?: Prisma.barang_masukSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the barang_masuk
   */
  omit?: Prisma.barang_masukOmit<ExtArgs> | null
  /**
   * The data used to update barang_masuks.
   */
  data: Prisma.XOR<Prisma.barang_masukUpdateManyMutationInput, Prisma.barang_masukUncheckedUpdateManyInput>
  /**
   * Filter which barang_masuks to update
   */
  where?: Prisma.barang_masukWhereInput
  /**
   * Limit how many barang_masuks to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.barang_masukIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * barang_masuk upsert
 */
export type barang_masukUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the barang_masuk
   */
  select?: Prisma.barang_masukSelect<ExtArgs> | null
  /**
   * Omit specific fields from the barang_masuk
   */
  omit?: Prisma.barang_masukOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.barang_masukInclude<ExtArgs> | null
  /**
   * The filter to search for the barang_masuk to update in case it exists.
   */
  where: Prisma.barang_masukWhereUniqueInput
  /**
   * In case the barang_masuk found by the `where` argument doesn't exist, create a new barang_masuk with this data.
   */
  create: Prisma.XOR<Prisma.barang_masukCreateInput, Prisma.barang_masukUncheckedCreateInput>
  /**
   * In case the barang_masuk was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.barang_masukUpdateInput, Prisma.barang_masukUncheckedUpdateInput>
}

/**
 * barang_masuk delete
 */
export type barang_masukDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the barang_masuk
   */
  select?: Prisma.barang_masukSelect<ExtArgs> | null
  /**
   * Omit specific fields from the barang_masuk
   */
  omit?: Prisma.barang_masukOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.barang_masukInclude<ExtArgs> | null
  /**
   * Filter which barang_masuk to delete.
   */
  where: Prisma.barang_masukWhereUniqueInput
}

/**
 * barang_masuk deleteMany
 */
export type barang_masukDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which barang_masuks to delete
   */
  where?: Prisma.barang_masukWhereInput
  /**
   * Limit how many barang_masuks to delete.
   */
  limit?: number
}

/**
 * barang_masuk without action
 */
export type barang_masukDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the barang_masuk
   */
  select?: Prisma.barang_masukSelect<ExtArgs> | null
  /**
   * Omit specific fields from the barang_masuk
   */
  omit?: Prisma.barang_masukOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.barang_masukInclude<ExtArgs> | null
}
