
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `lokasi_gudang` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model lokasi_gudang
 * 
 */
export type lokasi_gudangModel = runtime.Types.Result.DefaultSelection<Prisma.$lokasi_gudangPayload>

export type AggregateLokasi_gudang = {
  _count: Lokasi_gudangCountAggregateOutputType | null
  _avg: Lokasi_gudangAvgAggregateOutputType | null
  _sum: Lokasi_gudangSumAggregateOutputType | null
  _min: Lokasi_gudangMinAggregateOutputType | null
  _max: Lokasi_gudangMaxAggregateOutputType | null
}

export type Lokasi_gudangAvgAggregateOutputType = {
  id: number | null
}

export type Lokasi_gudangSumAggregateOutputType = {
  id: number | null
}

export type Lokasi_gudangMinAggregateOutputType = {
  id: number | null
  nama_gudang: string | null
  alamat_gudang: string | null
  warna_gudang: string | null
}

export type Lokasi_gudangMaxAggregateOutputType = {
  id: number | null
  nama_gudang: string | null
  alamat_gudang: string | null
  warna_gudang: string | null
}

export type Lokasi_gudangCountAggregateOutputType = {
  id: number
  nama_gudang: number
  alamat_gudang: number
  warna_gudang: number
  _all: number
}


export type Lokasi_gudangAvgAggregateInputType = {
  id?: true
}

export type Lokasi_gudangSumAggregateInputType = {
  id?: true
}

export type Lokasi_gudangMinAggregateInputType = {
  id?: true
  nama_gudang?: true
  alamat_gudang?: true
  warna_gudang?: true
}

export type Lokasi_gudangMaxAggregateInputType = {
  id?: true
  nama_gudang?: true
  alamat_gudang?: true
  warna_gudang?: true
}

export type Lokasi_gudangCountAggregateInputType = {
  id?: true
  nama_gudang?: true
  alamat_gudang?: true
  warna_gudang?: true
  _all?: true
}

export type Lokasi_gudangAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which lokasi_gudang to aggregate.
   */
  where?: Prisma.lokasi_gudangWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of lokasi_gudangs to fetch.
   */
  orderBy?: Prisma.lokasi_gudangOrderByWithRelationInput | Prisma.lokasi_gudangOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.lokasi_gudangWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` lokasi_gudangs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` lokasi_gudangs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned lokasi_gudangs
  **/
  _count?: true | Lokasi_gudangCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Lokasi_gudangAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Lokasi_gudangSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Lokasi_gudangMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Lokasi_gudangMaxAggregateInputType
}

export type GetLokasi_gudangAggregateType<T extends Lokasi_gudangAggregateArgs> = {
      [P in keyof T & keyof AggregateLokasi_gudang]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateLokasi_gudang[P]>
    : Prisma.GetScalarType<T[P], AggregateLokasi_gudang[P]>
}




export type lokasi_gudangGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.lokasi_gudangWhereInput
  orderBy?: Prisma.lokasi_gudangOrderByWithAggregationInput | Prisma.lokasi_gudangOrderByWithAggregationInput[]
  by: Prisma.Lokasi_gudangScalarFieldEnum[] | Prisma.Lokasi_gudangScalarFieldEnum
  having?: Prisma.lokasi_gudangScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Lokasi_gudangCountAggregateInputType | true
  _avg?: Lokasi_gudangAvgAggregateInputType
  _sum?: Lokasi_gudangSumAggregateInputType
  _min?: Lokasi_gudangMinAggregateInputType
  _max?: Lokasi_gudangMaxAggregateInputType
}

export type Lokasi_gudangGroupByOutputType = {
  id: number
  nama_gudang: string
  alamat_gudang: string
  warna_gudang: string
  _count: Lokasi_gudangCountAggregateOutputType | null
  _avg: Lokasi_gudangAvgAggregateOutputType | null
  _sum: Lokasi_gudangSumAggregateOutputType | null
  _min: Lokasi_gudangMinAggregateOutputType | null
  _max: Lokasi_gudangMaxAggregateOutputType | null
}

type GetLokasi_gudangGroupByPayload<T extends lokasi_gudangGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Lokasi_gudangGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Lokasi_gudangGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Lokasi_gudangGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Lokasi_gudangGroupByOutputType[P]>
      }
    >
  >



export type lokasi_gudangWhereInput = {
  AND?: Prisma.lokasi_gudangWhereInput | Prisma.lokasi_gudangWhereInput[]
  OR?: Prisma.lokasi_gudangWhereInput[]
  NOT?: Prisma.lokasi_gudangWhereInput | Prisma.lokasi_gudangWhereInput[]
  id?: Prisma.IntFilter<"lokasi_gudang"> | number
  nama_gudang?: Prisma.StringFilter<"lokasi_gudang"> | string
  alamat_gudang?: Prisma.StringFilter<"lokasi_gudang"> | string
  warna_gudang?: Prisma.StringFilter<"lokasi_gudang"> | string
  produk?: Prisma.ProdukListRelationFilter
}

export type lokasi_gudangOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  nama_gudang?: Prisma.SortOrder
  alamat_gudang?: Prisma.SortOrder
  warna_gudang?: Prisma.SortOrder
  produk?: Prisma.produkOrderByRelationAggregateInput
}

export type lokasi_gudangWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.lokasi_gudangWhereInput | Prisma.lokasi_gudangWhereInput[]
  OR?: Prisma.lokasi_gudangWhereInput[]
  NOT?: Prisma.lokasi_gudangWhereInput | Prisma.lokasi_gudangWhereInput[]
  nama_gudang?: Prisma.StringFilter<"lokasi_gudang"> | string
  alamat_gudang?: Prisma.StringFilter<"lokasi_gudang"> | string
  warna_gudang?: Prisma.StringFilter<"lokasi_gudang"> | string
  produk?: Prisma.ProdukListRelationFilter
}, "id">

export type lokasi_gudangOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  nama_gudang?: Prisma.SortOrder
  alamat_gudang?: Prisma.SortOrder
  warna_gudang?: Prisma.SortOrder
  _count?: Prisma.lokasi_gudangCountOrderByAggregateInput
  _avg?: Prisma.lokasi_gudangAvgOrderByAggregateInput
  _max?: Prisma.lokasi_gudangMaxOrderByAggregateInput
  _min?: Prisma.lokasi_gudangMinOrderByAggregateInput
  _sum?: Prisma.lokasi_gudangSumOrderByAggregateInput
}

export type lokasi_gudangScalarWhereWithAggregatesInput = {
  AND?: Prisma.lokasi_gudangScalarWhereWithAggregatesInput | Prisma.lokasi_gudangScalarWhereWithAggregatesInput[]
  OR?: Prisma.lokasi_gudangScalarWhereWithAggregatesInput[]
  NOT?: Prisma.lokasi_gudangScalarWhereWithAggregatesInput | Prisma.lokasi_gudangScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"lokasi_gudang"> | number
  nama_gudang?: Prisma.StringWithAggregatesFilter<"lokasi_gudang"> | string
  alamat_gudang?: Prisma.StringWithAggregatesFilter<"lokasi_gudang"> | string
  warna_gudang?: Prisma.StringWithAggregatesFilter<"lokasi_gudang"> | string
}

export type lokasi_gudangCreateInput = {
  nama_gudang: string
  alamat_gudang: string
  warna_gudang: string
  produk?: Prisma.produkCreateNestedManyWithoutLokasiInput
}

export type lokasi_gudangUncheckedCreateInput = {
  id?: number
  nama_gudang: string
  alamat_gudang: string
  warna_gudang: string
  produk?: Prisma.produkUncheckedCreateNestedManyWithoutLokasiInput
}

export type lokasi_gudangUpdateInput = {
  nama_gudang?: Prisma.StringFieldUpdateOperationsInput | string
  alamat_gudang?: Prisma.StringFieldUpdateOperationsInput | string
  warna_gudang?: Prisma.StringFieldUpdateOperationsInput | string
  produk?: Prisma.produkUpdateManyWithoutLokasiNestedInput
}

export type lokasi_gudangUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  nama_gudang?: Prisma.StringFieldUpdateOperationsInput | string
  alamat_gudang?: Prisma.StringFieldUpdateOperationsInput | string
  warna_gudang?: Prisma.StringFieldUpdateOperationsInput | string
  produk?: Prisma.produkUncheckedUpdateManyWithoutLokasiNestedInput
}

export type lokasi_gudangCreateManyInput = {
  id?: number
  nama_gudang: string
  alamat_gudang: string
  warna_gudang: string
}

export type lokasi_gudangUpdateManyMutationInput = {
  nama_gudang?: Prisma.StringFieldUpdateOperationsInput | string
  alamat_gudang?: Prisma.StringFieldUpdateOperationsInput | string
  warna_gudang?: Prisma.StringFieldUpdateOperationsInput | string
}

export type lokasi_gudangUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  nama_gudang?: Prisma.StringFieldUpdateOperationsInput | string
  alamat_gudang?: Prisma.StringFieldUpdateOperationsInput | string
  warna_gudang?: Prisma.StringFieldUpdateOperationsInput | string
}

export type lokasi_gudangCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nama_gudang?: Prisma.SortOrder
  alamat_gudang?: Prisma.SortOrder
  warna_gudang?: Prisma.SortOrder
}

export type lokasi_gudangAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type lokasi_gudangMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nama_gudang?: Prisma.SortOrder
  alamat_gudang?: Prisma.SortOrder
  warna_gudang?: Prisma.SortOrder
}

export type lokasi_gudangMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nama_gudang?: Prisma.SortOrder
  alamat_gudang?: Prisma.SortOrder
  warna_gudang?: Prisma.SortOrder
}

export type lokasi_gudangSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type Lokasi_gudangScalarRelationFilter = {
  is?: Prisma.lokasi_gudangWhereInput
  isNot?: Prisma.lokasi_gudangWhereInput
}

export type lokasi_gudangCreateNestedOneWithoutProdukInput = {
  create?: Prisma.XOR<Prisma.lokasi_gudangCreateWithoutProdukInput, Prisma.lokasi_gudangUncheckedCreateWithoutProdukInput>
  connectOrCreate?: Prisma.lokasi_gudangCreateOrConnectWithoutProdukInput
  connect?: Prisma.lokasi_gudangWhereUniqueInput
}

export type lokasi_gudangUpdateOneRequiredWithoutProdukNestedInput = {
  create?: Prisma.XOR<Prisma.lokasi_gudangCreateWithoutProdukInput, Prisma.lokasi_gudangUncheckedCreateWithoutProdukInput>
  connectOrCreate?: Prisma.lokasi_gudangCreateOrConnectWithoutProdukInput
  upsert?: Prisma.lokasi_gudangUpsertWithoutProdukInput
  connect?: Prisma.lokasi_gudangWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.lokasi_gudangUpdateToOneWithWhereWithoutProdukInput, Prisma.lokasi_gudangUpdateWithoutProdukInput>, Prisma.lokasi_gudangUncheckedUpdateWithoutProdukInput>
}

export type lokasi_gudangCreateWithoutProdukInput = {
  nama_gudang: string
  alamat_gudang: string
  warna_gudang: string
}

export type lokasi_gudangUncheckedCreateWithoutProdukInput = {
  id?: number
  nama_gudang: string
  alamat_gudang: string
  warna_gudang: string
}

export type lokasi_gudangCreateOrConnectWithoutProdukInput = {
  where: Prisma.lokasi_gudangWhereUniqueInput
  create: Prisma.XOR<Prisma.lokasi_gudangCreateWithoutProdukInput, Prisma.lokasi_gudangUncheckedCreateWithoutProdukInput>
}

export type lokasi_gudangUpsertWithoutProdukInput = {
  update: Prisma.XOR<Prisma.lokasi_gudangUpdateWithoutProdukInput, Prisma.lokasi_gudangUncheckedUpdateWithoutProdukInput>
  create: Prisma.XOR<Prisma.lokasi_gudangCreateWithoutProdukInput, Prisma.lokasi_gudangUncheckedCreateWithoutProdukInput>
  where?: Prisma.lokasi_gudangWhereInput
}

export type lokasi_gudangUpdateToOneWithWhereWithoutProdukInput = {
  where?: Prisma.lokasi_gudangWhereInput
  data: Prisma.XOR<Prisma.lokasi_gudangUpdateWithoutProdukInput, Prisma.lokasi_gudangUncheckedUpdateWithoutProdukInput>
}

export type lokasi_gudangUpdateWithoutProdukInput = {
  nama_gudang?: Prisma.StringFieldUpdateOperationsInput | string
  alamat_gudang?: Prisma.StringFieldUpdateOperationsInput | string
  warna_gudang?: Prisma.StringFieldUpdateOperationsInput | string
}

export type lokasi_gudangUncheckedUpdateWithoutProdukInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  nama_gudang?: Prisma.StringFieldUpdateOperationsInput | string
  alamat_gudang?: Prisma.StringFieldUpdateOperationsInput | string
  warna_gudang?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type Lokasi_gudangCountOutputType
 */

export type Lokasi_gudangCountOutputType = {
  produk: number
}

export type Lokasi_gudangCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  produk?: boolean | Lokasi_gudangCountOutputTypeCountProdukArgs
}

/**
 * Lokasi_gudangCountOutputType without action
 */
export type Lokasi_gudangCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lokasi_gudangCountOutputType
   */
  select?: Prisma.Lokasi_gudangCountOutputTypeSelect<ExtArgs> | null
}

/**
 * Lokasi_gudangCountOutputType without action
 */
export type Lokasi_gudangCountOutputTypeCountProdukArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.produkWhereInput
}


export type lokasi_gudangSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nama_gudang?: boolean
  alamat_gudang?: boolean
  warna_gudang?: boolean
  produk?: boolean | Prisma.lokasi_gudang$produkArgs<ExtArgs>
  _count?: boolean | Prisma.Lokasi_gudangCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["lokasi_gudang"]>

export type lokasi_gudangSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nama_gudang?: boolean
  alamat_gudang?: boolean
  warna_gudang?: boolean
}, ExtArgs["result"]["lokasi_gudang"]>

export type lokasi_gudangSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nama_gudang?: boolean
  alamat_gudang?: boolean
  warna_gudang?: boolean
}, ExtArgs["result"]["lokasi_gudang"]>

export type lokasi_gudangSelectScalar = {
  id?: boolean
  nama_gudang?: boolean
  alamat_gudang?: boolean
  warna_gudang?: boolean
}

export type lokasi_gudangOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "nama_gudang" | "alamat_gudang" | "warna_gudang", ExtArgs["result"]["lokasi_gudang"]>
export type lokasi_gudangInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  produk?: boolean | Prisma.lokasi_gudang$produkArgs<ExtArgs>
  _count?: boolean | Prisma.Lokasi_gudangCountOutputTypeDefaultArgs<ExtArgs>
}
export type lokasi_gudangIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type lokasi_gudangIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $lokasi_gudangPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "lokasi_gudang"
  objects: {
    produk: Prisma.$produkPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    nama_gudang: string
    alamat_gudang: string
    warna_gudang: string
  }, ExtArgs["result"]["lokasi_gudang"]>
  composites: {}
}

export type lokasi_gudangGetPayload<S extends boolean | null | undefined | lokasi_gudangDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$lokasi_gudangPayload, S>

export type lokasi_gudangCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<lokasi_gudangFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Lokasi_gudangCountAggregateInputType | true
  }

export interface lokasi_gudangDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['lokasi_gudang'], meta: { name: 'lokasi_gudang' } }
  /**
   * Find zero or one Lokasi_gudang that matches the filter.
   * @param {lokasi_gudangFindUniqueArgs} args - Arguments to find a Lokasi_gudang
   * @example
   * // Get one Lokasi_gudang
   * const lokasi_gudang = await prisma.lokasi_gudang.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends lokasi_gudangFindUniqueArgs>(args: Prisma.SelectSubset<T, lokasi_gudangFindUniqueArgs<ExtArgs>>): Prisma.Prisma__lokasi_gudangClient<runtime.Types.Result.GetResult<Prisma.$lokasi_gudangPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Lokasi_gudang that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {lokasi_gudangFindUniqueOrThrowArgs} args - Arguments to find a Lokasi_gudang
   * @example
   * // Get one Lokasi_gudang
   * const lokasi_gudang = await prisma.lokasi_gudang.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends lokasi_gudangFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, lokasi_gudangFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__lokasi_gudangClient<runtime.Types.Result.GetResult<Prisma.$lokasi_gudangPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Lokasi_gudang that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {lokasi_gudangFindFirstArgs} args - Arguments to find a Lokasi_gudang
   * @example
   * // Get one Lokasi_gudang
   * const lokasi_gudang = await prisma.lokasi_gudang.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends lokasi_gudangFindFirstArgs>(args?: Prisma.SelectSubset<T, lokasi_gudangFindFirstArgs<ExtArgs>>): Prisma.Prisma__lokasi_gudangClient<runtime.Types.Result.GetResult<Prisma.$lokasi_gudangPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Lokasi_gudang that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {lokasi_gudangFindFirstOrThrowArgs} args - Arguments to find a Lokasi_gudang
   * @example
   * // Get one Lokasi_gudang
   * const lokasi_gudang = await prisma.lokasi_gudang.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends lokasi_gudangFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, lokasi_gudangFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__lokasi_gudangClient<runtime.Types.Result.GetResult<Prisma.$lokasi_gudangPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Lokasi_gudangs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {lokasi_gudangFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Lokasi_gudangs
   * const lokasi_gudangs = await prisma.lokasi_gudang.findMany()
   * 
   * // Get first 10 Lokasi_gudangs
   * const lokasi_gudangs = await prisma.lokasi_gudang.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const lokasi_gudangWithIdOnly = await prisma.lokasi_gudang.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends lokasi_gudangFindManyArgs>(args?: Prisma.SelectSubset<T, lokasi_gudangFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$lokasi_gudangPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Lokasi_gudang.
   * @param {lokasi_gudangCreateArgs} args - Arguments to create a Lokasi_gudang.
   * @example
   * // Create one Lokasi_gudang
   * const Lokasi_gudang = await prisma.lokasi_gudang.create({
   *   data: {
   *     // ... data to create a Lokasi_gudang
   *   }
   * })
   * 
   */
  create<T extends lokasi_gudangCreateArgs>(args: Prisma.SelectSubset<T, lokasi_gudangCreateArgs<ExtArgs>>): Prisma.Prisma__lokasi_gudangClient<runtime.Types.Result.GetResult<Prisma.$lokasi_gudangPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Lokasi_gudangs.
   * @param {lokasi_gudangCreateManyArgs} args - Arguments to create many Lokasi_gudangs.
   * @example
   * // Create many Lokasi_gudangs
   * const lokasi_gudang = await prisma.lokasi_gudang.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends lokasi_gudangCreateManyArgs>(args?: Prisma.SelectSubset<T, lokasi_gudangCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Lokasi_gudangs and returns the data saved in the database.
   * @param {lokasi_gudangCreateManyAndReturnArgs} args - Arguments to create many Lokasi_gudangs.
   * @example
   * // Create many Lokasi_gudangs
   * const lokasi_gudang = await prisma.lokasi_gudang.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Lokasi_gudangs and only return the `id`
   * const lokasi_gudangWithIdOnly = await prisma.lokasi_gudang.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends lokasi_gudangCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, lokasi_gudangCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$lokasi_gudangPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Lokasi_gudang.
   * @param {lokasi_gudangDeleteArgs} args - Arguments to delete one Lokasi_gudang.
   * @example
   * // Delete one Lokasi_gudang
   * const Lokasi_gudang = await prisma.lokasi_gudang.delete({
   *   where: {
   *     // ... filter to delete one Lokasi_gudang
   *   }
   * })
   * 
   */
  delete<T extends lokasi_gudangDeleteArgs>(args: Prisma.SelectSubset<T, lokasi_gudangDeleteArgs<ExtArgs>>): Prisma.Prisma__lokasi_gudangClient<runtime.Types.Result.GetResult<Prisma.$lokasi_gudangPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Lokasi_gudang.
   * @param {lokasi_gudangUpdateArgs} args - Arguments to update one Lokasi_gudang.
   * @example
   * // Update one Lokasi_gudang
   * const lokasi_gudang = await prisma.lokasi_gudang.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends lokasi_gudangUpdateArgs>(args: Prisma.SelectSubset<T, lokasi_gudangUpdateArgs<ExtArgs>>): Prisma.Prisma__lokasi_gudangClient<runtime.Types.Result.GetResult<Prisma.$lokasi_gudangPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Lokasi_gudangs.
   * @param {lokasi_gudangDeleteManyArgs} args - Arguments to filter Lokasi_gudangs to delete.
   * @example
   * // Delete a few Lokasi_gudangs
   * const { count } = await prisma.lokasi_gudang.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends lokasi_gudangDeleteManyArgs>(args?: Prisma.SelectSubset<T, lokasi_gudangDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Lokasi_gudangs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {lokasi_gudangUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Lokasi_gudangs
   * const lokasi_gudang = await prisma.lokasi_gudang.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends lokasi_gudangUpdateManyArgs>(args: Prisma.SelectSubset<T, lokasi_gudangUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Lokasi_gudangs and returns the data updated in the database.
   * @param {lokasi_gudangUpdateManyAndReturnArgs} args - Arguments to update many Lokasi_gudangs.
   * @example
   * // Update many Lokasi_gudangs
   * const lokasi_gudang = await prisma.lokasi_gudang.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Lokasi_gudangs and only return the `id`
   * const lokasi_gudangWithIdOnly = await prisma.lokasi_gudang.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends lokasi_gudangUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, lokasi_gudangUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$lokasi_gudangPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Lokasi_gudang.
   * @param {lokasi_gudangUpsertArgs} args - Arguments to update or create a Lokasi_gudang.
   * @example
   * // Update or create a Lokasi_gudang
   * const lokasi_gudang = await prisma.lokasi_gudang.upsert({
   *   create: {
   *     // ... data to create a Lokasi_gudang
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Lokasi_gudang we want to update
   *   }
   * })
   */
  upsert<T extends lokasi_gudangUpsertArgs>(args: Prisma.SelectSubset<T, lokasi_gudangUpsertArgs<ExtArgs>>): Prisma.Prisma__lokasi_gudangClient<runtime.Types.Result.GetResult<Prisma.$lokasi_gudangPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Lokasi_gudangs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {lokasi_gudangCountArgs} args - Arguments to filter Lokasi_gudangs to count.
   * @example
   * // Count the number of Lokasi_gudangs
   * const count = await prisma.lokasi_gudang.count({
   *   where: {
   *     // ... the filter for the Lokasi_gudangs we want to count
   *   }
   * })
  **/
  count<T extends lokasi_gudangCountArgs>(
    args?: Prisma.Subset<T, lokasi_gudangCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Lokasi_gudangCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Lokasi_gudang.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Lokasi_gudangAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Lokasi_gudangAggregateArgs>(args: Prisma.Subset<T, Lokasi_gudangAggregateArgs>): Prisma.PrismaPromise<GetLokasi_gudangAggregateType<T>>

  /**
   * Group by Lokasi_gudang.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {lokasi_gudangGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends lokasi_gudangGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: lokasi_gudangGroupByArgs['orderBy'] }
      : { orderBy?: lokasi_gudangGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, lokasi_gudangGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetLokasi_gudangGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the lokasi_gudang model
 */
readonly fields: lokasi_gudangFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for lokasi_gudang.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__lokasi_gudangClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  produk<T extends Prisma.lokasi_gudang$produkArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.lokasi_gudang$produkArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$produkPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the lokasi_gudang model
 */
export interface lokasi_gudangFieldRefs {
  readonly id: Prisma.FieldRef<"lokasi_gudang", 'Int'>
  readonly nama_gudang: Prisma.FieldRef<"lokasi_gudang", 'String'>
  readonly alamat_gudang: Prisma.FieldRef<"lokasi_gudang", 'String'>
  readonly warna_gudang: Prisma.FieldRef<"lokasi_gudang", 'String'>
}
    

// Custom InputTypes
/**
 * lokasi_gudang findUnique
 */
export type lokasi_gudangFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the lokasi_gudang
   */
  select?: Prisma.lokasi_gudangSelect<ExtArgs> | null
  /**
   * Omit specific fields from the lokasi_gudang
   */
  omit?: Prisma.lokasi_gudangOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.lokasi_gudangInclude<ExtArgs> | null
  /**
   * Filter, which lokasi_gudang to fetch.
   */
  where: Prisma.lokasi_gudangWhereUniqueInput
}

/**
 * lokasi_gudang findUniqueOrThrow
 */
export type lokasi_gudangFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the lokasi_gudang
   */
  select?: Prisma.lokasi_gudangSelect<ExtArgs> | null
  /**
   * Omit specific fields from the lokasi_gudang
   */
  omit?: Prisma.lokasi_gudangOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.lokasi_gudangInclude<ExtArgs> | null
  /**
   * Filter, which lokasi_gudang to fetch.
   */
  where: Prisma.lokasi_gudangWhereUniqueInput
}

/**
 * lokasi_gudang findFirst
 */
export type lokasi_gudangFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the lokasi_gudang
   */
  select?: Prisma.lokasi_gudangSelect<ExtArgs> | null
  /**
   * Omit specific fields from the lokasi_gudang
   */
  omit?: Prisma.lokasi_gudangOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.lokasi_gudangInclude<ExtArgs> | null
  /**
   * Filter, which lokasi_gudang to fetch.
   */
  where?: Prisma.lokasi_gudangWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of lokasi_gudangs to fetch.
   */
  orderBy?: Prisma.lokasi_gudangOrderByWithRelationInput | Prisma.lokasi_gudangOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for lokasi_gudangs.
   */
  cursor?: Prisma.lokasi_gudangWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` lokasi_gudangs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` lokasi_gudangs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of lokasi_gudangs.
   */
  distinct?: Prisma.Lokasi_gudangScalarFieldEnum | Prisma.Lokasi_gudangScalarFieldEnum[]
}

/**
 * lokasi_gudang findFirstOrThrow
 */
export type lokasi_gudangFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the lokasi_gudang
   */
  select?: Prisma.lokasi_gudangSelect<ExtArgs> | null
  /**
   * Omit specific fields from the lokasi_gudang
   */
  omit?: Prisma.lokasi_gudangOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.lokasi_gudangInclude<ExtArgs> | null
  /**
   * Filter, which lokasi_gudang to fetch.
   */
  where?: Prisma.lokasi_gudangWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of lokasi_gudangs to fetch.
   */
  orderBy?: Prisma.lokasi_gudangOrderByWithRelationInput | Prisma.lokasi_gudangOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for lokasi_gudangs.
   */
  cursor?: Prisma.lokasi_gudangWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` lokasi_gudangs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` lokasi_gudangs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of lokasi_gudangs.
   */
  distinct?: Prisma.Lokasi_gudangScalarFieldEnum | Prisma.Lokasi_gudangScalarFieldEnum[]
}

/**
 * lokasi_gudang findMany
 */
export type lokasi_gudangFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the lokasi_gudang
   */
  select?: Prisma.lokasi_gudangSelect<ExtArgs> | null
  /**
   * Omit specific fields from the lokasi_gudang
   */
  omit?: Prisma.lokasi_gudangOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.lokasi_gudangInclude<ExtArgs> | null
  /**
   * Filter, which lokasi_gudangs to fetch.
   */
  where?: Prisma.lokasi_gudangWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of lokasi_gudangs to fetch.
   */
  orderBy?: Prisma.lokasi_gudangOrderByWithRelationInput | Prisma.lokasi_gudangOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing lokasi_gudangs.
   */
  cursor?: Prisma.lokasi_gudangWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` lokasi_gudangs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` lokasi_gudangs.
   */
  skip?: number
  distinct?: Prisma.Lokasi_gudangScalarFieldEnum | Prisma.Lokasi_gudangScalarFieldEnum[]
}

/**
 * lokasi_gudang create
 */
export type lokasi_gudangCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the lokasi_gudang
   */
  select?: Prisma.lokasi_gudangSelect<ExtArgs> | null
  /**
   * Omit specific fields from the lokasi_gudang
   */
  omit?: Prisma.lokasi_gudangOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.lokasi_gudangInclude<ExtArgs> | null
  /**
   * The data needed to create a lokasi_gudang.
   */
  data: Prisma.XOR<Prisma.lokasi_gudangCreateInput, Prisma.lokasi_gudangUncheckedCreateInput>
}

/**
 * lokasi_gudang createMany
 */
export type lokasi_gudangCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many lokasi_gudangs.
   */
  data: Prisma.lokasi_gudangCreateManyInput | Prisma.lokasi_gudangCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * lokasi_gudang createManyAndReturn
 */
export type lokasi_gudangCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the lokasi_gudang
   */
  select?: Prisma.lokasi_gudangSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the lokasi_gudang
   */
  omit?: Prisma.lokasi_gudangOmit<ExtArgs> | null
  /**
   * The data used to create many lokasi_gudangs.
   */
  data: Prisma.lokasi_gudangCreateManyInput | Prisma.lokasi_gudangCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * lokasi_gudang update
 */
export type lokasi_gudangUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the lokasi_gudang
   */
  select?: Prisma.lokasi_gudangSelect<ExtArgs> | null
  /**
   * Omit specific fields from the lokasi_gudang
   */
  omit?: Prisma.lokasi_gudangOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.lokasi_gudangInclude<ExtArgs> | null
  /**
   * The data needed to update a lokasi_gudang.
   */
  data: Prisma.XOR<Prisma.lokasi_gudangUpdateInput, Prisma.lokasi_gudangUncheckedUpdateInput>
  /**
   * Choose, which lokasi_gudang to update.
   */
  where: Prisma.lokasi_gudangWhereUniqueInput
}

/**
 * lokasi_gudang updateMany
 */
export type lokasi_gudangUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update lokasi_gudangs.
   */
  data: Prisma.XOR<Prisma.lokasi_gudangUpdateManyMutationInput, Prisma.lokasi_gudangUncheckedUpdateManyInput>
  /**
   * Filter which lokasi_gudangs to update
   */
  where?: Prisma.lokasi_gudangWhereInput
  /**
   * Limit how many lokasi_gudangs to update.
   */
  limit?: number
}

/**
 * lokasi_gudang updateManyAndReturn
 */
export type lokasi_gudangUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the lokasi_gudang
   */
  select?: Prisma.lokasi_gudangSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the lokasi_gudang
   */
  omit?: Prisma.lokasi_gudangOmit<ExtArgs> | null
  /**
   * The data used to update lokasi_gudangs.
   */
  data: Prisma.XOR<Prisma.lokasi_gudangUpdateManyMutationInput, Prisma.lokasi_gudangUncheckedUpdateManyInput>
  /**
   * Filter which lokasi_gudangs to update
   */
  where?: Prisma.lokasi_gudangWhereInput
  /**
   * Limit how many lokasi_gudangs to update.
   */
  limit?: number
}

/**
 * lokasi_gudang upsert
 */
export type lokasi_gudangUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the lokasi_gudang
   */
  select?: Prisma.lokasi_gudangSelect<ExtArgs> | null
  /**
   * Omit specific fields from the lokasi_gudang
   */
  omit?: Prisma.lokasi_gudangOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.lokasi_gudangInclude<ExtArgs> | null
  /**
   * The filter to search for the lokasi_gudang to update in case it exists.
   */
  where: Prisma.lokasi_gudangWhereUniqueInput
  /**
   * In case the lokasi_gudang found by the `where` argument doesn't exist, create a new lokasi_gudang with this data.
   */
  create: Prisma.XOR<Prisma.lokasi_gudangCreateInput, Prisma.lokasi_gudangUncheckedCreateInput>
  /**
   * In case the lokasi_gudang was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.lokasi_gudangUpdateInput, Prisma.lokasi_gudangUncheckedUpdateInput>
}

/**
 * lokasi_gudang delete
 */
export type lokasi_gudangDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the lokasi_gudang
   */
  select?: Prisma.lokasi_gudangSelect<ExtArgs> | null
  /**
   * Omit specific fields from the lokasi_gudang
   */
  omit?: Prisma.lokasi_gudangOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.lokasi_gudangInclude<ExtArgs> | null
  /**
   * Filter which lokasi_gudang to delete.
   */
  where: Prisma.lokasi_gudangWhereUniqueInput
}

/**
 * lokasi_gudang deleteMany
 */
export type lokasi_gudangDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which lokasi_gudangs to delete
   */
  where?: Prisma.lokasi_gudangWhereInput
  /**
   * Limit how many lokasi_gudangs to delete.
   */
  limit?: number
}

/**
 * lokasi_gudang.produk
 */
export type lokasi_gudang$produkArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the produk
   */
  select?: Prisma.produkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the produk
   */
  omit?: Prisma.produkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.produkInclude<ExtArgs> | null
  where?: Prisma.produkWhereInput
  orderBy?: Prisma.produkOrderByWithRelationInput | Prisma.produkOrderByWithRelationInput[]
  cursor?: Prisma.produkWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ProdukScalarFieldEnum | Prisma.ProdukScalarFieldEnum[]
}

/**
 * lokasi_gudang without action
 */
export type lokasi_gudangDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the lokasi_gudang
   */
  select?: Prisma.lokasi_gudangSelect<ExtArgs> | null
  /**
   * Omit specific fields from the lokasi_gudang
   */
  omit?: Prisma.lokasi_gudangOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.lokasi_gudangInclude<ExtArgs> | null
}
