
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `produk` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model produk
 * 
 */
export type produkModel = runtime.Types.Result.DefaultSelection<Prisma.$produkPayload>

export type AggregateProduk = {
  _count: ProdukCountAggregateOutputType | null
  _avg: ProdukAvgAggregateOutputType | null
  _sum: ProdukSumAggregateOutputType | null
  _min: ProdukMinAggregateOutputType | null
  _max: ProdukMaxAggregateOutputType | null
}

export type ProdukAvgAggregateOutputType = {
  id: number | null
  kategoriId: number | null
  vendorsId: number | null
  jumlah: number | null
  lokasiId: number | null
}

export type ProdukSumAggregateOutputType = {
  id: number | null
  kategoriId: number | null
  vendorsId: number | null
  jumlah: number | null
  lokasiId: number | null
}

export type ProdukMinAggregateOutputType = {
  id: number | null
  nama_produk: string | null
  kategoriId: number | null
  vendorsId: number | null
  jumlah: number | null
  lokasiId: number | null
}

export type ProdukMaxAggregateOutputType = {
  id: number | null
  nama_produk: string | null
  kategoriId: number | null
  vendorsId: number | null
  jumlah: number | null
  lokasiId: number | null
}

export type ProdukCountAggregateOutputType = {
  id: number
  nama_produk: number
  kategoriId: number
  vendorsId: number
  jumlah: number
  lokasiId: number
  _all: number
}


export type ProdukAvgAggregateInputType = {
  id?: true
  kategoriId?: true
  vendorsId?: true
  jumlah?: true
  lokasiId?: true
}

export type ProdukSumAggregateInputType = {
  id?: true
  kategoriId?: true
  vendorsId?: true
  jumlah?: true
  lokasiId?: true
}

export type ProdukMinAggregateInputType = {
  id?: true
  nama_produk?: true
  kategoriId?: true
  vendorsId?: true
  jumlah?: true
  lokasiId?: true
}

export type ProdukMaxAggregateInputType = {
  id?: true
  nama_produk?: true
  kategoriId?: true
  vendorsId?: true
  jumlah?: true
  lokasiId?: true
}

export type ProdukCountAggregateInputType = {
  id?: true
  nama_produk?: true
  kategoriId?: true
  vendorsId?: true
  jumlah?: true
  lokasiId?: true
  _all?: true
}

export type ProdukAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which produk to aggregate.
   */
  where?: Prisma.produkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of produks to fetch.
   */
  orderBy?: Prisma.produkOrderByWithRelationInput | Prisma.produkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.produkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` produks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` produks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned produks
  **/
  _count?: true | ProdukCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ProdukAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ProdukSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ProdukMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ProdukMaxAggregateInputType
}

export type GetProdukAggregateType<T extends ProdukAggregateArgs> = {
      [P in keyof T & keyof AggregateProduk]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProduk[P]>
    : Prisma.GetScalarType<T[P], AggregateProduk[P]>
}




export type produkGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.produkWhereInput
  orderBy?: Prisma.produkOrderByWithAggregationInput | Prisma.produkOrderByWithAggregationInput[]
  by: Prisma.ProdukScalarFieldEnum[] | Prisma.ProdukScalarFieldEnum
  having?: Prisma.produkScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ProdukCountAggregateInputType | true
  _avg?: ProdukAvgAggregateInputType
  _sum?: ProdukSumAggregateInputType
  _min?: ProdukMinAggregateInputType
  _max?: ProdukMaxAggregateInputType
}

export type ProdukGroupByOutputType = {
  id: number
  nama_produk: string
  kategoriId: number
  vendorsId: number
  jumlah: number
  lokasiId: number
  _count: ProdukCountAggregateOutputType | null
  _avg: ProdukAvgAggregateOutputType | null
  _sum: ProdukSumAggregateOutputType | null
  _min: ProdukMinAggregateOutputType | null
  _max: ProdukMaxAggregateOutputType | null
}

type GetProdukGroupByPayload<T extends produkGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ProdukGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ProdukGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ProdukGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ProdukGroupByOutputType[P]>
      }
    >
  >



export type produkWhereInput = {
  AND?: Prisma.produkWhereInput | Prisma.produkWhereInput[]
  OR?: Prisma.produkWhereInput[]
  NOT?: Prisma.produkWhereInput | Prisma.produkWhereInput[]
  id?: Prisma.IntFilter<"produk"> | number
  nama_produk?: Prisma.StringFilter<"produk"> | string
  kategoriId?: Prisma.IntFilter<"produk"> | number
  vendorsId?: Prisma.IntFilter<"produk"> | number
  jumlah?: Prisma.IntFilter<"produk"> | number
  lokasiId?: Prisma.IntFilter<"produk"> | number
  kategori?: Prisma.XOR<Prisma.CategoryScalarRelationFilter, Prisma.categoryWhereInput>
  vendors?: Prisma.XOR<Prisma.VendorsScalarRelationFilter, Prisma.vendorsWhereInput>
  lokasi?: Prisma.XOR<Prisma.Lokasi_gudangScalarRelationFilter, Prisma.lokasi_gudangWhereInput>
  inbound?: Prisma.Barang_masukListRelationFilter
  outbound?: Prisma.Barang_keluarListRelationFilter
}

export type produkOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  nama_produk?: Prisma.SortOrder
  kategoriId?: Prisma.SortOrder
  vendorsId?: Prisma.SortOrder
  jumlah?: Prisma.SortOrder
  lokasiId?: Prisma.SortOrder
  kategori?: Prisma.categoryOrderByWithRelationInput
  vendors?: Prisma.vendorsOrderByWithRelationInput
  lokasi?: Prisma.lokasi_gudangOrderByWithRelationInput
  inbound?: Prisma.barang_masukOrderByRelationAggregateInput
  outbound?: Prisma.barang_keluarOrderByRelationAggregateInput
}

export type produkWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.produkWhereInput | Prisma.produkWhereInput[]
  OR?: Prisma.produkWhereInput[]
  NOT?: Prisma.produkWhereInput | Prisma.produkWhereInput[]
  nama_produk?: Prisma.StringFilter<"produk"> | string
  kategoriId?: Prisma.IntFilter<"produk"> | number
  vendorsId?: Prisma.IntFilter<"produk"> | number
  jumlah?: Prisma.IntFilter<"produk"> | number
  lokasiId?: Prisma.IntFilter<"produk"> | number
  kategori?: Prisma.XOR<Prisma.CategoryScalarRelationFilter, Prisma.categoryWhereInput>
  vendors?: Prisma.XOR<Prisma.VendorsScalarRelationFilter, Prisma.vendorsWhereInput>
  lokasi?: Prisma.XOR<Prisma.Lokasi_gudangScalarRelationFilter, Prisma.lokasi_gudangWhereInput>
  inbound?: Prisma.Barang_masukListRelationFilter
  outbound?: Prisma.Barang_keluarListRelationFilter
}, "id">

export type produkOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  nama_produk?: Prisma.SortOrder
  kategoriId?: Prisma.SortOrder
  vendorsId?: Prisma.SortOrder
  jumlah?: Prisma.SortOrder
  lokasiId?: Prisma.SortOrder
  _count?: Prisma.produkCountOrderByAggregateInput
  _avg?: Prisma.produkAvgOrderByAggregateInput
  _max?: Prisma.produkMaxOrderByAggregateInput
  _min?: Prisma.produkMinOrderByAggregateInput
  _sum?: Prisma.produkSumOrderByAggregateInput
}

export type produkScalarWhereWithAggregatesInput = {
  AND?: Prisma.produkScalarWhereWithAggregatesInput | Prisma.produkScalarWhereWithAggregatesInput[]
  OR?: Prisma.produkScalarWhereWithAggregatesInput[]
  NOT?: Prisma.produkScalarWhereWithAggregatesInput | Prisma.produkScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"produk"> | number
  nama_produk?: Prisma.StringWithAggregatesFilter<"produk"> | string
  kategoriId?: Prisma.IntWithAggregatesFilter<"produk"> | number
  vendorsId?: Prisma.IntWithAggregatesFilter<"produk"> | number
  jumlah?: Prisma.IntWithAggregatesFilter<"produk"> | number
  lokasiId?: Prisma.IntWithAggregatesFilter<"produk"> | number
}

export type produkCreateInput = {
  nama_produk: string
  jumlah?: number
  kategori: Prisma.categoryCreateNestedOneWithoutProdukInput
  vendors: Prisma.vendorsCreateNestedOneWithoutProdukInput
  lokasi: Prisma.lokasi_gudangCreateNestedOneWithoutProdukInput
  inbound?: Prisma.barang_masukCreateNestedManyWithoutProdukInput
  outbound?: Prisma.barang_keluarCreateNestedManyWithoutProdukInput
}

export type produkUncheckedCreateInput = {
  id?: number
  nama_produk: string
  kategoriId: number
  vendorsId: number
  jumlah?: number
  lokasiId: number
  inbound?: Prisma.barang_masukUncheckedCreateNestedManyWithoutProdukInput
  outbound?: Prisma.barang_keluarUncheckedCreateNestedManyWithoutProdukInput
}

export type produkUpdateInput = {
  nama_produk?: Prisma.StringFieldUpdateOperationsInput | string
  jumlah?: Prisma.IntFieldUpdateOperationsInput | number
  kategori?: Prisma.categoryUpdateOneRequiredWithoutProdukNestedInput
  vendors?: Prisma.vendorsUpdateOneRequiredWithoutProdukNestedInput
  lokasi?: Prisma.lokasi_gudangUpdateOneRequiredWithoutProdukNestedInput
  inbound?: Prisma.barang_masukUpdateManyWithoutProdukNestedInput
  outbound?: Prisma.barang_keluarUpdateManyWithoutProdukNestedInput
}

export type produkUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  nama_produk?: Prisma.StringFieldUpdateOperationsInput | string
  kategoriId?: Prisma.IntFieldUpdateOperationsInput | number
  vendorsId?: Prisma.IntFieldUpdateOperationsInput | number
  jumlah?: Prisma.IntFieldUpdateOperationsInput | number
  lokasiId?: Prisma.IntFieldUpdateOperationsInput | number
  inbound?: Prisma.barang_masukUncheckedUpdateManyWithoutProdukNestedInput
  outbound?: Prisma.barang_keluarUncheckedUpdateManyWithoutProdukNestedInput
}

export type produkCreateManyInput = {
  id?: number
  nama_produk: string
  kategoriId: number
  vendorsId: number
  jumlah?: number
  lokasiId: number
}

export type produkUpdateManyMutationInput = {
  nama_produk?: Prisma.StringFieldUpdateOperationsInput | string
  jumlah?: Prisma.IntFieldUpdateOperationsInput | number
}

export type produkUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  nama_produk?: Prisma.StringFieldUpdateOperationsInput | string
  kategoriId?: Prisma.IntFieldUpdateOperationsInput | number
  vendorsId?: Prisma.IntFieldUpdateOperationsInput | number
  jumlah?: Prisma.IntFieldUpdateOperationsInput | number
  lokasiId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type ProdukListRelationFilter = {
  every?: Prisma.produkWhereInput
  some?: Prisma.produkWhereInput
  none?: Prisma.produkWhereInput
}

export type produkOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type produkCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nama_produk?: Prisma.SortOrder
  kategoriId?: Prisma.SortOrder
  vendorsId?: Prisma.SortOrder
  jumlah?: Prisma.SortOrder
  lokasiId?: Prisma.SortOrder
}

export type produkAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  kategoriId?: Prisma.SortOrder
  vendorsId?: Prisma.SortOrder
  jumlah?: Prisma.SortOrder
  lokasiId?: Prisma.SortOrder
}

export type produkMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nama_produk?: Prisma.SortOrder
  kategoriId?: Prisma.SortOrder
  vendorsId?: Prisma.SortOrder
  jumlah?: Prisma.SortOrder
  lokasiId?: Prisma.SortOrder
}

export type produkMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nama_produk?: Prisma.SortOrder
  kategoriId?: Prisma.SortOrder
  vendorsId?: Prisma.SortOrder
  jumlah?: Prisma.SortOrder
  lokasiId?: Prisma.SortOrder
}

export type produkSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  kategoriId?: Prisma.SortOrder
  vendorsId?: Prisma.SortOrder
  jumlah?: Prisma.SortOrder
  lokasiId?: Prisma.SortOrder
}

export type ProdukScalarRelationFilter = {
  is?: Prisma.produkWhereInput
  isNot?: Prisma.produkWhereInput
}

export type produkCreateNestedManyWithoutVendorsInput = {
  create?: Prisma.XOR<Prisma.produkCreateWithoutVendorsInput, Prisma.produkUncheckedCreateWithoutVendorsInput> | Prisma.produkCreateWithoutVendorsInput[] | Prisma.produkUncheckedCreateWithoutVendorsInput[]
  connectOrCreate?: Prisma.produkCreateOrConnectWithoutVendorsInput | Prisma.produkCreateOrConnectWithoutVendorsInput[]
  createMany?: Prisma.produkCreateManyVendorsInputEnvelope
  connect?: Prisma.produkWhereUniqueInput | Prisma.produkWhereUniqueInput[]
}

export type produkUncheckedCreateNestedManyWithoutVendorsInput = {
  create?: Prisma.XOR<Prisma.produkCreateWithoutVendorsInput, Prisma.produkUncheckedCreateWithoutVendorsInput> | Prisma.produkCreateWithoutVendorsInput[] | Prisma.produkUncheckedCreateWithoutVendorsInput[]
  connectOrCreate?: Prisma.produkCreateOrConnectWithoutVendorsInput | Prisma.produkCreateOrConnectWithoutVendorsInput[]
  createMany?: Prisma.produkCreateManyVendorsInputEnvelope
  connect?: Prisma.produkWhereUniqueInput | Prisma.produkWhereUniqueInput[]
}

export type produkUpdateManyWithoutVendorsNestedInput = {
  create?: Prisma.XOR<Prisma.produkCreateWithoutVendorsInput, Prisma.produkUncheckedCreateWithoutVendorsInput> | Prisma.produkCreateWithoutVendorsInput[] | Prisma.produkUncheckedCreateWithoutVendorsInput[]
  connectOrCreate?: Prisma.produkCreateOrConnectWithoutVendorsInput | Prisma.produkCreateOrConnectWithoutVendorsInput[]
  upsert?: Prisma.produkUpsertWithWhereUniqueWithoutVendorsInput | Prisma.produkUpsertWithWhereUniqueWithoutVendorsInput[]
  createMany?: Prisma.produkCreateManyVendorsInputEnvelope
  set?: Prisma.produkWhereUniqueInput | Prisma.produkWhereUniqueInput[]
  disconnect?: Prisma.produkWhereUniqueInput | Prisma.produkWhereUniqueInput[]
  delete?: Prisma.produkWhereUniqueInput | Prisma.produkWhereUniqueInput[]
  connect?: Prisma.produkWhereUniqueInput | Prisma.produkWhereUniqueInput[]
  update?: Prisma.produkUpdateWithWhereUniqueWithoutVendorsInput | Prisma.produkUpdateWithWhereUniqueWithoutVendorsInput[]
  updateMany?: Prisma.produkUpdateManyWithWhereWithoutVendorsInput | Prisma.produkUpdateManyWithWhereWithoutVendorsInput[]
  deleteMany?: Prisma.produkScalarWhereInput | Prisma.produkScalarWhereInput[]
}

export type produkUncheckedUpdateManyWithoutVendorsNestedInput = {
  create?: Prisma.XOR<Prisma.produkCreateWithoutVendorsInput, Prisma.produkUncheckedCreateWithoutVendorsInput> | Prisma.produkCreateWithoutVendorsInput[] | Prisma.produkUncheckedCreateWithoutVendorsInput[]
  connectOrCreate?: Prisma.produkCreateOrConnectWithoutVendorsInput | Prisma.produkCreateOrConnectWithoutVendorsInput[]
  upsert?: Prisma.produkUpsertWithWhereUniqueWithoutVendorsInput | Prisma.produkUpsertWithWhereUniqueWithoutVendorsInput[]
  createMany?: Prisma.produkCreateManyVendorsInputEnvelope
  set?: Prisma.produkWhereUniqueInput | Prisma.produkWhereUniqueInput[]
  disconnect?: Prisma.produkWhereUniqueInput | Prisma.produkWhereUniqueInput[]
  delete?: Prisma.produkWhereUniqueInput | Prisma.produkWhereUniqueInput[]
  connect?: Prisma.produkWhereUniqueInput | Prisma.produkWhereUniqueInput[]
  update?: Prisma.produkUpdateWithWhereUniqueWithoutVendorsInput | Prisma.produkUpdateWithWhereUniqueWithoutVendorsInput[]
  updateMany?: Prisma.produkUpdateManyWithWhereWithoutVendorsInput | Prisma.produkUpdateManyWithWhereWithoutVendorsInput[]
  deleteMany?: Prisma.produkScalarWhereInput | Prisma.produkScalarWhereInput[]
}

export type produkCreateNestedManyWithoutKategoriInput = {
  create?: Prisma.XOR<Prisma.produkCreateWithoutKategoriInput, Prisma.produkUncheckedCreateWithoutKategoriInput> | Prisma.produkCreateWithoutKategoriInput[] | Prisma.produkUncheckedCreateWithoutKategoriInput[]
  connectOrCreate?: Prisma.produkCreateOrConnectWithoutKategoriInput | Prisma.produkCreateOrConnectWithoutKategoriInput[]
  createMany?: Prisma.produkCreateManyKategoriInputEnvelope
  connect?: Prisma.produkWhereUniqueInput | Prisma.produkWhereUniqueInput[]
}

export type produkUncheckedCreateNestedManyWithoutKategoriInput = {
  create?: Prisma.XOR<Prisma.produkCreateWithoutKategoriInput, Prisma.produkUncheckedCreateWithoutKategoriInput> | Prisma.produkCreateWithoutKategoriInput[] | Prisma.produkUncheckedCreateWithoutKategoriInput[]
  connectOrCreate?: Prisma.produkCreateOrConnectWithoutKategoriInput | Prisma.produkCreateOrConnectWithoutKategoriInput[]
  createMany?: Prisma.produkCreateManyKategoriInputEnvelope
  connect?: Prisma.produkWhereUniqueInput | Prisma.produkWhereUniqueInput[]
}

export type produkUpdateManyWithoutKategoriNestedInput = {
  create?: Prisma.XOR<Prisma.produkCreateWithoutKategoriInput, Prisma.produkUncheckedCreateWithoutKategoriInput> | Prisma.produkCreateWithoutKategoriInput[] | Prisma.produkUncheckedCreateWithoutKategoriInput[]
  connectOrCreate?: Prisma.produkCreateOrConnectWithoutKategoriInput | Prisma.produkCreateOrConnectWithoutKategoriInput[]
  upsert?: Prisma.produkUpsertWithWhereUniqueWithoutKategoriInput | Prisma.produkUpsertWithWhereUniqueWithoutKategoriInput[]
  createMany?: Prisma.produkCreateManyKategoriInputEnvelope
  set?: Prisma.produkWhereUniqueInput | Prisma.produkWhereUniqueInput[]
  disconnect?: Prisma.produkWhereUniqueInput | Prisma.produkWhereUniqueInput[]
  delete?: Prisma.produkWhereUniqueInput | Prisma.produkWhereUniqueInput[]
  connect?: Prisma.produkWhereUniqueInput | Prisma.produkWhereUniqueInput[]
  update?: Prisma.produkUpdateWithWhereUniqueWithoutKategoriInput | Prisma.produkUpdateWithWhereUniqueWithoutKategoriInput[]
  updateMany?: Prisma.produkUpdateManyWithWhereWithoutKategoriInput | Prisma.produkUpdateManyWithWhereWithoutKategoriInput[]
  deleteMany?: Prisma.produkScalarWhereInput | Prisma.produkScalarWhereInput[]
}

export type produkUncheckedUpdateManyWithoutKategoriNestedInput = {
  create?: Prisma.XOR<Prisma.produkCreateWithoutKategoriInput, Prisma.produkUncheckedCreateWithoutKategoriInput> | Prisma.produkCreateWithoutKategoriInput[] | Prisma.produkUncheckedCreateWithoutKategoriInput[]
  connectOrCreate?: Prisma.produkCreateOrConnectWithoutKategoriInput | Prisma.produkCreateOrConnectWithoutKategoriInput[]
  upsert?: Prisma.produkUpsertWithWhereUniqueWithoutKategoriInput | Prisma.produkUpsertWithWhereUniqueWithoutKategoriInput[]
  createMany?: Prisma.produkCreateManyKategoriInputEnvelope
  set?: Prisma.produkWhereUniqueInput | Prisma.produkWhereUniqueInput[]
  disconnect?: Prisma.produkWhereUniqueInput | Prisma.produkWhereUniqueInput[]
  delete?: Prisma.produkWhereUniqueInput | Prisma.produkWhereUniqueInput[]
  connect?: Prisma.produkWhereUniqueInput | Prisma.produkWhereUniqueInput[]
  update?: Prisma.produkUpdateWithWhereUniqueWithoutKategoriInput | Prisma.produkUpdateWithWhereUniqueWithoutKategoriInput[]
  updateMany?: Prisma.produkUpdateManyWithWhereWithoutKategoriInput | Prisma.produkUpdateManyWithWhereWithoutKategoriInput[]
  deleteMany?: Prisma.produkScalarWhereInput | Prisma.produkScalarWhereInput[]
}

export type produkCreateNestedManyWithoutLokasiInput = {
  create?: Prisma.XOR<Prisma.produkCreateWithoutLokasiInput, Prisma.produkUncheckedCreateWithoutLokasiInput> | Prisma.produkCreateWithoutLokasiInput[] | Prisma.produkUncheckedCreateWithoutLokasiInput[]
  connectOrCreate?: Prisma.produkCreateOrConnectWithoutLokasiInput | Prisma.produkCreateOrConnectWithoutLokasiInput[]
  createMany?: Prisma.produkCreateManyLokasiInputEnvelope
  connect?: Prisma.produkWhereUniqueInput | Prisma.produkWhereUniqueInput[]
}

export type produkUncheckedCreateNestedManyWithoutLokasiInput = {
  create?: Prisma.XOR<Prisma.produkCreateWithoutLokasiInput, Prisma.produkUncheckedCreateWithoutLokasiInput> | Prisma.produkCreateWithoutLokasiInput[] | Prisma.produkUncheckedCreateWithoutLokasiInput[]
  connectOrCreate?: Prisma.produkCreateOrConnectWithoutLokasiInput | Prisma.produkCreateOrConnectWithoutLokasiInput[]
  createMany?: Prisma.produkCreateManyLokasiInputEnvelope
  connect?: Prisma.produkWhereUniqueInput | Prisma.produkWhereUniqueInput[]
}

export type produkUpdateManyWithoutLokasiNestedInput = {
  create?: Prisma.XOR<Prisma.produkCreateWithoutLokasiInput, Prisma.produkUncheckedCreateWithoutLokasiInput> | Prisma.produkCreateWithoutLokasiInput[] | Prisma.produkUncheckedCreateWithoutLokasiInput[]
  connectOrCreate?: Prisma.produkCreateOrConnectWithoutLokasiInput | Prisma.produkCreateOrConnectWithoutLokasiInput[]
  upsert?: Prisma.produkUpsertWithWhereUniqueWithoutLokasiInput | Prisma.produkUpsertWithWhereUniqueWithoutLokasiInput[]
  createMany?: Prisma.produkCreateManyLokasiInputEnvelope
  set?: Prisma.produkWhereUniqueInput | Prisma.produkWhereUniqueInput[]
  disconnect?: Prisma.produkWhereUniqueInput | Prisma.produkWhereUniqueInput[]
  delete?: Prisma.produkWhereUniqueInput | Prisma.produkWhereUniqueInput[]
  connect?: Prisma.produkWhereUniqueInput | Prisma.produkWhereUniqueInput[]
  update?: Prisma.produkUpdateWithWhereUniqueWithoutLokasiInput | Prisma.produkUpdateWithWhereUniqueWithoutLokasiInput[]
  updateMany?: Prisma.produkUpdateManyWithWhereWithoutLokasiInput | Prisma.produkUpdateManyWithWhereWithoutLokasiInput[]
  deleteMany?: Prisma.produkScalarWhereInput | Prisma.produkScalarWhereInput[]
}

export type produkUncheckedUpdateManyWithoutLokasiNestedInput = {
  create?: Prisma.XOR<Prisma.produkCreateWithoutLokasiInput, Prisma.produkUncheckedCreateWithoutLokasiInput> | Prisma.produkCreateWithoutLokasiInput[] | Prisma.produkUncheckedCreateWithoutLokasiInput[]
  connectOrCreate?: Prisma.produkCreateOrConnectWithoutLokasiInput | Prisma.produkCreateOrConnectWithoutLokasiInput[]
  upsert?: Prisma.produkUpsertWithWhereUniqueWithoutLokasiInput | Prisma.produkUpsertWithWhereUniqueWithoutLokasiInput[]
  createMany?: Prisma.produkCreateManyLokasiInputEnvelope
  set?: Prisma.produkWhereUniqueInput | Prisma.produkWhereUniqueInput[]
  disconnect?: Prisma.produkWhereUniqueInput | Prisma.produkWhereUniqueInput[]
  delete?: Prisma.produkWhereUniqueInput | Prisma.produkWhereUniqueInput[]
  connect?: Prisma.produkWhereUniqueInput | Prisma.produkWhereUniqueInput[]
  update?: Prisma.produkUpdateWithWhereUniqueWithoutLokasiInput | Prisma.produkUpdateWithWhereUniqueWithoutLokasiInput[]
  updateMany?: Prisma.produkUpdateManyWithWhereWithoutLokasiInput | Prisma.produkUpdateManyWithWhereWithoutLokasiInput[]
  deleteMany?: Prisma.produkScalarWhereInput | Prisma.produkScalarWhereInput[]
}

export type produkCreateNestedOneWithoutInboundInput = {
  create?: Prisma.XOR<Prisma.produkCreateWithoutInboundInput, Prisma.produkUncheckedCreateWithoutInboundInput>
  connectOrCreate?: Prisma.produkCreateOrConnectWithoutInboundInput
  connect?: Prisma.produkWhereUniqueInput
}

export type produkUpdateOneRequiredWithoutInboundNestedInput = {
  create?: Prisma.XOR<Prisma.produkCreateWithoutInboundInput, Prisma.produkUncheckedCreateWithoutInboundInput>
  connectOrCreate?: Prisma.produkCreateOrConnectWithoutInboundInput
  upsert?: Prisma.produkUpsertWithoutInboundInput
  connect?: Prisma.produkWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.produkUpdateToOneWithWhereWithoutInboundInput, Prisma.produkUpdateWithoutInboundInput>, Prisma.produkUncheckedUpdateWithoutInboundInput>
}

export type produkCreateNestedOneWithoutOutboundInput = {
  create?: Prisma.XOR<Prisma.produkCreateWithoutOutboundInput, Prisma.produkUncheckedCreateWithoutOutboundInput>
  connectOrCreate?: Prisma.produkCreateOrConnectWithoutOutboundInput
  connect?: Prisma.produkWhereUniqueInput
}

export type produkUpdateOneRequiredWithoutOutboundNestedInput = {
  create?: Prisma.XOR<Prisma.produkCreateWithoutOutboundInput, Prisma.produkUncheckedCreateWithoutOutboundInput>
  connectOrCreate?: Prisma.produkCreateOrConnectWithoutOutboundInput
  upsert?: Prisma.produkUpsertWithoutOutboundInput
  connect?: Prisma.produkWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.produkUpdateToOneWithWhereWithoutOutboundInput, Prisma.produkUpdateWithoutOutboundInput>, Prisma.produkUncheckedUpdateWithoutOutboundInput>
}

export type produkCreateWithoutVendorsInput = {
  nama_produk: string
  jumlah?: number
  kategori: Prisma.categoryCreateNestedOneWithoutProdukInput
  lokasi: Prisma.lokasi_gudangCreateNestedOneWithoutProdukInput
  inbound?: Prisma.barang_masukCreateNestedManyWithoutProdukInput
  outbound?: Prisma.barang_keluarCreateNestedManyWithoutProdukInput
}

export type produkUncheckedCreateWithoutVendorsInput = {
  id?: number
  nama_produk: string
  kategoriId: number
  jumlah?: number
  lokasiId: number
  inbound?: Prisma.barang_masukUncheckedCreateNestedManyWithoutProdukInput
  outbound?: Prisma.barang_keluarUncheckedCreateNestedManyWithoutProdukInput
}

export type produkCreateOrConnectWithoutVendorsInput = {
  where: Prisma.produkWhereUniqueInput
  create: Prisma.XOR<Prisma.produkCreateWithoutVendorsInput, Prisma.produkUncheckedCreateWithoutVendorsInput>
}

export type produkCreateManyVendorsInputEnvelope = {
  data: Prisma.produkCreateManyVendorsInput | Prisma.produkCreateManyVendorsInput[]
  skipDuplicates?: boolean
}

export type produkUpsertWithWhereUniqueWithoutVendorsInput = {
  where: Prisma.produkWhereUniqueInput
  update: Prisma.XOR<Prisma.produkUpdateWithoutVendorsInput, Prisma.produkUncheckedUpdateWithoutVendorsInput>
  create: Prisma.XOR<Prisma.produkCreateWithoutVendorsInput, Prisma.produkUncheckedCreateWithoutVendorsInput>
}

export type produkUpdateWithWhereUniqueWithoutVendorsInput = {
  where: Prisma.produkWhereUniqueInput
  data: Prisma.XOR<Prisma.produkUpdateWithoutVendorsInput, Prisma.produkUncheckedUpdateWithoutVendorsInput>
}

export type produkUpdateManyWithWhereWithoutVendorsInput = {
  where: Prisma.produkScalarWhereInput
  data: Prisma.XOR<Prisma.produkUpdateManyMutationInput, Prisma.produkUncheckedUpdateManyWithoutVendorsInput>
}

export type produkScalarWhereInput = {
  AND?: Prisma.produkScalarWhereInput | Prisma.produkScalarWhereInput[]
  OR?: Prisma.produkScalarWhereInput[]
  NOT?: Prisma.produkScalarWhereInput | Prisma.produkScalarWhereInput[]
  id?: Prisma.IntFilter<"produk"> | number
  nama_produk?: Prisma.StringFilter<"produk"> | string
  kategoriId?: Prisma.IntFilter<"produk"> | number
  vendorsId?: Prisma.IntFilter<"produk"> | number
  jumlah?: Prisma.IntFilter<"produk"> | number
  lokasiId?: Prisma.IntFilter<"produk"> | number
}

export type produkCreateWithoutKategoriInput = {
  nama_produk: string
  jumlah?: number
  vendors: Prisma.vendorsCreateNestedOneWithoutProdukInput
  lokasi: Prisma.lokasi_gudangCreateNestedOneWithoutProdukInput
  inbound?: Prisma.barang_masukCreateNestedManyWithoutProdukInput
  outbound?: Prisma.barang_keluarCreateNestedManyWithoutProdukInput
}

export type produkUncheckedCreateWithoutKategoriInput = {
  id?: number
  nama_produk: string
  vendorsId: number
  jumlah?: number
  lokasiId: number
  inbound?: Prisma.barang_masukUncheckedCreateNestedManyWithoutProdukInput
  outbound?: Prisma.barang_keluarUncheckedCreateNestedManyWithoutProdukInput
}

export type produkCreateOrConnectWithoutKategoriInput = {
  where: Prisma.produkWhereUniqueInput
  create: Prisma.XOR<Prisma.produkCreateWithoutKategoriInput, Prisma.produkUncheckedCreateWithoutKategoriInput>
}

export type produkCreateManyKategoriInputEnvelope = {
  data: Prisma.produkCreateManyKategoriInput | Prisma.produkCreateManyKategoriInput[]
  skipDuplicates?: boolean
}

export type produkUpsertWithWhereUniqueWithoutKategoriInput = {
  where: Prisma.produkWhereUniqueInput
  update: Prisma.XOR<Prisma.produkUpdateWithoutKategoriInput, Prisma.produkUncheckedUpdateWithoutKategoriInput>
  create: Prisma.XOR<Prisma.produkCreateWithoutKategoriInput, Prisma.produkUncheckedCreateWithoutKategoriInput>
}

export type produkUpdateWithWhereUniqueWithoutKategoriInput = {
  where: Prisma.produkWhereUniqueInput
  data: Prisma.XOR<Prisma.produkUpdateWithoutKategoriInput, Prisma.produkUncheckedUpdateWithoutKategoriInput>
}

export type produkUpdateManyWithWhereWithoutKategoriInput = {
  where: Prisma.produkScalarWhereInput
  data: Prisma.XOR<Prisma.produkUpdateManyMutationInput, Prisma.produkUncheckedUpdateManyWithoutKategoriInput>
}

export type produkCreateWithoutLokasiInput = {
  nama_produk: string
  jumlah?: number
  kategori: Prisma.categoryCreateNestedOneWithoutProdukInput
  vendors: Prisma.vendorsCreateNestedOneWithoutProdukInput
  inbound?: Prisma.barang_masukCreateNestedManyWithoutProdukInput
  outbound?: Prisma.barang_keluarCreateNestedManyWithoutProdukInput
}

export type produkUncheckedCreateWithoutLokasiInput = {
  id?: number
  nama_produk: string
  kategoriId: number
  vendorsId: number
  jumlah?: number
  inbound?: Prisma.barang_masukUncheckedCreateNestedManyWithoutProdukInput
  outbound?: Prisma.barang_keluarUncheckedCreateNestedManyWithoutProdukInput
}

export type produkCreateOrConnectWithoutLokasiInput = {
  where: Prisma.produkWhereUniqueInput
  create: Prisma.XOR<Prisma.produkCreateWithoutLokasiInput, Prisma.produkUncheckedCreateWithoutLokasiInput>
}

export type produkCreateManyLokasiInputEnvelope = {
  data: Prisma.produkCreateManyLokasiInput | Prisma.produkCreateManyLokasiInput[]
  skipDuplicates?: boolean
}

export type produkUpsertWithWhereUniqueWithoutLokasiInput = {
  where: Prisma.produkWhereUniqueInput
  update: Prisma.XOR<Prisma.produkUpdateWithoutLokasiInput, Prisma.produkUncheckedUpdateWithoutLokasiInput>
  create: Prisma.XOR<Prisma.produkCreateWithoutLokasiInput, Prisma.produkUncheckedCreateWithoutLokasiInput>
}

export type produkUpdateWithWhereUniqueWithoutLokasiInput = {
  where: Prisma.produkWhereUniqueInput
  data: Prisma.XOR<Prisma.produkUpdateWithoutLokasiInput, Prisma.produkUncheckedUpdateWithoutLokasiInput>
}

export type produkUpdateManyWithWhereWithoutLokasiInput = {
  where: Prisma.produkScalarWhereInput
  data: Prisma.XOR<Prisma.produkUpdateManyMutationInput, Prisma.produkUncheckedUpdateManyWithoutLokasiInput>
}

export type produkCreateWithoutInboundInput = {
  nama_produk: string
  jumlah?: number
  kategori: Prisma.categoryCreateNestedOneWithoutProdukInput
  vendors: Prisma.vendorsCreateNestedOneWithoutProdukInput
  lokasi: Prisma.lokasi_gudangCreateNestedOneWithoutProdukInput
  outbound?: Prisma.barang_keluarCreateNestedManyWithoutProdukInput
}

export type produkUncheckedCreateWithoutInboundInput = {
  id?: number
  nama_produk: string
  kategoriId: number
  vendorsId: number
  jumlah?: number
  lokasiId: number
  outbound?: Prisma.barang_keluarUncheckedCreateNestedManyWithoutProdukInput
}

export type produkCreateOrConnectWithoutInboundInput = {
  where: Prisma.produkWhereUniqueInput
  create: Prisma.XOR<Prisma.produkCreateWithoutInboundInput, Prisma.produkUncheckedCreateWithoutInboundInput>
}

export type produkUpsertWithoutInboundInput = {
  update: Prisma.XOR<Prisma.produkUpdateWithoutInboundInput, Prisma.produkUncheckedUpdateWithoutInboundInput>
  create: Prisma.XOR<Prisma.produkCreateWithoutInboundInput, Prisma.produkUncheckedCreateWithoutInboundInput>
  where?: Prisma.produkWhereInput
}

export type produkUpdateToOneWithWhereWithoutInboundInput = {
  where?: Prisma.produkWhereInput
  data: Prisma.XOR<Prisma.produkUpdateWithoutInboundInput, Prisma.produkUncheckedUpdateWithoutInboundInput>
}

export type produkUpdateWithoutInboundInput = {
  nama_produk?: Prisma.StringFieldUpdateOperationsInput | string
  jumlah?: Prisma.IntFieldUpdateOperationsInput | number
  kategori?: Prisma.categoryUpdateOneRequiredWithoutProdukNestedInput
  vendors?: Prisma.vendorsUpdateOneRequiredWithoutProdukNestedInput
  lokasi?: Prisma.lokasi_gudangUpdateOneRequiredWithoutProdukNestedInput
  outbound?: Prisma.barang_keluarUpdateManyWithoutProdukNestedInput
}

export type produkUncheckedUpdateWithoutInboundInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  nama_produk?: Prisma.StringFieldUpdateOperationsInput | string
  kategoriId?: Prisma.IntFieldUpdateOperationsInput | number
  vendorsId?: Prisma.IntFieldUpdateOperationsInput | number
  jumlah?: Prisma.IntFieldUpdateOperationsInput | number
  lokasiId?: Prisma.IntFieldUpdateOperationsInput | number
  outbound?: Prisma.barang_keluarUncheckedUpdateManyWithoutProdukNestedInput
}

export type produkCreateWithoutOutboundInput = {
  nama_produk: string
  jumlah?: number
  kategori: Prisma.categoryCreateNestedOneWithoutProdukInput
  vendors: Prisma.vendorsCreateNestedOneWithoutProdukInput
  lokasi: Prisma.lokasi_gudangCreateNestedOneWithoutProdukInput
  inbound?: Prisma.barang_masukCreateNestedManyWithoutProdukInput
}

export type produkUncheckedCreateWithoutOutboundInput = {
  id?: number
  nama_produk: string
  kategoriId: number
  vendorsId: number
  jumlah?: number
  lokasiId: number
  inbound?: Prisma.barang_masukUncheckedCreateNestedManyWithoutProdukInput
}

export type produkCreateOrConnectWithoutOutboundInput = {
  where: Prisma.produkWhereUniqueInput
  create: Prisma.XOR<Prisma.produkCreateWithoutOutboundInput, Prisma.produkUncheckedCreateWithoutOutboundInput>
}

export type produkUpsertWithoutOutboundInput = {
  update: Prisma.XOR<Prisma.produkUpdateWithoutOutboundInput, Prisma.produkUncheckedUpdateWithoutOutboundInput>
  create: Prisma.XOR<Prisma.produkCreateWithoutOutboundInput, Prisma.produkUncheckedCreateWithoutOutboundInput>
  where?: Prisma.produkWhereInput
}

export type produkUpdateToOneWithWhereWithoutOutboundInput = {
  where?: Prisma.produkWhereInput
  data: Prisma.XOR<Prisma.produkUpdateWithoutOutboundInput, Prisma.produkUncheckedUpdateWithoutOutboundInput>
}

export type produkUpdateWithoutOutboundInput = {
  nama_produk?: Prisma.StringFieldUpdateOperationsInput | string
  jumlah?: Prisma.IntFieldUpdateOperationsInput | number
  kategori?: Prisma.categoryUpdateOneRequiredWithoutProdukNestedInput
  vendors?: Prisma.vendorsUpdateOneRequiredWithoutProdukNestedInput
  lokasi?: Prisma.lokasi_gudangUpdateOneRequiredWithoutProdukNestedInput
  inbound?: Prisma.barang_masukUpdateManyWithoutProdukNestedInput
}

export type produkUncheckedUpdateWithoutOutboundInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  nama_produk?: Prisma.StringFieldUpdateOperationsInput | string
  kategoriId?: Prisma.IntFieldUpdateOperationsInput | number
  vendorsId?: Prisma.IntFieldUpdateOperationsInput | number
  jumlah?: Prisma.IntFieldUpdateOperationsInput | number
  lokasiId?: Prisma.IntFieldUpdateOperationsInput | number
  inbound?: Prisma.barang_masukUncheckedUpdateManyWithoutProdukNestedInput
}

export type produkCreateManyVendorsInput = {
  id?: number
  nama_produk: string
  kategoriId: number
  jumlah?: number
  lokasiId: number
}

export type produkUpdateWithoutVendorsInput = {
  nama_produk?: Prisma.StringFieldUpdateOperationsInput | string
  jumlah?: Prisma.IntFieldUpdateOperationsInput | number
  kategori?: Prisma.categoryUpdateOneRequiredWithoutProdukNestedInput
  lokasi?: Prisma.lokasi_gudangUpdateOneRequiredWithoutProdukNestedInput
  inbound?: Prisma.barang_masukUpdateManyWithoutProdukNestedInput
  outbound?: Prisma.barang_keluarUpdateManyWithoutProdukNestedInput
}

export type produkUncheckedUpdateWithoutVendorsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  nama_produk?: Prisma.StringFieldUpdateOperationsInput | string
  kategoriId?: Prisma.IntFieldUpdateOperationsInput | number
  jumlah?: Prisma.IntFieldUpdateOperationsInput | number
  lokasiId?: Prisma.IntFieldUpdateOperationsInput | number
  inbound?: Prisma.barang_masukUncheckedUpdateManyWithoutProdukNestedInput
  outbound?: Prisma.barang_keluarUncheckedUpdateManyWithoutProdukNestedInput
}

export type produkUncheckedUpdateManyWithoutVendorsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  nama_produk?: Prisma.StringFieldUpdateOperationsInput | string
  kategoriId?: Prisma.IntFieldUpdateOperationsInput | number
  jumlah?: Prisma.IntFieldUpdateOperationsInput | number
  lokasiId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type produkCreateManyKategoriInput = {
  id?: number
  nama_produk: string
  vendorsId: number
  jumlah?: number
  lokasiId: number
}

export type produkUpdateWithoutKategoriInput = {
  nama_produk?: Prisma.StringFieldUpdateOperationsInput | string
  jumlah?: Prisma.IntFieldUpdateOperationsInput | number
  vendors?: Prisma.vendorsUpdateOneRequiredWithoutProdukNestedInput
  lokasi?: Prisma.lokasi_gudangUpdateOneRequiredWithoutProdukNestedInput
  inbound?: Prisma.barang_masukUpdateManyWithoutProdukNestedInput
  outbound?: Prisma.barang_keluarUpdateManyWithoutProdukNestedInput
}

export type produkUncheckedUpdateWithoutKategoriInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  nama_produk?: Prisma.StringFieldUpdateOperationsInput | string
  vendorsId?: Prisma.IntFieldUpdateOperationsInput | number
  jumlah?: Prisma.IntFieldUpdateOperationsInput | number
  lokasiId?: Prisma.IntFieldUpdateOperationsInput | number
  inbound?: Prisma.barang_masukUncheckedUpdateManyWithoutProdukNestedInput
  outbound?: Prisma.barang_keluarUncheckedUpdateManyWithoutProdukNestedInput
}

export type produkUncheckedUpdateManyWithoutKategoriInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  nama_produk?: Prisma.StringFieldUpdateOperationsInput | string
  vendorsId?: Prisma.IntFieldUpdateOperationsInput | number
  jumlah?: Prisma.IntFieldUpdateOperationsInput | number
  lokasiId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type produkCreateManyLokasiInput = {
  id?: number
  nama_produk: string
  kategoriId: number
  vendorsId: number
  jumlah?: number
}

export type produkUpdateWithoutLokasiInput = {
  nama_produk?: Prisma.StringFieldUpdateOperationsInput | string
  jumlah?: Prisma.IntFieldUpdateOperationsInput | number
  kategori?: Prisma.categoryUpdateOneRequiredWithoutProdukNestedInput
  vendors?: Prisma.vendorsUpdateOneRequiredWithoutProdukNestedInput
  inbound?: Prisma.barang_masukUpdateManyWithoutProdukNestedInput
  outbound?: Prisma.barang_keluarUpdateManyWithoutProdukNestedInput
}

export type produkUncheckedUpdateWithoutLokasiInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  nama_produk?: Prisma.StringFieldUpdateOperationsInput | string
  kategoriId?: Prisma.IntFieldUpdateOperationsInput | number
  vendorsId?: Prisma.IntFieldUpdateOperationsInput | number
  jumlah?: Prisma.IntFieldUpdateOperationsInput | number
  inbound?: Prisma.barang_masukUncheckedUpdateManyWithoutProdukNestedInput
  outbound?: Prisma.barang_keluarUncheckedUpdateManyWithoutProdukNestedInput
}

export type produkUncheckedUpdateManyWithoutLokasiInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  nama_produk?: Prisma.StringFieldUpdateOperationsInput | string
  kategoriId?: Prisma.IntFieldUpdateOperationsInput | number
  vendorsId?: Prisma.IntFieldUpdateOperationsInput | number
  jumlah?: Prisma.IntFieldUpdateOperationsInput | number
}


/**
 * Count Type ProdukCountOutputType
 */

export type ProdukCountOutputType = {
  inbound: number
  outbound: number
}

export type ProdukCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  inbound?: boolean | ProdukCountOutputTypeCountInboundArgs
  outbound?: boolean | ProdukCountOutputTypeCountOutboundArgs
}

/**
 * ProdukCountOutputType without action
 */
export type ProdukCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProdukCountOutputType
   */
  select?: Prisma.ProdukCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ProdukCountOutputType without action
 */
export type ProdukCountOutputTypeCountInboundArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.barang_masukWhereInput
}

/**
 * ProdukCountOutputType without action
 */
export type ProdukCountOutputTypeCountOutboundArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.barang_keluarWhereInput
}


export type produkSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nama_produk?: boolean
  kategoriId?: boolean
  vendorsId?: boolean
  jumlah?: boolean
  lokasiId?: boolean
  kategori?: boolean | Prisma.categoryDefaultArgs<ExtArgs>
  vendors?: boolean | Prisma.vendorsDefaultArgs<ExtArgs>
  lokasi?: boolean | Prisma.lokasi_gudangDefaultArgs<ExtArgs>
  inbound?: boolean | Prisma.produk$inboundArgs<ExtArgs>
  outbound?: boolean | Prisma.produk$outboundArgs<ExtArgs>
  _count?: boolean | Prisma.ProdukCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["produk"]>

export type produkSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nama_produk?: boolean
  kategoriId?: boolean
  vendorsId?: boolean
  jumlah?: boolean
  lokasiId?: boolean
  kategori?: boolean | Prisma.categoryDefaultArgs<ExtArgs>
  vendors?: boolean | Prisma.vendorsDefaultArgs<ExtArgs>
  lokasi?: boolean | Prisma.lokasi_gudangDefaultArgs<ExtArgs>
}, ExtArgs["result"]["produk"]>

export type produkSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nama_produk?: boolean
  kategoriId?: boolean
  vendorsId?: boolean
  jumlah?: boolean
  lokasiId?: boolean
  kategori?: boolean | Prisma.categoryDefaultArgs<ExtArgs>
  vendors?: boolean | Prisma.vendorsDefaultArgs<ExtArgs>
  lokasi?: boolean | Prisma.lokasi_gudangDefaultArgs<ExtArgs>
}, ExtArgs["result"]["produk"]>

export type produkSelectScalar = {
  id?: boolean
  nama_produk?: boolean
  kategoriId?: boolean
  vendorsId?: boolean
  jumlah?: boolean
  lokasiId?: boolean
}

export type produkOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "nama_produk" | "kategoriId" | "vendorsId" | "jumlah" | "lokasiId", ExtArgs["result"]["produk"]>
export type produkInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  kategori?: boolean | Prisma.categoryDefaultArgs<ExtArgs>
  vendors?: boolean | Prisma.vendorsDefaultArgs<ExtArgs>
  lokasi?: boolean | Prisma.lokasi_gudangDefaultArgs<ExtArgs>
  inbound?: boolean | Prisma.produk$inboundArgs<ExtArgs>
  outbound?: boolean | Prisma.produk$outboundArgs<ExtArgs>
  _count?: boolean | Prisma.ProdukCountOutputTypeDefaultArgs<ExtArgs>
}
export type produkIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  kategori?: boolean | Prisma.categoryDefaultArgs<ExtArgs>
  vendors?: boolean | Prisma.vendorsDefaultArgs<ExtArgs>
  lokasi?: boolean | Prisma.lokasi_gudangDefaultArgs<ExtArgs>
}
export type produkIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  kategori?: boolean | Prisma.categoryDefaultArgs<ExtArgs>
  vendors?: boolean | Prisma.vendorsDefaultArgs<ExtArgs>
  lokasi?: boolean | Prisma.lokasi_gudangDefaultArgs<ExtArgs>
}

export type $produkPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "produk"
  objects: {
    kategori: Prisma.$categoryPayload<ExtArgs>
    vendors: Prisma.$vendorsPayload<ExtArgs>
    lokasi: Prisma.$lokasi_gudangPayload<ExtArgs>
    inbound: Prisma.$barang_masukPayload<ExtArgs>[]
    outbound: Prisma.$barang_keluarPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    nama_produk: string
    kategoriId: number
    vendorsId: number
    jumlah: number
    lokasiId: number
  }, ExtArgs["result"]["produk"]>
  composites: {}
}

export type produkGetPayload<S extends boolean | null | undefined | produkDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$produkPayload, S>

export type produkCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<produkFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ProdukCountAggregateInputType | true
  }

export interface produkDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['produk'], meta: { name: 'produk' } }
  /**
   * Find zero or one Produk that matches the filter.
   * @param {produkFindUniqueArgs} args - Arguments to find a Produk
   * @example
   * // Get one Produk
   * const produk = await prisma.produk.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends produkFindUniqueArgs>(args: Prisma.SelectSubset<T, produkFindUniqueArgs<ExtArgs>>): Prisma.Prisma__produkClient<runtime.Types.Result.GetResult<Prisma.$produkPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Produk that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {produkFindUniqueOrThrowArgs} args - Arguments to find a Produk
   * @example
   * // Get one Produk
   * const produk = await prisma.produk.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends produkFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, produkFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__produkClient<runtime.Types.Result.GetResult<Prisma.$produkPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Produk that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {produkFindFirstArgs} args - Arguments to find a Produk
   * @example
   * // Get one Produk
   * const produk = await prisma.produk.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends produkFindFirstArgs>(args?: Prisma.SelectSubset<T, produkFindFirstArgs<ExtArgs>>): Prisma.Prisma__produkClient<runtime.Types.Result.GetResult<Prisma.$produkPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Produk that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {produkFindFirstOrThrowArgs} args - Arguments to find a Produk
   * @example
   * // Get one Produk
   * const produk = await prisma.produk.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends produkFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, produkFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__produkClient<runtime.Types.Result.GetResult<Prisma.$produkPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Produks that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {produkFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Produks
   * const produks = await prisma.produk.findMany()
   * 
   * // Get first 10 Produks
   * const produks = await prisma.produk.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const produkWithIdOnly = await prisma.produk.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends produkFindManyArgs>(args?: Prisma.SelectSubset<T, produkFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$produkPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Produk.
   * @param {produkCreateArgs} args - Arguments to create a Produk.
   * @example
   * // Create one Produk
   * const Produk = await prisma.produk.create({
   *   data: {
   *     // ... data to create a Produk
   *   }
   * })
   * 
   */
  create<T extends produkCreateArgs>(args: Prisma.SelectSubset<T, produkCreateArgs<ExtArgs>>): Prisma.Prisma__produkClient<runtime.Types.Result.GetResult<Prisma.$produkPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Produks.
   * @param {produkCreateManyArgs} args - Arguments to create many Produks.
   * @example
   * // Create many Produks
   * const produk = await prisma.produk.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends produkCreateManyArgs>(args?: Prisma.SelectSubset<T, produkCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Produks and returns the data saved in the database.
   * @param {produkCreateManyAndReturnArgs} args - Arguments to create many Produks.
   * @example
   * // Create many Produks
   * const produk = await prisma.produk.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Produks and only return the `id`
   * const produkWithIdOnly = await prisma.produk.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends produkCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, produkCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$produkPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Produk.
   * @param {produkDeleteArgs} args - Arguments to delete one Produk.
   * @example
   * // Delete one Produk
   * const Produk = await prisma.produk.delete({
   *   where: {
   *     // ... filter to delete one Produk
   *   }
   * })
   * 
   */
  delete<T extends produkDeleteArgs>(args: Prisma.SelectSubset<T, produkDeleteArgs<ExtArgs>>): Prisma.Prisma__produkClient<runtime.Types.Result.GetResult<Prisma.$produkPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Produk.
   * @param {produkUpdateArgs} args - Arguments to update one Produk.
   * @example
   * // Update one Produk
   * const produk = await prisma.produk.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends produkUpdateArgs>(args: Prisma.SelectSubset<T, produkUpdateArgs<ExtArgs>>): Prisma.Prisma__produkClient<runtime.Types.Result.GetResult<Prisma.$produkPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Produks.
   * @param {produkDeleteManyArgs} args - Arguments to filter Produks to delete.
   * @example
   * // Delete a few Produks
   * const { count } = await prisma.produk.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends produkDeleteManyArgs>(args?: Prisma.SelectSubset<T, produkDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Produks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {produkUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Produks
   * const produk = await prisma.produk.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends produkUpdateManyArgs>(args: Prisma.SelectSubset<T, produkUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Produks and returns the data updated in the database.
   * @param {produkUpdateManyAndReturnArgs} args - Arguments to update many Produks.
   * @example
   * // Update many Produks
   * const produk = await prisma.produk.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Produks and only return the `id`
   * const produkWithIdOnly = await prisma.produk.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends produkUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, produkUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$produkPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Produk.
   * @param {produkUpsertArgs} args - Arguments to update or create a Produk.
   * @example
   * // Update or create a Produk
   * const produk = await prisma.produk.upsert({
   *   create: {
   *     // ... data to create a Produk
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Produk we want to update
   *   }
   * })
   */
  upsert<T extends produkUpsertArgs>(args: Prisma.SelectSubset<T, produkUpsertArgs<ExtArgs>>): Prisma.Prisma__produkClient<runtime.Types.Result.GetResult<Prisma.$produkPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Produks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {produkCountArgs} args - Arguments to filter Produks to count.
   * @example
   * // Count the number of Produks
   * const count = await prisma.produk.count({
   *   where: {
   *     // ... the filter for the Produks we want to count
   *   }
   * })
  **/
  count<T extends produkCountArgs>(
    args?: Prisma.Subset<T, produkCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ProdukCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Produk.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProdukAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ProdukAggregateArgs>(args: Prisma.Subset<T, ProdukAggregateArgs>): Prisma.PrismaPromise<GetProdukAggregateType<T>>

  /**
   * Group by Produk.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {produkGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends produkGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: produkGroupByArgs['orderBy'] }
      : { orderBy?: produkGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, produkGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProdukGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the produk model
 */
readonly fields: produkFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for produk.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__produkClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  kategori<T extends Prisma.categoryDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.categoryDefaultArgs<ExtArgs>>): Prisma.Prisma__categoryClient<runtime.Types.Result.GetResult<Prisma.$categoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  vendors<T extends Prisma.vendorsDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.vendorsDefaultArgs<ExtArgs>>): Prisma.Prisma__vendorsClient<runtime.Types.Result.GetResult<Prisma.$vendorsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  lokasi<T extends Prisma.lokasi_gudangDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.lokasi_gudangDefaultArgs<ExtArgs>>): Prisma.Prisma__lokasi_gudangClient<runtime.Types.Result.GetResult<Prisma.$lokasi_gudangPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  inbound<T extends Prisma.produk$inboundArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.produk$inboundArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$barang_masukPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  outbound<T extends Prisma.produk$outboundArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.produk$outboundArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$barang_keluarPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the produk model
 */
export interface produkFieldRefs {
  readonly id: Prisma.FieldRef<"produk", 'Int'>
  readonly nama_produk: Prisma.FieldRef<"produk", 'String'>
  readonly kategoriId: Prisma.FieldRef<"produk", 'Int'>
  readonly vendorsId: Prisma.FieldRef<"produk", 'Int'>
  readonly jumlah: Prisma.FieldRef<"produk", 'Int'>
  readonly lokasiId: Prisma.FieldRef<"produk", 'Int'>
}
    

// Custom InputTypes
/**
 * produk findUnique
 */
export type produkFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the produk
   */
  select?: Prisma.produkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the produk
   */
  omit?: Prisma.produkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.produkInclude<ExtArgs> | null
  /**
   * Filter, which produk to fetch.
   */
  where: Prisma.produkWhereUniqueInput
}

/**
 * produk findUniqueOrThrow
 */
export type produkFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the produk
   */
  select?: Prisma.produkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the produk
   */
  omit?: Prisma.produkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.produkInclude<ExtArgs> | null
  /**
   * Filter, which produk to fetch.
   */
  where: Prisma.produkWhereUniqueInput
}

/**
 * produk findFirst
 */
export type produkFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the produk
   */
  select?: Prisma.produkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the produk
   */
  omit?: Prisma.produkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.produkInclude<ExtArgs> | null
  /**
   * Filter, which produk to fetch.
   */
  where?: Prisma.produkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of produks to fetch.
   */
  orderBy?: Prisma.produkOrderByWithRelationInput | Prisma.produkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for produks.
   */
  cursor?: Prisma.produkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` produks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` produks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of produks.
   */
  distinct?: Prisma.ProdukScalarFieldEnum | Prisma.ProdukScalarFieldEnum[]
}

/**
 * produk findFirstOrThrow
 */
export type produkFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the produk
   */
  select?: Prisma.produkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the produk
   */
  omit?: Prisma.produkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.produkInclude<ExtArgs> | null
  /**
   * Filter, which produk to fetch.
   */
  where?: Prisma.produkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of produks to fetch.
   */
  orderBy?: Prisma.produkOrderByWithRelationInput | Prisma.produkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for produks.
   */
  cursor?: Prisma.produkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` produks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` produks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of produks.
   */
  distinct?: Prisma.ProdukScalarFieldEnum | Prisma.ProdukScalarFieldEnum[]
}

/**
 * produk findMany
 */
export type produkFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the produk
   */
  select?: Prisma.produkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the produk
   */
  omit?: Prisma.produkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.produkInclude<ExtArgs> | null
  /**
   * Filter, which produks to fetch.
   */
  where?: Prisma.produkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of produks to fetch.
   */
  orderBy?: Prisma.produkOrderByWithRelationInput | Prisma.produkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing produks.
   */
  cursor?: Prisma.produkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` produks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` produks.
   */
  skip?: number
  distinct?: Prisma.ProdukScalarFieldEnum | Prisma.ProdukScalarFieldEnum[]
}

/**
 * produk create
 */
export type produkCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the produk
   */
  select?: Prisma.produkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the produk
   */
  omit?: Prisma.produkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.produkInclude<ExtArgs> | null
  /**
   * The data needed to create a produk.
   */
  data: Prisma.XOR<Prisma.produkCreateInput, Prisma.produkUncheckedCreateInput>
}

/**
 * produk createMany
 */
export type produkCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many produks.
   */
  data: Prisma.produkCreateManyInput | Prisma.produkCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * produk createManyAndReturn
 */
export type produkCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the produk
   */
  select?: Prisma.produkSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the produk
   */
  omit?: Prisma.produkOmit<ExtArgs> | null
  /**
   * The data used to create many produks.
   */
  data: Prisma.produkCreateManyInput | Prisma.produkCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.produkIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * produk update
 */
export type produkUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the produk
   */
  select?: Prisma.produkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the produk
   */
  omit?: Prisma.produkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.produkInclude<ExtArgs> | null
  /**
   * The data needed to update a produk.
   */
  data: Prisma.XOR<Prisma.produkUpdateInput, Prisma.produkUncheckedUpdateInput>
  /**
   * Choose, which produk to update.
   */
  where: Prisma.produkWhereUniqueInput
}

/**
 * produk updateMany
 */
export type produkUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update produks.
   */
  data: Prisma.XOR<Prisma.produkUpdateManyMutationInput, Prisma.produkUncheckedUpdateManyInput>
  /**
   * Filter which produks to update
   */
  where?: Prisma.produkWhereInput
  /**
   * Limit how many produks to update.
   */
  limit?: number
}

/**
 * produk updateManyAndReturn
 */
export type produkUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the produk
   */
  select?: Prisma.produkSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the produk
   */
  omit?: Prisma.produkOmit<ExtArgs> | null
  /**
   * The data used to update produks.
   */
  data: Prisma.XOR<Prisma.produkUpdateManyMutationInput, Prisma.produkUncheckedUpdateManyInput>
  /**
   * Filter which produks to update
   */
  where?: Prisma.produkWhereInput
  /**
   * Limit how many produks to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.produkIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * produk upsert
 */
export type produkUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the produk
   */
  select?: Prisma.produkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the produk
   */
  omit?: Prisma.produkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.produkInclude<ExtArgs> | null
  /**
   * The filter to search for the produk to update in case it exists.
   */
  where: Prisma.produkWhereUniqueInput
  /**
   * In case the produk found by the `where` argument doesn't exist, create a new produk with this data.
   */
  create: Prisma.XOR<Prisma.produkCreateInput, Prisma.produkUncheckedCreateInput>
  /**
   * In case the produk was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.produkUpdateInput, Prisma.produkUncheckedUpdateInput>
}

/**
 * produk delete
 */
export type produkDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the produk
   */
  select?: Prisma.produkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the produk
   */
  omit?: Prisma.produkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.produkInclude<ExtArgs> | null
  /**
   * Filter which produk to delete.
   */
  where: Prisma.produkWhereUniqueInput
}

/**
 * produk deleteMany
 */
export type produkDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which produks to delete
   */
  where?: Prisma.produkWhereInput
  /**
   * Limit how many produks to delete.
   */
  limit?: number
}

/**
 * produk.inbound
 */
export type produk$inboundArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the barang_masuk
   */
  select?: Prisma.barang_masukSelect<ExtArgs> | null
  /**
   * Omit specific fields from the barang_masuk
   */
  omit?: Prisma.barang_masukOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.barang_masukInclude<ExtArgs> | null
  where?: Prisma.barang_masukWhereInput
  orderBy?: Prisma.barang_masukOrderByWithRelationInput | Prisma.barang_masukOrderByWithRelationInput[]
  cursor?: Prisma.barang_masukWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Barang_masukScalarFieldEnum | Prisma.Barang_masukScalarFieldEnum[]
}

/**
 * produk.outbound
 */
export type produk$outboundArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the barang_keluar
   */
  select?: Prisma.barang_keluarSelect<ExtArgs> | null
  /**
   * Omit specific fields from the barang_keluar
   */
  omit?: Prisma.barang_keluarOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.barang_keluarInclude<ExtArgs> | null
  where?: Prisma.barang_keluarWhereInput
  orderBy?: Prisma.barang_keluarOrderByWithRelationInput | Prisma.barang_keluarOrderByWithRelationInput[]
  cursor?: Prisma.barang_keluarWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Barang_keluarScalarFieldEnum | Prisma.Barang_keluarScalarFieldEnum[]
}

/**
 * produk without action
 */
export type produkDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the produk
   */
  select?: Prisma.produkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the produk
   */
  omit?: Prisma.produkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.produkInclude<ExtArgs> | null
}
