
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `vendors` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model vendors
 * 
 */
export type vendorsModel = runtime.Types.Result.DefaultSelection<Prisma.$vendorsPayload>

export type AggregateVendors = {
  _count: VendorsCountAggregateOutputType | null
  _avg: VendorsAvgAggregateOutputType | null
  _sum: VendorsSumAggregateOutputType | null
  _min: VendorsMinAggregateOutputType | null
  _max: VendorsMaxAggregateOutputType | null
}

export type VendorsAvgAggregateOutputType = {
  id: number | null
}

export type VendorsSumAggregateOutputType = {
  id: number | null
}

export type VendorsMinAggregateOutputType = {
  id: number | null
  nama_vendor: string | null
  warna_vendor: string | null
  alamat_vendor: string | null
}

export type VendorsMaxAggregateOutputType = {
  id: number | null
  nama_vendor: string | null
  warna_vendor: string | null
  alamat_vendor: string | null
}

export type VendorsCountAggregateOutputType = {
  id: number
  nama_vendor: number
  warna_vendor: number
  alamat_vendor: number
  _all: number
}


export type VendorsAvgAggregateInputType = {
  id?: true
}

export type VendorsSumAggregateInputType = {
  id?: true
}

export type VendorsMinAggregateInputType = {
  id?: true
  nama_vendor?: true
  warna_vendor?: true
  alamat_vendor?: true
}

export type VendorsMaxAggregateInputType = {
  id?: true
  nama_vendor?: true
  warna_vendor?: true
  alamat_vendor?: true
}

export type VendorsCountAggregateInputType = {
  id?: true
  nama_vendor?: true
  warna_vendor?: true
  alamat_vendor?: true
  _all?: true
}

export type VendorsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which vendors to aggregate.
   */
  where?: Prisma.vendorsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of vendors to fetch.
   */
  orderBy?: Prisma.vendorsOrderByWithRelationInput | Prisma.vendorsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.vendorsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` vendors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` vendors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned vendors
  **/
  _count?: true | VendorsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: VendorsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: VendorsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: VendorsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: VendorsMaxAggregateInputType
}

export type GetVendorsAggregateType<T extends VendorsAggregateArgs> = {
      [P in keyof T & keyof AggregateVendors]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateVendors[P]>
    : Prisma.GetScalarType<T[P], AggregateVendors[P]>
}




export type vendorsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.vendorsWhereInput
  orderBy?: Prisma.vendorsOrderByWithAggregationInput | Prisma.vendorsOrderByWithAggregationInput[]
  by: Prisma.VendorsScalarFieldEnum[] | Prisma.VendorsScalarFieldEnum
  having?: Prisma.vendorsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: VendorsCountAggregateInputType | true
  _avg?: VendorsAvgAggregateInputType
  _sum?: VendorsSumAggregateInputType
  _min?: VendorsMinAggregateInputType
  _max?: VendorsMaxAggregateInputType
}

export type VendorsGroupByOutputType = {
  id: number
  nama_vendor: string
  warna_vendor: string
  alamat_vendor: string
  _count: VendorsCountAggregateOutputType | null
  _avg: VendorsAvgAggregateOutputType | null
  _sum: VendorsSumAggregateOutputType | null
  _min: VendorsMinAggregateOutputType | null
  _max: VendorsMaxAggregateOutputType | null
}

type GetVendorsGroupByPayload<T extends vendorsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<VendorsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof VendorsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], VendorsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], VendorsGroupByOutputType[P]>
      }
    >
  >



export type vendorsWhereInput = {
  AND?: Prisma.vendorsWhereInput | Prisma.vendorsWhereInput[]
  OR?: Prisma.vendorsWhereInput[]
  NOT?: Prisma.vendorsWhereInput | Prisma.vendorsWhereInput[]
  id?: Prisma.IntFilter<"vendors"> | number
  nama_vendor?: Prisma.StringFilter<"vendors"> | string
  warna_vendor?: Prisma.StringFilter<"vendors"> | string
  alamat_vendor?: Prisma.StringFilter<"vendors"> | string
  produk?: Prisma.ProdukListRelationFilter
}

export type vendorsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  nama_vendor?: Prisma.SortOrder
  warna_vendor?: Prisma.SortOrder
  alamat_vendor?: Prisma.SortOrder
  produk?: Prisma.produkOrderByRelationAggregateInput
}

export type vendorsWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.vendorsWhereInput | Prisma.vendorsWhereInput[]
  OR?: Prisma.vendorsWhereInput[]
  NOT?: Prisma.vendorsWhereInput | Prisma.vendorsWhereInput[]
  nama_vendor?: Prisma.StringFilter<"vendors"> | string
  warna_vendor?: Prisma.StringFilter<"vendors"> | string
  alamat_vendor?: Prisma.StringFilter<"vendors"> | string
  produk?: Prisma.ProdukListRelationFilter
}, "id">

export type vendorsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  nama_vendor?: Prisma.SortOrder
  warna_vendor?: Prisma.SortOrder
  alamat_vendor?: Prisma.SortOrder
  _count?: Prisma.vendorsCountOrderByAggregateInput
  _avg?: Prisma.vendorsAvgOrderByAggregateInput
  _max?: Prisma.vendorsMaxOrderByAggregateInput
  _min?: Prisma.vendorsMinOrderByAggregateInput
  _sum?: Prisma.vendorsSumOrderByAggregateInput
}

export type vendorsScalarWhereWithAggregatesInput = {
  AND?: Prisma.vendorsScalarWhereWithAggregatesInput | Prisma.vendorsScalarWhereWithAggregatesInput[]
  OR?: Prisma.vendorsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.vendorsScalarWhereWithAggregatesInput | Prisma.vendorsScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"vendors"> | number
  nama_vendor?: Prisma.StringWithAggregatesFilter<"vendors"> | string
  warna_vendor?: Prisma.StringWithAggregatesFilter<"vendors"> | string
  alamat_vendor?: Prisma.StringWithAggregatesFilter<"vendors"> | string
}

export type vendorsCreateInput = {
  nama_vendor: string
  warna_vendor: string
  alamat_vendor: string
  produk?: Prisma.produkCreateNestedManyWithoutVendorsInput
}

export type vendorsUncheckedCreateInput = {
  id?: number
  nama_vendor: string
  warna_vendor: string
  alamat_vendor: string
  produk?: Prisma.produkUncheckedCreateNestedManyWithoutVendorsInput
}

export type vendorsUpdateInput = {
  nama_vendor?: Prisma.StringFieldUpdateOperationsInput | string
  warna_vendor?: Prisma.StringFieldUpdateOperationsInput | string
  alamat_vendor?: Prisma.StringFieldUpdateOperationsInput | string
  produk?: Prisma.produkUpdateManyWithoutVendorsNestedInput
}

export type vendorsUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  nama_vendor?: Prisma.StringFieldUpdateOperationsInput | string
  warna_vendor?: Prisma.StringFieldUpdateOperationsInput | string
  alamat_vendor?: Prisma.StringFieldUpdateOperationsInput | string
  produk?: Prisma.produkUncheckedUpdateManyWithoutVendorsNestedInput
}

export type vendorsCreateManyInput = {
  id?: number
  nama_vendor: string
  warna_vendor: string
  alamat_vendor: string
}

export type vendorsUpdateManyMutationInput = {
  nama_vendor?: Prisma.StringFieldUpdateOperationsInput | string
  warna_vendor?: Prisma.StringFieldUpdateOperationsInput | string
  alamat_vendor?: Prisma.StringFieldUpdateOperationsInput | string
}

export type vendorsUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  nama_vendor?: Prisma.StringFieldUpdateOperationsInput | string
  warna_vendor?: Prisma.StringFieldUpdateOperationsInput | string
  alamat_vendor?: Prisma.StringFieldUpdateOperationsInput | string
}

export type vendorsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nama_vendor?: Prisma.SortOrder
  warna_vendor?: Prisma.SortOrder
  alamat_vendor?: Prisma.SortOrder
}

export type vendorsAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type vendorsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nama_vendor?: Prisma.SortOrder
  warna_vendor?: Prisma.SortOrder
  alamat_vendor?: Prisma.SortOrder
}

export type vendorsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nama_vendor?: Prisma.SortOrder
  warna_vendor?: Prisma.SortOrder
  alamat_vendor?: Prisma.SortOrder
}

export type vendorsSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type VendorsScalarRelationFilter = {
  is?: Prisma.vendorsWhereInput
  isNot?: Prisma.vendorsWhereInput
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type vendorsCreateNestedOneWithoutProdukInput = {
  create?: Prisma.XOR<Prisma.vendorsCreateWithoutProdukInput, Prisma.vendorsUncheckedCreateWithoutProdukInput>
  connectOrCreate?: Prisma.vendorsCreateOrConnectWithoutProdukInput
  connect?: Prisma.vendorsWhereUniqueInput
}

export type vendorsUpdateOneRequiredWithoutProdukNestedInput = {
  create?: Prisma.XOR<Prisma.vendorsCreateWithoutProdukInput, Prisma.vendorsUncheckedCreateWithoutProdukInput>
  connectOrCreate?: Prisma.vendorsCreateOrConnectWithoutProdukInput
  upsert?: Prisma.vendorsUpsertWithoutProdukInput
  connect?: Prisma.vendorsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.vendorsUpdateToOneWithWhereWithoutProdukInput, Prisma.vendorsUpdateWithoutProdukInput>, Prisma.vendorsUncheckedUpdateWithoutProdukInput>
}

export type vendorsCreateWithoutProdukInput = {
  nama_vendor: string
  warna_vendor: string
  alamat_vendor: string
}

export type vendorsUncheckedCreateWithoutProdukInput = {
  id?: number
  nama_vendor: string
  warna_vendor: string
  alamat_vendor: string
}

export type vendorsCreateOrConnectWithoutProdukInput = {
  where: Prisma.vendorsWhereUniqueInput
  create: Prisma.XOR<Prisma.vendorsCreateWithoutProdukInput, Prisma.vendorsUncheckedCreateWithoutProdukInput>
}

export type vendorsUpsertWithoutProdukInput = {
  update: Prisma.XOR<Prisma.vendorsUpdateWithoutProdukInput, Prisma.vendorsUncheckedUpdateWithoutProdukInput>
  create: Prisma.XOR<Prisma.vendorsCreateWithoutProdukInput, Prisma.vendorsUncheckedCreateWithoutProdukInput>
  where?: Prisma.vendorsWhereInput
}

export type vendorsUpdateToOneWithWhereWithoutProdukInput = {
  where?: Prisma.vendorsWhereInput
  data: Prisma.XOR<Prisma.vendorsUpdateWithoutProdukInput, Prisma.vendorsUncheckedUpdateWithoutProdukInput>
}

export type vendorsUpdateWithoutProdukInput = {
  nama_vendor?: Prisma.StringFieldUpdateOperationsInput | string
  warna_vendor?: Prisma.StringFieldUpdateOperationsInput | string
  alamat_vendor?: Prisma.StringFieldUpdateOperationsInput | string
}

export type vendorsUncheckedUpdateWithoutProdukInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  nama_vendor?: Prisma.StringFieldUpdateOperationsInput | string
  warna_vendor?: Prisma.StringFieldUpdateOperationsInput | string
  alamat_vendor?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type VendorsCountOutputType
 */

export type VendorsCountOutputType = {
  produk: number
}

export type VendorsCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  produk?: boolean | VendorsCountOutputTypeCountProdukArgs
}

/**
 * VendorsCountOutputType without action
 */
export type VendorsCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VendorsCountOutputType
   */
  select?: Prisma.VendorsCountOutputTypeSelect<ExtArgs> | null
}

/**
 * VendorsCountOutputType without action
 */
export type VendorsCountOutputTypeCountProdukArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.produkWhereInput
}


export type vendorsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nama_vendor?: boolean
  warna_vendor?: boolean
  alamat_vendor?: boolean
  produk?: boolean | Prisma.vendors$produkArgs<ExtArgs>
  _count?: boolean | Prisma.VendorsCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["vendors"]>

export type vendorsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nama_vendor?: boolean
  warna_vendor?: boolean
  alamat_vendor?: boolean
}, ExtArgs["result"]["vendors"]>

export type vendorsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nama_vendor?: boolean
  warna_vendor?: boolean
  alamat_vendor?: boolean
}, ExtArgs["result"]["vendors"]>

export type vendorsSelectScalar = {
  id?: boolean
  nama_vendor?: boolean
  warna_vendor?: boolean
  alamat_vendor?: boolean
}

export type vendorsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "nama_vendor" | "warna_vendor" | "alamat_vendor", ExtArgs["result"]["vendors"]>
export type vendorsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  produk?: boolean | Prisma.vendors$produkArgs<ExtArgs>
  _count?: boolean | Prisma.VendorsCountOutputTypeDefaultArgs<ExtArgs>
}
export type vendorsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type vendorsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $vendorsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "vendors"
  objects: {
    produk: Prisma.$produkPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    nama_vendor: string
    warna_vendor: string
    alamat_vendor: string
  }, ExtArgs["result"]["vendors"]>
  composites: {}
}

export type vendorsGetPayload<S extends boolean | null | undefined | vendorsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$vendorsPayload, S>

export type vendorsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<vendorsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: VendorsCountAggregateInputType | true
  }

export interface vendorsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['vendors'], meta: { name: 'vendors' } }
  /**
   * Find zero or one Vendors that matches the filter.
   * @param {vendorsFindUniqueArgs} args - Arguments to find a Vendors
   * @example
   * // Get one Vendors
   * const vendors = await prisma.vendors.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends vendorsFindUniqueArgs>(args: Prisma.SelectSubset<T, vendorsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__vendorsClient<runtime.Types.Result.GetResult<Prisma.$vendorsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Vendors that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {vendorsFindUniqueOrThrowArgs} args - Arguments to find a Vendors
   * @example
   * // Get one Vendors
   * const vendors = await prisma.vendors.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends vendorsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, vendorsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__vendorsClient<runtime.Types.Result.GetResult<Prisma.$vendorsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Vendors that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {vendorsFindFirstArgs} args - Arguments to find a Vendors
   * @example
   * // Get one Vendors
   * const vendors = await prisma.vendors.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends vendorsFindFirstArgs>(args?: Prisma.SelectSubset<T, vendorsFindFirstArgs<ExtArgs>>): Prisma.Prisma__vendorsClient<runtime.Types.Result.GetResult<Prisma.$vendorsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Vendors that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {vendorsFindFirstOrThrowArgs} args - Arguments to find a Vendors
   * @example
   * // Get one Vendors
   * const vendors = await prisma.vendors.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends vendorsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, vendorsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__vendorsClient<runtime.Types.Result.GetResult<Prisma.$vendorsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Vendors that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {vendorsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Vendors
   * const vendors = await prisma.vendors.findMany()
   * 
   * // Get first 10 Vendors
   * const vendors = await prisma.vendors.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const vendorsWithIdOnly = await prisma.vendors.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends vendorsFindManyArgs>(args?: Prisma.SelectSubset<T, vendorsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$vendorsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Vendors.
   * @param {vendorsCreateArgs} args - Arguments to create a Vendors.
   * @example
   * // Create one Vendors
   * const Vendors = await prisma.vendors.create({
   *   data: {
   *     // ... data to create a Vendors
   *   }
   * })
   * 
   */
  create<T extends vendorsCreateArgs>(args: Prisma.SelectSubset<T, vendorsCreateArgs<ExtArgs>>): Prisma.Prisma__vendorsClient<runtime.Types.Result.GetResult<Prisma.$vendorsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Vendors.
   * @param {vendorsCreateManyArgs} args - Arguments to create many Vendors.
   * @example
   * // Create many Vendors
   * const vendors = await prisma.vendors.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends vendorsCreateManyArgs>(args?: Prisma.SelectSubset<T, vendorsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Vendors and returns the data saved in the database.
   * @param {vendorsCreateManyAndReturnArgs} args - Arguments to create many Vendors.
   * @example
   * // Create many Vendors
   * const vendors = await prisma.vendors.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Vendors and only return the `id`
   * const vendorsWithIdOnly = await prisma.vendors.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends vendorsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, vendorsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$vendorsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Vendors.
   * @param {vendorsDeleteArgs} args - Arguments to delete one Vendors.
   * @example
   * // Delete one Vendors
   * const Vendors = await prisma.vendors.delete({
   *   where: {
   *     // ... filter to delete one Vendors
   *   }
   * })
   * 
   */
  delete<T extends vendorsDeleteArgs>(args: Prisma.SelectSubset<T, vendorsDeleteArgs<ExtArgs>>): Prisma.Prisma__vendorsClient<runtime.Types.Result.GetResult<Prisma.$vendorsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Vendors.
   * @param {vendorsUpdateArgs} args - Arguments to update one Vendors.
   * @example
   * // Update one Vendors
   * const vendors = await prisma.vendors.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends vendorsUpdateArgs>(args: Prisma.SelectSubset<T, vendorsUpdateArgs<ExtArgs>>): Prisma.Prisma__vendorsClient<runtime.Types.Result.GetResult<Prisma.$vendorsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Vendors.
   * @param {vendorsDeleteManyArgs} args - Arguments to filter Vendors to delete.
   * @example
   * // Delete a few Vendors
   * const { count } = await prisma.vendors.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends vendorsDeleteManyArgs>(args?: Prisma.SelectSubset<T, vendorsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Vendors.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {vendorsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Vendors
   * const vendors = await prisma.vendors.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends vendorsUpdateManyArgs>(args: Prisma.SelectSubset<T, vendorsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Vendors and returns the data updated in the database.
   * @param {vendorsUpdateManyAndReturnArgs} args - Arguments to update many Vendors.
   * @example
   * // Update many Vendors
   * const vendors = await prisma.vendors.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Vendors and only return the `id`
   * const vendorsWithIdOnly = await prisma.vendors.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends vendorsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, vendorsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$vendorsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Vendors.
   * @param {vendorsUpsertArgs} args - Arguments to update or create a Vendors.
   * @example
   * // Update or create a Vendors
   * const vendors = await prisma.vendors.upsert({
   *   create: {
   *     // ... data to create a Vendors
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Vendors we want to update
   *   }
   * })
   */
  upsert<T extends vendorsUpsertArgs>(args: Prisma.SelectSubset<T, vendorsUpsertArgs<ExtArgs>>): Prisma.Prisma__vendorsClient<runtime.Types.Result.GetResult<Prisma.$vendorsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Vendors.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {vendorsCountArgs} args - Arguments to filter Vendors to count.
   * @example
   * // Count the number of Vendors
   * const count = await prisma.vendors.count({
   *   where: {
   *     // ... the filter for the Vendors we want to count
   *   }
   * })
  **/
  count<T extends vendorsCountArgs>(
    args?: Prisma.Subset<T, vendorsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], VendorsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Vendors.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VendorsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends VendorsAggregateArgs>(args: Prisma.Subset<T, VendorsAggregateArgs>): Prisma.PrismaPromise<GetVendorsAggregateType<T>>

  /**
   * Group by Vendors.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {vendorsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends vendorsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: vendorsGroupByArgs['orderBy'] }
      : { orderBy?: vendorsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, vendorsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetVendorsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the vendors model
 */
readonly fields: vendorsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for vendors.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__vendorsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  produk<T extends Prisma.vendors$produkArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.vendors$produkArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$produkPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the vendors model
 */
export interface vendorsFieldRefs {
  readonly id: Prisma.FieldRef<"vendors", 'Int'>
  readonly nama_vendor: Prisma.FieldRef<"vendors", 'String'>
  readonly warna_vendor: Prisma.FieldRef<"vendors", 'String'>
  readonly alamat_vendor: Prisma.FieldRef<"vendors", 'String'>
}
    

// Custom InputTypes
/**
 * vendors findUnique
 */
export type vendorsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the vendors
   */
  select?: Prisma.vendorsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the vendors
   */
  omit?: Prisma.vendorsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.vendorsInclude<ExtArgs> | null
  /**
   * Filter, which vendors to fetch.
   */
  where: Prisma.vendorsWhereUniqueInput
}

/**
 * vendors findUniqueOrThrow
 */
export type vendorsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the vendors
   */
  select?: Prisma.vendorsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the vendors
   */
  omit?: Prisma.vendorsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.vendorsInclude<ExtArgs> | null
  /**
   * Filter, which vendors to fetch.
   */
  where: Prisma.vendorsWhereUniqueInput
}

/**
 * vendors findFirst
 */
export type vendorsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the vendors
   */
  select?: Prisma.vendorsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the vendors
   */
  omit?: Prisma.vendorsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.vendorsInclude<ExtArgs> | null
  /**
   * Filter, which vendors to fetch.
   */
  where?: Prisma.vendorsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of vendors to fetch.
   */
  orderBy?: Prisma.vendorsOrderByWithRelationInput | Prisma.vendorsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for vendors.
   */
  cursor?: Prisma.vendorsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` vendors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` vendors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of vendors.
   */
  distinct?: Prisma.VendorsScalarFieldEnum | Prisma.VendorsScalarFieldEnum[]
}

/**
 * vendors findFirstOrThrow
 */
export type vendorsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the vendors
   */
  select?: Prisma.vendorsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the vendors
   */
  omit?: Prisma.vendorsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.vendorsInclude<ExtArgs> | null
  /**
   * Filter, which vendors to fetch.
   */
  where?: Prisma.vendorsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of vendors to fetch.
   */
  orderBy?: Prisma.vendorsOrderByWithRelationInput | Prisma.vendorsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for vendors.
   */
  cursor?: Prisma.vendorsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` vendors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` vendors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of vendors.
   */
  distinct?: Prisma.VendorsScalarFieldEnum | Prisma.VendorsScalarFieldEnum[]
}

/**
 * vendors findMany
 */
export type vendorsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the vendors
   */
  select?: Prisma.vendorsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the vendors
   */
  omit?: Prisma.vendorsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.vendorsInclude<ExtArgs> | null
  /**
   * Filter, which vendors to fetch.
   */
  where?: Prisma.vendorsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of vendors to fetch.
   */
  orderBy?: Prisma.vendorsOrderByWithRelationInput | Prisma.vendorsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing vendors.
   */
  cursor?: Prisma.vendorsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` vendors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` vendors.
   */
  skip?: number
  distinct?: Prisma.VendorsScalarFieldEnum | Prisma.VendorsScalarFieldEnum[]
}

/**
 * vendors create
 */
export type vendorsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the vendors
   */
  select?: Prisma.vendorsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the vendors
   */
  omit?: Prisma.vendorsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.vendorsInclude<ExtArgs> | null
  /**
   * The data needed to create a vendors.
   */
  data: Prisma.XOR<Prisma.vendorsCreateInput, Prisma.vendorsUncheckedCreateInput>
}

/**
 * vendors createMany
 */
export type vendorsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many vendors.
   */
  data: Prisma.vendorsCreateManyInput | Prisma.vendorsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * vendors createManyAndReturn
 */
export type vendorsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the vendors
   */
  select?: Prisma.vendorsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the vendors
   */
  omit?: Prisma.vendorsOmit<ExtArgs> | null
  /**
   * The data used to create many vendors.
   */
  data: Prisma.vendorsCreateManyInput | Prisma.vendorsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * vendors update
 */
export type vendorsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the vendors
   */
  select?: Prisma.vendorsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the vendors
   */
  omit?: Prisma.vendorsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.vendorsInclude<ExtArgs> | null
  /**
   * The data needed to update a vendors.
   */
  data: Prisma.XOR<Prisma.vendorsUpdateInput, Prisma.vendorsUncheckedUpdateInput>
  /**
   * Choose, which vendors to update.
   */
  where: Prisma.vendorsWhereUniqueInput
}

/**
 * vendors updateMany
 */
export type vendorsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update vendors.
   */
  data: Prisma.XOR<Prisma.vendorsUpdateManyMutationInput, Prisma.vendorsUncheckedUpdateManyInput>
  /**
   * Filter which vendors to update
   */
  where?: Prisma.vendorsWhereInput
  /**
   * Limit how many vendors to update.
   */
  limit?: number
}

/**
 * vendors updateManyAndReturn
 */
export type vendorsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the vendors
   */
  select?: Prisma.vendorsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the vendors
   */
  omit?: Prisma.vendorsOmit<ExtArgs> | null
  /**
   * The data used to update vendors.
   */
  data: Prisma.XOR<Prisma.vendorsUpdateManyMutationInput, Prisma.vendorsUncheckedUpdateManyInput>
  /**
   * Filter which vendors to update
   */
  where?: Prisma.vendorsWhereInput
  /**
   * Limit how many vendors to update.
   */
  limit?: number
}

/**
 * vendors upsert
 */
export type vendorsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the vendors
   */
  select?: Prisma.vendorsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the vendors
   */
  omit?: Prisma.vendorsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.vendorsInclude<ExtArgs> | null
  /**
   * The filter to search for the vendors to update in case it exists.
   */
  where: Prisma.vendorsWhereUniqueInput
  /**
   * In case the vendors found by the `where` argument doesn't exist, create a new vendors with this data.
   */
  create: Prisma.XOR<Prisma.vendorsCreateInput, Prisma.vendorsUncheckedCreateInput>
  /**
   * In case the vendors was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.vendorsUpdateInput, Prisma.vendorsUncheckedUpdateInput>
}

/**
 * vendors delete
 */
export type vendorsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the vendors
   */
  select?: Prisma.vendorsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the vendors
   */
  omit?: Prisma.vendorsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.vendorsInclude<ExtArgs> | null
  /**
   * Filter which vendors to delete.
   */
  where: Prisma.vendorsWhereUniqueInput
}

/**
 * vendors deleteMany
 */
export type vendorsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which vendors to delete
   */
  where?: Prisma.vendorsWhereInput
  /**
   * Limit how many vendors to delete.
   */
  limit?: number
}

/**
 * vendors.produk
 */
export type vendors$produkArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the produk
   */
  select?: Prisma.produkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the produk
   */
  omit?: Prisma.produkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.produkInclude<ExtArgs> | null
  where?: Prisma.produkWhereInput
  orderBy?: Prisma.produkOrderByWithRelationInput | Prisma.produkOrderByWithRelationInput[]
  cursor?: Prisma.produkWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ProdukScalarFieldEnum | Prisma.ProdukScalarFieldEnum[]
}

/**
 * vendors without action
 */
export type vendorsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the vendors
   */
  select?: Prisma.vendorsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the vendors
   */
  omit?: Prisma.vendorsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.vendorsInclude<ExtArgs> | null
}
