
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model vendors
 * 
 */
export type vendors = Prisma.vendorsModel
/**
 * Model category
 * 
 */
export type category = Prisma.categoryModel
/**
 * Model lokasi_gudang
 * 
 */
export type lokasi_gudang = Prisma.lokasi_gudangModel
/**
 * Model produk
 * 
 */
export type produk = Prisma.produkModel
/**
 * Model barang_masuk
 * 
 */
export type barang_masuk = Prisma.barang_masukModel
/**
 * Model barang_keluar
 * 
 */
export type barang_keluar = Prisma.barang_keluarModel
