
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/vendors'
export type * from './models/category'
export type * from './models/lokasi_gudang'
export type * from './models/produk'
export type * from './models/barang_masuk'
export type * from './models/barang_keluar'
export type * from './commonInputTypes'